### ISSUE TITLE
Issue: Comfortable Clothes and Bimbo Skirt are broken

### ISSUE THREAD

**Issue by AzumaEros** [Kitteh6660/Corruption-of-Champions-Mod#1004]
### Overview
	Attempting to unequip Comfortable Clothes freezes the game. Attempting to equip Bimbo Skirt also freezes. When it finally unfreezes it says 'You cannot use NOTHING' and the armor you tried to use to replace the comfortable clothes, or the bimbo skirt disappear from the inventory entirely. Untested for other armors.
	
### Game version
	1.0.2_mod_1.4.10b
	
### Expected behaviour
	Equipping and un-equipping different armors should function normally.
	
### Actual behaviour
	Equipping the bimbo skirt or even equipping different armor on a character wearing comfortable clothes is impossible. using Unequip to remove comfortable clothes is also impossible. 

### Steps to reproduce the issue

1.  Make a new character.
2.  Unequip comfortable clothes. or attempt to equip bimbo skirt.
3. Freeze

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

**Comment by Kitteh6660** [comment]
I've attempted to unequip comfortable clothes and it works fine.

I'll put out 1.4.11 eventually. If the issue still persists, let me know.
