### ISSUE TITLE
Problem with using Test Input

### ISSUE THREAD

**Issue by JustPassingThrough99** [Kitteh6660/Corruption-of-Champions-Mod#1008]
Hey guys,
I'm trying to use the Test Input function, but I'm having no luck so far.
Essentially, I'm trying to access certain scenes for testing, such as "giveALLTHELETHICITES", but every time I try with that or with different functions I get just a blank screen with a Next button.

The syntax that I'm using is (using that particular scene as an example): HellHoundScene.HellHoundMasterEncounter.giveALLTHELETHICITES | test

I tried several varieties of syntax as well and I checked the capitalization. 
What am I doing wrong?
Thanks again for helping!

**Comment by brrritssocold** [comment]
Can you provide a code example?

A branch with a commit would probably be best, or you could paste a code snippet or attach a file to this issue.

For pasting code:
 on a new line(repace % with `): %%%actionscript then new line, paste the code, then on a new line add %%%

that will give you something like this:
```actionscript
		/**
		 * Just a test
		 */
		public function justTesting(): void {
			
		}
```

**Comment by Stadler76** [comment]
@brrritssocold wrote:
> How are you running the test? Debug build and debug player?

It's an ingame testing feature found in \[Main Menu\] → \[Debug Info\] → \[Test Input\]
And its available in release builds, too.

Hitting \[Proceed\] without changing the textarea directly throws an exception:
```
 [Fault] exception, information=ReferenceError: Error #1056: Cannot create property currentText on classes.CoC.
```

Stack trace:
```
classes.Parser::Parser/recursiveParser at H:\GitHub\Corruption-of-Champions-Mod\classes\classes\Parser\Parser.as:1120
classes::Output/_addText at H:\GitHub\Corruption-of-Champions-Mod\classes\classes\Output.as:56
classes::Output/text at H:\GitHub\Corruption-of-Champions-Mod\classes\classes\Output.as:74
classes::CoC/outputText at H:\GitHub\Corruption-of-Champions-Mod\includes\engineCore.as:153
classes::CoC/eventTesterGo at H:\GitHub\Corruption-of-Champions-Mod\includes\debug.as:339
Function/<anonymous> at H:\GitHub\Corruption-of-Champions-Mod\includes\engineCore.as:303
coc.view::CoCButton/click at H:\GitHub\Corruption-of-Champions-Mod\classes\coc\view\CoCButton.as:95
```

**Comment by JustPassingThrough99** [comment]
As Stadler76 said, it is a built-in, in-game function that I found in the latest release build.

If I leave everything to the default code (that is, with the buttons triggering some Kitsune scenes), everything works as intended. If I change the code to redirect to other scenes like the one I mentioned in the OT, then I get a blank screen when pressing the button to access the scene. I'm assuming then that I am calling the scenes in a wrong way, but I'm not sure how. If anyone could give me an example on how to do that, it would be great!

**Comment by brrritssocold** [comment]
Hrm. Had a look at the parser code. Oh dear.

While I can get the parser to not crash, it won't display the `"Paste test event text here."` either.

**Comment by JustPassingThrough99** [comment]
Any update on this?
I'm not a coding expert by any means, so this Test Input function in the release builds would allow me to actually help out with the debugging of scenes. It seems strange that only the default examples seem to work and any other scenes will just output blank.

Once again anyway, thank you for all of you who answered and are helping!
