### ISSUE TITLE
[WIP] Refactoring old style Creature-props to use the BodyPart-props

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1010]
I'm currently working on the next big refactor related to `BodyParts`. This time I'm ditching the old style bodypart-props, like `hairType`, `hairColor`, `legCount` and so on in favor of using the BodyPart-props.
This is to support more intuitive code completion, when working with IDEs, like FlashDevelop and to clean up `Creature.as` some more and ditch all those aliased to support BC. SaveFile-structure will be unaffected. At least for now.

Current state: https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/master...Stadler76:refactoring-Creature-propertys

**Comment by Stadler76** [comment]
Ok, finally:
```as3
		public var antennae:Antennae = new Antennae();
		public var arms:Arms = new Arms();
		public var beard:Beard = new Beard();
		public var butt:Butt = new Butt();
		public var claws:Claws = new Claws();
		public var ears:Ears = new Ears();
		public var eyes:Eyes = new Eyes();
		public var face:Face = new Face();
		public var gills:Gills = new Gills();
		public var hair:Hair = new Hair();
		public var hips:Hips = new Hips();
		public var horns:Horns = new Horns();
		public var lowerBody:LowerBody = new LowerBody();
		public var neck:Neck = new Neck();
		public var rearBody:RearBody = new RearBody();
		public var skin:Skin = new Skin();
		public var tail:Tail = new Tail();
		public var tongue:Tongue = new Tongue();
		public var underBody:UnderBody = new UnderBody();
		public var wings:Wings = new Wings();

		public var wingDesc:String = "non-existant";
```

@aimozg, @Kitteh6660, @brrritssocold: Would be nice, if one or the other could take a look at the changes and check if I made any mistake or if you have any comments, suggestions or objections.

**Comment by Stadler76** [comment]
Did some more fine-tunings. The last one being adding a new `lists`-package for lists, like the `BodyPartLists`. Currently for the lists `canFlyWings`, `longTails`, `longTails` and `muzzles`

**Comment by Stadler76** [comment]
Did some more fine-tunings. The last one being adding a new `lists`-package for lists, like the `BodyPartLists`. Currently for the lists `canFlyWings`, `longTails`, `longTongues` and `muzzles` so they don't bloat `Creature.as` and `Character.as` anymore.

mmh, now that I think of it: Maybe `BreastCup.as` and `Gender.as` could be moved there, too?

**Comment by Stadler76** [comment]
> mmh, now that I think of it: Maybe `BreastCup.as` and `Gender.as` could be moved there, too?

Ok, BTDT :-)

**Comment by brrritssocold** [comment]
Since this has been merged, can you close the issue?

**Comment by Stadler76** [comment]
Sure

**Comment by brrritssocold** [comment]
Thanks!
