### ISSUE TITLE
Piercings

### ISSUE THREAD

**Issue by Everelda** [Kitteh6660/Corruption-of-Champions-Mod#1041]
### Overview
	the piercing lady is messed up
### Game version
	1.4.11
	
### Expected behaviour
	expected to have clean proper lists for the piercing merchant no extra buttons from other merchants
	
### Actual behaviour
	the piercing merchant isnt loading right when you pick her. she remembers buttons that she shouldnt from the main shops list. and when you select rare materials she shows the first 4 rare materials but the rest of the list is full of the non rare materials not allowing you to buy the 5th rare material as a piercing.	
### Steps to reproduce the issue

go to the piercing lady and mess with her lists

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

**Comment by Kitteh6660** [comment]
This should be fixed in next release.
