### ISSUE TITLE
Kelt won't react when he forces the player to strip.

### ISSUE THREAD

**Issue by The2ndImpact** [Kitteh6660/Corruption-of-Champions-Mod#1042]
### Overview
	Kelt doesn't comment on the player's body anymore, which kinda sucks because it was one of my favorite interactions in the game.
	
### Game version
	CoC_1.0.2_mod_1.4.11.swf
	
### Expected behaviour
	When the player reluctantly strips for Kelt, he usually comments on the player's breasts and butt.

### Actual behaviour
	The player interacts with Kelt is as if they didn't strip at all.

### Steps to reproduce the issue
	1. Find the farm and start training your archery with Kelt.
	2. When Kelt asks you to strip to continue training, do so reluctantly.

### File
	[I miss Kelt.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1519748/I.miss.Kelt.zip)

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [x] Working on patch for issue
- [ ] Submit pull request
