### ISSUE TITLE
Piercing shop doesn't hide other buttons

### ISSUE THREAD

**Issue by bonezinger** [Kitteh6660/Corruption-of-Champions-Mod#1044]
### Overview
	When visiting the Piercing shop in Tel'Adre, old buttons don't hide: Tailor (after talking About Her at least once), Weapons, Jewelry, Clinic and Carpenter are still visible.
	
### Game version
	e.g.: 1.0.2_mod_1.4.11
	
### Expected behaviour
	Hide the buttons of the other shops once you visit the Piercing studio.
	
### Actual behaviour
	The first 2-3 buttons get replace, the other buttons remain, as if partially in the Shop selection screen.

### Steps to reproduce the issue

1. Go to Tel'Adre
2. Click Shops
3. Click Piercing

**Comment by Kitteh6660** [comment]
Looked into the code. Should be fixed with the next release.
