### ISSUE TITLE
No text on Jewelry shop when clicking Jewelry box

### ISSUE THREAD

**Issue by bonezinger** [Kitteh6660/Corruption-of-Champions-Mod#1045]
### Overview
	No text on Jewelry shop when clicking Jewelry box
	
### Game version
	e.g.: 1.0.2_mod_1.4.11
	
### Expected behaviour
	Show some text
	
### Actual behaviour
	The text box becomes completely empty

### Steps to reproduce the issue

1. Go to Tel'Adre
2. Click Shops
3. Click Jewelry
4. Click Jewelry Box

Possible cause: classes/Scenes/Places/TelAdre/JewelryShop.as, line 54, the button makes a call for `curry(confirmBuy, null, 500, Inventory.STORAGE_JEWELRY_BOX)`
I suspect calling `(confirmBuy, null, 500, Inventory.STORAGE_JEWELRY_BOX)` or `confirmBuy(null, 500, Inventory.STORAGE_JEWELRY_BOX)` should work.

**Comment by Kitteh6660** [comment]
Let me know if this still happens when I release 1.4.12.
