### ISSUE TITLE
How on earth do i fix this

### ISSUE THREAD

**Issue by capitanbrian** [Kitteh6660/Corruption-of-Champions-Mod#1060]
### Overview
	game wont actually play
	
### Game version
	1.0.2_mod_1.4.11
	
### Expected behaviour
	Game runs without issue
	
### Actual behaviour
	The game re-downloads itself instead of running

### Steps to reproduce the issue

1. attempt to run game

**Comment by capitanbrian** [comment]
I can tell you now that last guy wasn't the only one to have that problem

**Comment by capitanbrian** [comment]
At least give a link to a decent flash player

**Comment by Omega1084** [comment]
That's a chrome problem, seen here:
https://bugs.chromium.org/p/chromium/issues/detail?id=767342
Google's trying to phase out Flash before it gets killed off in 3 years(yes 3. Lol.)
Basically just get the Adobe Desktop Player and you'll be able to run the game just fine:
https://labs.adobe.com/downloads/flashplayer.html
You'll need to find your saves wherever Chrome's keeping them and replace them in the Adobe local folder.
Take them out of C:\Users\Username\AppData\Local\Google\Chrome\User Data\Default\Pepper Data\Shockwave Flash\WritableRoot\#SharedObjects\CSF2UPSM\#localWithNet
And put them in C:\Users\Username\AppData\Roaming\Macromedia\Flash Player\#SharedObjects\RE7AU8GK\localhost
Should be working just fine then.
Alternatively use CoCEd to take the Chrome save and save it as a local one, haven't tried that.

**Comment by capitanbrian** [comment]
Thank you kitteh, your response was very helpful

**Comment by Kitteh6660** [comment]
Standalone Flash player will do.

I just use Firefox. It never fails me.

**Comment by kiop9099** [comment]
In the event you'd still like to use Chrome (or its derivative browsers), there is a workaround.

Open up a text file, copy+paste:

> <object type="application/x-shockwave-flash" data="_filename_.swf" width="100%" height="100%"></object> <

or in the case of the current version:

<object type="application/x-shockwave-flash" data="CoC_1.0.2_mod_1.4.12b.swf" width="100%" height="100%"></object>

Save it as an html file. Make sure the swf and html file are in the same folder location. This should open in any browser that supports flash, even if they automatically default to downloading the file itself.

Google has clear intentions to phase out Flash. There is no way to cleanly transition from Flash as a whole though.
