### ISSUE TITLE
feeder perk and dungeon notification

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#107]
With the latest patch and low corruption, the option to breastfeed the corrupt imp is now gone altogether, not just the scene where you forcibly trans him. I'm not sure if this is by design or a bug.
Also, a notification appears hourly: "Something inside your mind tells you that you should return to the prison. Mistress Elly would probably get angry if you wander the realms and abandon her. You leave a note in the camp to let anyone know that you’re making your departure." My character has full obedience if that's significant. Is this event not meant to prompt a return to prison? If not, making it less frequent might be a good idea. For one, the notifications pile up on sleep or rest.

**Comment by openaz** [comment]
Feeder perk works only with corruption 66+, unless you have corruption tolerance acension perk, which lowers corruption required. So this is probably intended.

**Comment by openaz** [comment]
And regarding second point, this prompt means, that you had quest and time for it is gone. It has up to 25% probability of occuring and should lead to capturing player. It has been implemented in the last release. After this message, you should be taken to prison, which probably doesn't occur.

**Comment by archmancer8** [comment]
With all other monsters, the feeder perk works regardless of corruption level (w/ corrupt imp, 66+ corruption resulting in forced trans scene). Just so long as your corruption does not drop below 20, the perk is retained, implying that 20 is the minimum requirement to feed opponents. The perk description is listed as "Lactation does not decrease and gives a compulsion to breastfeed others." This indicates that as long as Feeder is active, 20 or more corruption, the PC should have a desire to feed. In original CoC, the Corrupted Imp is feedable as long as you win through lust; corruption is not an issue and there is no trans in that scene. I think that this original scene should be reinstated for PCs with 65- corruption.
And for the dungeon notification, I promise you, it appears for me every single hour without fail.

**Comment by openaz** [comment]
I'm sorry, I mentioned incorrect values. Taken from CoC wiki:
>Obtained from: Chance to obtain by drinking LaBova or ProBova while having heavily lactating breasts of DD size or larger and 35 or greater corruption. Lost by reducing corruption to 20 or below.

For imp, hardcoded value is 66 in order to breastfeed him, which might be intended by Kitteh (due to new imp scenes) and he'll know better whether to fix it or leave it. But just for case, he'll want to fix it (diff removes corruption requirement. Once player is below 20, perk is removed, so it's not necessary to check it again):
```diff
diff --git a/classes/classes/Scenes/Monsters/ImpScene.as b/classes/classes/Scenes/Monsters/ImpScene.as
index b4dbddd..5e3a538 100644
--- a/classes/classes/Scenes/Monsters/ImpScene.as
+++ b/classes/classes/Scenes/Monsters/ImpScene.as
@@ -1643,7 +1643,7 @@ package classes.Scenes.Monsters
 				if(player.hasCock() && player.cockThatFits(monster.analCapacity()) >= 0) addButton(0,"FuckHisAss",impLordBumPlug);
 				if(player.hasCock()) addButton(1,"Get Blown",getBlownByAnImpLord);
 				if(player.hasVagina()) addButton(2,"Ride Cock",femaleVagRape);
-				if(player.findPerk(PerkLib.Feeder) >= 0 && player.cor >= (66 - player.corruptionTolerance()) && monster.short != "imp overlord" && monster.short != "imp warlord") addButton(3,"Breastfeed",feederBreastfeedRape);
+				if(player.findPerk(PerkLib.Feeder) >= 0 && monster.short != "imp overlord" && monster.short != "imp warlord") addButton(3,"Breastfeed",feederBreastfeedRape);
 				if (player.hasVagina() && player.biggestTitSize() >= 4 && player.armor is LustyMaidensArmor) addButton(4, "B.Titfuck", (player.armor as LustyMaidensArmor).lustyMaidenPaizuri);
 			}
 			addButton(14,"Leave",cleanupAfterCombat);
```

And for prison, I didn't said that I don't believe you. You might be pretty unlucky so the message is generated for you every hour. Or it may be broken. When the message appears, is there button next? And if so, are you moved to prison after clicking on it? I don't have currently character with fully obedient prisoner and I might get different result.

**Comment by archmancer8** [comment]
Sorry, didn't mean to imply that I didn't think you believed me. But yes, the notification appears every hour; there's a next button and I'm able to go about my day ordinarily afterword, albeit with a slight lust gain.

**Comment by archmancer8** [comment]
And no, I never actually go back to prison.
