### ISSUE TITLE
[Request] Separate place for suggestions

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#111]
As for now, there are 3 places for talk about this mod: forum thread, trello and here. Neither is really good for suggestions — forum thread is too long and anything here have good chance to be forgotten, trello is restricted for only comments about existing ideas and github is meant for issues (since we can't use labels system to avoid clutter).

So it can be either trello list with notes for every suggestion type to be added as comments, or github with official tagging guideline, or some other place.

**Comment by Kitteh6660** [comment]
I've added a new place for suggestion here: https://trello.com/c/7xylV2UR/138-suggestions
