### ISSUE TITLE
Not enough space for gameplay setting's description text

### ISSUE THREAD

**Issue by manhvu0803** [Kitteh6660/Corruption-of-Champions-Mod#1111]
### Issue type
Bug report (not really a bug)

### Overview
	Not enough space for gameplay setting's description text
	
### Game version
	1.0.2_mod_1.4.12
	
### Expected behaviour
	There should be more space for the description text
	
### Actual behaviour
	When changing the gameplay setting, some description text like the Hyper Happy or Prison go over other text

### Steps to reproduce the issue

1. Open the game
2. Click Option, click Hyper Happy On

**Comment by Kitteh6660** [comment]
Should be resolved now that the description box is wider.
