### ISSUE TITLE
Bug Report Phouka

### ISSUE THREAD

**Issue by Munkus11** [Kitteh6660/Corruption-of-Champions-Mod#1116]
### Issue type
- [x ] Bug report
- [ ] Feature request
- [ ] Other

### Before reporting a bug, please check the following:
- [x ] Check that the bug is still present in the latest release
- [ ] Search existing issues first(please do not open duplicate issues!)
- [ ] Fill out the template - it's there for a reason

### Overview
	
The bug happens when ANY kind of sexual encounter with the phouka takes place. No matter if they are winning, loosing or after talking with it. 
It SKIPS the discription of the actual sex scene and immediately jumps to the conclusion. No matter the player (tested on flashplayer, chrome and firefox) or the body of the pc. 

The sex scene is triggered and it jumps to the aftermath where you see if you are pregnant by it or not. 
	
### Game version
CoC_1.0.2_mod_1.4.12b
	
### Expected behaviour
	Sex scene should be triggered, description of the actual sex happening, conclusion
	
### Actual behaviour
	sex triggered, jumps to conclusion

### How often can this be reproduced?
	always

### Steps to reproduce the issue

Tried different saves, tried loading earlier saves, tried new saves, tried independant flash player, chrome and firefox. 
occurs 10 out of 10 times.

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [x] Working on patch for issue
- [ ] Submit pull request
