### ISSUE TITLE
Centaur pole masturbation not working

### ISSUE THREAD

**Issue by Munkus11** [Kitteh6660/Corruption-of-Champions-Mod#1117]
### Issue type
- [x ] Bug report
- [ ] Feature request
- [ ] Other

### Before reporting a bug, please check the following:
- [x ] Check that the bug is still present in the latest release

### Overview
	Tauric masturbation not possible - even with fake mare + pole
	
### Game version
	CoC_1.0.2_mod_1.4.12b
	
### Expected behaviour
	with fake mare + centaur pole masturbation should be possible
	
### Actual behaviour
	Game reports:
"No matter how you twist and turn, you can’t reach anywhere close to your genitalia! It seems that being a centaur has a rather crippling downside – you can’t reach around to get yourself off and sate your lusts!

It looks like you’ll have to find a partner to relieve your pent up need, but in your current state you’ll probably be on the receiving end of whatever you can get!"

even though centaur pole and fake mare are listed in key items

### How often can this be reproduced?
	always

### Steps to reproduce the issue
tried different players + different player characters on different machines

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [ ] Trying to reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request

**Comment by brrritssocold** [comment]
Cannot reproduce.

Items for Mastrubation show up in `Mastrubate` -> `Items` menu.
This is more of a UI issue, the `Items` button is easy to miss.

**Comment by Munkus11** [comment]
You are right. My apologies. 
I totally overlooked the items button.
