### ISSUE TITLE
Grammatical error in exgartuan.as

### ISSUE THREAD

**Issue by kiop9099** [Kitteh6660/Corruption-of-Champions-Mod#1120]
### exgartuan.as
outputText("Suddenly your " + chestDesc() + " feel as if they trying to force their way off your chest.  The strange motions are accompanied by some loud moaning, as if they are stretching awake.  Looks like the delightful peace and quiet has ended.", false);

chestDesc() outputs plural so "they trying" should be "they're trying"... something like that.
	
https://github.com/Fenoxo/Source/blob/master/exgartuan.as

line 326

**Comment by Stadler76** [comment]
You're referring to the wrong repo.
Correct would be:
https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/NPCs/Exgartuan.as#L457
But still the same error ^^

**Comment by Kitteh6660** [comment]
Looked and there's no grammatical error in this repository. The original still has the error however.

Issue closed.
