### ISSUE TITLE
the boulder from the ice giant won't leave me alone [was: Problem]

### ISSUE THREAD

**Issue by SylicaTelca** [Kitteh6660/Corruption-of-Champions-Mod#1129]
### Issue type
- [x] Bug report
- [ ] Feature request
- [ ] Other

### Before reporting a bug, please check the following:
- [x] Check that the bug is still present in the latest release
- [x] Search existing issues first(please do not open duplicate issues!)
- [ ] Fill out the template - it's there for a reason

### Overview
	e.g.: When using a large number of y item, the game crashes.
	
### Game version
	e.g.: 1.0.2_mod_1.4
	
### Expected behaviour
	e.g.: Can use as many y item as I want.
	
### Actual behaviour
	e.g.: The game crashes after using around z number of item y.

### How often can this be reproduced?
	e.g.: always, 4 out of 10 times, ect.

### Steps to reproduce the issue

1. e.g.: Switch to debug mode
2. e.g.: Try to eat n number of item y
3.

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed).

**Comment by Stadler76** [comment]
Not tested, but it should be fixed by applying: [20180118_0153_giantBoulder-fix.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1641322/20180118_0153_giantBoulder-fix.zip)

**Comment by SylicaTelca** [comment]
How do I use it on mobile

**Comment by Stadler76** [comment]
@SylicaTelca wrote:
> How do I use it on mobile

You can't just apply a patch to the binary you're running on your mobile. you have to download the source, apply the patch to it and then compile it to a version that you can run on your mobile. Or just wait, till a version with that bug fixed is released.

About the issue:
It occurs, when you battle the frost giant and he throws a boulder at you.
If you then leave the battle before the boulder hits or misses you the status effect `StatusEffects.GiantBoulder` will stay until you battle the frost giant again.
As a workaround you have to battle him again and make sure the battle ends before he throws the next one at you.
