### ISSUE TITLE
Ascension and perks

### ISSUE THREAD

**Issue by openaz** [Kitteh6660/Corruption-of-Champions-Mod#115]
After ascension, following perks are removed. Some of them seems to be illogical, e.g. Controlled Breath as other two Jojo's training perks are retained. No fix provided as this is more likely question and what to fix depends on what's @Kitteh6660 plan.
Androgyny - gained from Joey's in Bazaar
Basilisk Womb - gained with Oviposition from Benoit
Brood Mother - gained after giving birth 10 times
Controlled Breath - gained from Jojo's training
Dragonfire - gained from drinking Ember's blood
Magical Fertility - gained from Sand Cave dungeon
Marble Resistant - gained after removing addiction on Marble's milk
Misdirection - gained from Raphael's training
Oviposition - gained with Basilisk Womb from Benoit
Purity Blessing - gained after eating Pure Pearl
Thick Skin - gained from consuming Numb Rox
Transformation Resistance - gained after transformed 100 times

**Comment by openaz** [comment]
As it seems to be intended to keep only levelup perks with few exceptions, here's list of what probably shouldn't be transferred.
Cleansing Palm
Enlightened

Also, piercings are transferred too, including their perks ofc. Probably intended, as it can be considered as equipment.

**Comment by Netys** [comment]
Dragonfire should be transferred if at least 3 dragon traits retain (btw, IMO tongue should stay).

If training perks are intended to stay, Controlled Breath, Misdirection and rapier training should be kept too.

Other are more body features, and can be transferred or removed like other unusual bodyparts.

**Comment by openaz** [comment]
Ascension has been done after consuming tons of Hummus, so character was pure human with no mutations at all. For me, most logical seems to be remove all perks except level ups, perks from transferred mutations and from equipment. So the character can go through the full game again. But e.g. Transformation resistance doesn't have big effect on play experience, nor Brood Mother. So it highly depends on how the ascension should work.

**Comment by Netys** [comment]
Transformation resistance makes it harder to get TF. Even without it some TFs takes weeks of griding to get.

History perks IMO should stay too.

**Comment by Kitteh6660** [comment]
I'm pondering over having multiple history perk. Ideally, it would take at least 9 NG+ cycles to get all the history perks. You'll be able to skip taking any of them in NG+. (Same history perk can't be taken multiple times)

**Comment by Netys** [comment]
Also, I personally like pre-defined characters, thay gives unique taste to playtrough. It's a shame they lose their personality at ascension.

BTW, maybe make special names official game mode with name selection?

**Comment by openaz** [comment]
So, good news first. Cleansing Palm and Enlightened are gone after ascension (in new release). Bad news, you have to select Corruption tolerance as ascension perk. Without it, situation remains unchanged, because long description is different from short one due to 15 corruption player gains on new game. So the condition in isAscension() has to be changed or proper implementation of "flag" has to be done.

**Comment by Netys** [comment]
To make mess less messy - ascension behavior can be defined inside of perk itself.

P.S.: Git blows my mind. Is there really no other way to create a fancy pull request for selected branches, like this:

https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/0921a45a91b8a6a684d84ae9c81c5c370e851b85...Netys:e80463c9300a893b388f3ea00d8fd287196dfaa8

instead of bland diff files like this

https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/0921a45a91b8a6a684d84ae9c81c5c370e851b85...Netys:e80463c9300a893b388f3ea00d8fd287196dfaa8.diff

(and i can only hope that this diff would stay as it is now after more commits)

**Comment by openaz** [comment]
Hey, get out of my head, now! :smiley: Something very similar I wanted to start yesterday (actually started, but got lost in PerkLib when adding new params). And you know what? You forgot to include levelup perks (the dirty condition will once again cause issues with Perks from Jojo training, it should be completely removed) ;)

**Comment by Netys** [comment]
>Hey, get out of my head, now!

:neutral_face:

>You forgot to include levelup perks

I had no intention to actually change what code does, only how it does it.

>And for diff, did you tried git diff branch1 branch2 ? It should work also for remote branches. (But it's possible that I didn't understood your question)

See second link. It would give same diff file. And I wanted to have pull request. Ahh, forget it. Whatever works.

**Comment by openaz** [comment]
To get pull request, you must make a fork of kitteh master, then commit into this fork and once you are done, github will allow you to create a pull request, which will consist of your unique commits ;)

**Comment by Netys** [comment]
Yes, I know. But it looks like it only allows to request pull of difference between Kitteh's master and my target revision, not target...target range.
```
Kitteh: head ↓
Me    :      → A - B - C - D - head
```
How can I create pull request for B and C only?

**Comment by openaz** [comment]
One branch per request, I had same problem with it. In the past, forking was used which did exactly what you want using cherry pick...but it has been replaced by pull request.

**Comment by Killette2** [comment]
I'm a bit late to the party, but I feel annoyed on how much is lost after ascension.

You lose multiple perks, some of which are difficult to get so you must grind them again
You lose your cabin, which can take a lot of effort to build, especially if you decide to decorate it with impskulls, however you keep your chest and storage items which I find bizarre
You also lose your multiple genitals, which affects cock rings and sizes, also cum production

It just feels like I lose so much progress during ascension to the point where I'd rather not ascend at all because I have to grind it all back over again every time.

**Comment by Kitteh6660** [comment]
These changes might happen with ascension rework.

**Comment by Killette2** [comment]
Will this involve keeping the transformation? I can see keeping the perk requirements if it's a perk that fades understandable, but if it's not obvious some people also play CoC just to minmax (sorry roguelikes did this to me). That said, RIP my spiked gauntlet and might+charged weapon build, with the iron fist nerfs and the spell caps for those two.

**Comment by Kitteh6660** [comment]
In 1.3.22, you'll be able to make some perks permanent. Not every perk listed on the first post is permable.
