### ISSUE TITLE
Permanent stat decrease after bee venom and minor suggestion (1.0.2_mod_1.4.12b)

### ISSUE THREAD

**Issue by KKITAANIK** [Kitteh6660/Corruption-of-Champions-Mod#1150]
Hello. There are three things I would like to simply explain to see if it is a problem on my end or with the mod. I have gone through many google searches as well as every issue here and as far as I can tell no one has posted about these before.

1) Stats are permanently decreased after the bee girl fight. After fighting her I usually am injected with her paralytic venom, after the fight I see the line explaining that I feel stronger and faster as the venom wears off, however the stats don't show any increase. I have tried saving and loading, seeing if it increases after rest or sleep, and various other things, however they seem to be permanently decreased, which is very troublesome as this is at the beginning of a run.

3) Ovipositor scenes are species exclusive. While this isn't a bug, it bothers me that ovipositor scenes require either drider _or_ bee ovipositors. For example, the scene with an imp only works with a bee, and the scene with a goblin only works as a drider. While I understand that this may be because these scenes involve webbing or honey or the like, it is annoying that to make a character that deposits eggs I'd simply have to choose. Well I don't really have much grounds to recommend the game be changed or scenes altered, that is something that would make playing such a character much less limiting.

Thank you for reading through what you did and hopefully replying, any help possible is very much appreciated.

Edit: Sprites were disabled in settings, issue removed. Sorry. Other two problems still exist.

**Comment by Based-Dog** [comment]
I've having the same bug with the permanent stat decrease from the bee girl as well. Kinda annoying.

**Comment by Kitteh6660** [comment]
Should not be an issue anymore as of current version. Probably.
