### ISSUE TITLE
[Bug report] Priscilla encounter - No male options for futa when choosing sex option

### ISSUE THREAD

**Issue by Fusion-tech** [Kitteh6660/Corruption-of-Champions-Mod#1205]
### Issue type
- [X] Bug report

### Overview
	Only female-focused scene buttons display when choosing sex with Priscilla as a futa. No male-based scene options display. Also, all scene variants display during foreplay scene.
	
### Game version
	1.0.2_mod_1.4.12b
	
### Expected behaviour
	Options to choose either female or male-based scenes when playing as futa.

### Actual behaviour
	 All scenes variants (male/female/futa) display and then provides only vagina options for futa

### How often can this be reproduced?
	Every time Priscilla is encountered.

### Steps to reproduce the issue
	Encounter Priscilla as random encounter
	Talk to her and choose sex option as futa

I'm including screenshots of scene as played in-game, and scene code highlighted from PriscillaScene.as file. Hope this helps.

![bug_screen01](https://user-images.githubusercontent.com/16268845/36062931-e94a6a3c-0e32-11e8-9139-44ec51c69f15.JPG)
![bug_screen02](https://user-images.githubusercontent.com/16268845/36062932-eb6478d0-0e32-11e8-819a-b6801adb669e.JPG)
![bug_screen03](https://user-images.githubusercontent.com/16268845/36062933-ed5d7466-0e32-11e8-83ce-978d9a0dceeb.JPG)
![bug_screen04](https://user-images.githubusercontent.com/16268845/36062934-efb55a26-0e32-11e8-86cc-12d5eedfcabe.JPG)

**Comment by Kitteh6660** [comment]
This could probably easily be resolved with if-else statement.

**Comment by Fusion-tech** [comment]
I modified the PriscillaScene.as file in Notepad++ to include the male option buttons in addition to the female ones for futa player characters. Not sure if it will help but I'm attaching the changed file here.

Thank you for all you do with this game!

[PriscillaScene.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/2472933/PriscillaScene.zip)

**Comment by Kitteh6660** [comment]
Should be fixed in 1.4.18 now.
