### ISSUE TITLE
Travis is on a failfest again ...

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1211]
```
Player version mismatch! Flex SDK min version: 27.0, script player version: 28.0
Update the PLAYER_VERSION_* variables in devTools/ci/setup-flex.sh to match 27.0
```
I've tried to fix this in PR #1210 but that didn't work ...
Looks, like Adobe changed something on their servers but Apache Flex wasn't updated yet.

Any ideas on how to fix that? I'm out of those ...

**Comment by brrritssocold** [comment]
Working on a quick fix to get builds working again.

**Comment by Stadler76** [comment]
mmh, seems that this time SF.net is the one to blame ...

http://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw&ts=201802141624 currently gives me a '503 - Service Unavailable' error.

SF-Status here: https://twitter.com/sfnet_ops

**Comment by brrritssocold** [comment]
FYI: Sourceforge is under DDOS: https://twitter.com/sfnet_ops/status/967809090545180672

**Comment by brrritssocold** [comment]
And gone again...

**Comment by Stadler76** [comment]
SF.net now has an outage for roughly 48 hours. *sighs* I hope, it becomes reliable again soon. Too many outages since they started moving their servers ...
