### ISSUE TITLE
[Refactoring] Evasion overhaul

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#124]
Now it checks every perk separately, so any change require massive work over all code.

Now it looks like

     if (combatMiss() || combatEvade() || combatFlexibility() || combatMisdirect())

and with approved perks there would be 2 more checks. Also, there are many non-combat cases, where only one of that perks is checked, when it would be reasonable to have them all be checked. My code have following functions:

     // returns summary chance to evade
     getEvasionChance():Number
     // rolls evasion chance and returns what caused success if successfull, or null if failed, good for different messages for different ways to evade, don't forget to use failsafe return != null whan using it to support future perks
     // can check both combat and non-combat evasion
     // can use attack speed number in non-combat cases
     getEvasionReason(useMonster:Boolean = true, attackSpeed:int = int.MIN_VALUE):String
     // wrapper for getEvasionReason which only returns boolean
     getEvasionRoll(useMonster:Boolean = true, attackSpeed:int = int.MIN_VALUE):Boolean

Technically, this allows monsters to use evasion perks, if function called from monster with (false, player.spe) arguments.

Fancy diff: https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/e80463c9300a893b388f3ea00d8fd287196dfaa8...Netys:f459b95

File diff: https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/e80463c9300a893b388f3ea00d8fd287196dfaa8...Netys:f459b95.diff

P.S.: Still not sure, which is better - pull requests or diffs.

**Comment by Kitteh6660** [comment]
Now that's something I can do.

Although keep in mind that the Unhindered perk will be tweaked so you can still wear undergarments.

**Comment by Kitteh6660** [comment]
If you like, you can go ahead and make a pull request.

**Comment by Netys** [comment]
Isn't diff file good enough? I'm not sure it is still consistent for current version of mod, and, sadly, have lost all flash dev tools and have not enough time (yep, that's why I've disappeared - have work to do) to find them again, especially since it took me lots of time to find ends and tails in how they work (why dev tools never really work without some tinkering?) and I don't really remember it's all now.

**Comment by Netys** [comment]
Done. Got #122 as well...
