### ISSUE TITLE
Me, the critic

### ISSUE THREAD

**Issue by Munkus11** [Kitteh6660/Corruption-of-Champions-Mod#1245]
Not really anything, no issues, sorry. 

Just me wanting to thank you guys for doing this, for working through a positive f*ton of code which seems completely alien to me and making something out of it that is both entertaining to read and fun to play. 
It is very interesting to see it grow and see the changes. Which look very complicated. (No programmer here). 

So thanks a lot guys for the job you are doing. Peace.

**Comment by AnonymousIncognito5** [comment]
Could someone close this? It isn't actually an issue.
