### ISSUE TITLE
[Enhancement] Just food

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#125]
Just 2 simple food items in Tel'Adre bakery, which are food and nothing more.

Hard Biscuits - 5 gems, 20 hunger. Trail Mix - 20 gems, 50 hunger and small fatigue/hp restotation.

Possible improvements:
 - add this items to Ingram
 - add Ingram's tavern food to Tel Adre (Wet Bitch or new inn)
 - add option to buy food to farm
 - add new learnable ability to cook food propertly, you already can talk with baker about this, why can't learn something?

https://github.com/Netys/Corruption-of-Champions-Mod/commit/c3faa10d00fe3374de0e3048628d08a691c46f5c

Diff: https://github.com/Netys/Corruption-of-Champions-Mod/commit/c3faa10d00fe3374de0e3048628d08a691c46f5c.diff

**Comment by Kitteh6660** [comment]
The ability to buy the biscuits and trail mix are going to be in the next snapshot.
I'm beginning to think the farm can offer a regular hummus as human TF item but at high prices. (Human TFs are not meant to be easy to get)
