### ISSUE TITLE
[Regression] No more 'lay Benoit(e) eggs' event at night since recent update

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1269]
### I have checked the following before submitting this issue:
- [ ] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
The event, where you lay Benoit(e)'s eggs at night doesn't happen anymore. In addition the egg pregnancy updates don't show up anymore. It just happens silently. Plus: The amount of eggs laid is doubled.
	
### Game version
Probably caused by PR #1263 
	
### Expected behaviour
- Egg pregnancy updates (In bold)
- Incubation event at night
- Lay `fertility / 10` eggs rounded down.
	
### Actual behaviour
- No updates
- No event
- Double the amount (Simply watch the stats=

### How often can this be reproduced?
Always

### Steps to reproduce the issue

1. Obtain the Basilisk Womb Perk
2. Get pregged with it by male or herm Benoit
3. Wait a few days

**Comment by brrritssocold** [comment]
Argh.

**Comment by Stadler76** [comment]
Ok, after some debugging I've found out, that PlayerBenoitPregnancy happens immediatly:
```
knockUp(type, incubationDuration): 18, 250
knockUpForce(type, incubationDuration): 18, 250
knockUpForce(type, incubationDuration): 18, 250
3/13/2018 20:45:14.250 [DEBUG] classes.Scenes.PregnancyProgression Updating pregnancy for mother 25, father 18 by using class [object PlayerBenoitPregnancy]
knockUpForce(type, incubationDuration): 0, 0
knockUpForce(type, incubationDuration): 0, 0
```
