### ISSUE TITLE
arian's twin penises and corrupt imp breastfeeding

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#127]
Feeding Arian reptilium in vanilla COC causes him to grow a second, identical penis, replacing his initial "get fucked" scene, in which a female or herm character is vaginally penetrated, with a scene in which the lizan penetrates the PC both vaginally and anally. In mod 1.2.15, a player may feed him reptilium, causing the growth of a second phallus. However, his "get fucked" scene remains the same. He is described as having only a single penis and only penetrates the PC's vagina.
Also, the feeding scene for the corrupt imp still TF's him into a cuntboy at low corruption.

**Comment by archmancer8** [comment]
Completely disregard the first point, I am an idiot, I got my saves mixed up and managed to fully convince myself that I'd already given him reptilium in the save in point; not so, in fact. Everything with Arian is fine -.-

**Comment by Netys** [comment]
> Also, the feeding scene for the corrupt imp still TF's him into a cuntboy at low corruption.

http://forum.fenoxo.com/thread-10915-post-302628.html#pid302628

According to the Source Code the requirements for that scene are:

    Imp must be an Imp Lord. Imp Warlords and Overlords don't work.
    You must have the Feeder Perk.
    You must meet one of the following:
        Height less than 48 Inches (4 Feet).
        Height greater than 60 Inches (5 Feet).
        Have a Centaur lower body.
    Additionally:
        If you have one Breast Row, you must lactate more than 2 Liters.
        If you have two Breast Rows, you cannot get this scene.
        If you have more than two Breast Rows, you need 80 or higher corruption.

**Comment by archmancer8** [comment]
Right. My character is 60 inches tall, has feeder, 1 breast row, lactates a lot. But Kitteh in the last version stated that 66 corruption should now be required for the cuntboy scene.

**Comment by Kitteh6660** [comment]
This will be resolved in 1.3.16 with some changes. At least 80 corruption will be required for the imp to turns into cuntboy. Below that and your milk isn't potent enough.
