### ISSUE TITLE
[Regression] Times given birth seems to be only updated with Benoit(e) pregnancy now

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1271]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
giveBirth has been moved to PlayerBenoitPregnancy and is only called when giving birth to bassys after being pregged by Benoit AFAICS.
	
### Game version
1.4.13b
	
### Expected behaviour
giveBirth should always be called, when the player gives birth to 'something'.
	
### Actual behaviour
Its only being called in PlayerBenoitPregnancy.as

### How often can this be reproduced?
Always

### Steps to reproduce the issue

1. Player gives birth to anything, but basilisks

@brrritssocold: Could you look into this soonish?

**Comment by Stadler76** [comment]
Heres, what was removed without proper replacement:
```as3
if (player.pregnancyIncubation === 1 && player.pregnancyType !== PregnancyStore.PREGNANCY_BENOIT) giveBirth();
```

As you can see it is always being called. But since Benoit pregnancy has mechanics that delay the event till 5 or 6am it is excluded at the top and called directly in Benoit pregnancy.
Simply go back in history. The original PregnancyProgression.as calls it in lines 44 and 1598

**Comment by brrritssocold** [comment]
Looking at it, rather embarrassing that i missed that.
