### ISSUE TITLE
[Bug] Oviposition with Large Bees in Forest not occurring

### ISSUE THREAD

**Issue by shadedmagus** [Kitteh6660/Corruption-of-Champions-Mod#1275]
### I have checked the following before submitting this issue:
- [X] The bug is present in the latest release
- [X] Searched the existing issues so I do not open a duplicate issue

### Overview
In the event with the normal large bees in the Forest, when you accept their eggs and honey, the impregnation is not occurring.
	
### Game version
1.4.13b
	
### Expected behaviour
The bolded text after the event should indicate that impregnation occurred, along with the timed events leading up to egg release.
	
### Actual behaviour
None of this happens.

### How often can this be reproduced?
In five straight encounters, this has not triggered once. It triggered (almost) every time in vanilla and in mod version 1.4.12b

### Steps to reproduce the issue

1. Initiate an encounter with a large bee in the Forest at low level.

**Comment by Stadler76** [comment]
Haven't tested with version 1.4.13b but at least with commit b3ada94 is seems to be fixed.
