### ISSUE TITLE
[Bug] Maximum length name overlaps with main text area

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#1277]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
The maximum allowed name length exceeds the stat windows width, causing it to overlap with the main text area.	
### Game version
CoC 1.0.2 - Mod v1.4.13b
	
### Expected behaviour
The maximum name length should either be limited so it does not overlap with the main text area, or some other solution to allow longer names.
	
### Actual behaviour
Name overlaps with the main text area.

### How often can this be reproduced?
Always.

### Steps to reproduce the issue

1. Create a new character with the name `1234567890123456`
2. Start the game proceed until some text is displayed in the main text area 

![image](https://user-images.githubusercontent.com/19509767/37557628-b3aeeaec-2a07-11e8-9769-4aa5a4bbaaf2.png)

**Comment by Kitteh6660** [comment]
Should be resolved as the UI was updated.
