### ISSUE TITLE
ascension bugs(?)

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#128]
Reincarnating seems to carry over the score for hips and butt, but not breasts. My PC kept 20's for hips and butt, but breasts reset to starting value. (Nipples also retained 'fuckable' tag)
Also, milk score carried over. However, all encounter-type perks are lost in ascension (cornucopia, milking twat, fire lord, etc.) This includes feeder, allowing for a rapid loss of lactation rating with no access to a milker. I don't know if any or all of this was by design or not.
Finally, when ascending, players are allowed to keep their items. However, upon being sent back to Mareth from Ingnam, their equipped weapon is confiscated, losing that weapon. Obviously, this can be avoided by unequipping that weapon, but it may be smoother to eliminate the weapon confiscation scene for NG+.

**Comment by Kitteh6660** [comment]
This will be resolved in 1.3.4.
