### ISSUE TITLE
[Enhancement] Gauntlet/Perk improvement!

### ISSUE THREAD

**Issue by orochi02** [Kitteh6660/Corruption-of-Champions-Mod#1280]
### I have checked the following before submitting this issue:
- [ ] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [ ] Filled out the template, so developers are less likely to ask for more info

### Overview
The issue is that in CoC gauntlets are pretty underrated since there are more straightforward weapons with more attack damage. 
	
### Game version
Every game version.
### Expected behaviour
So how about making the Iron Fists perk not only increase attack damage of fists but also gauntlets too? This way you can have more variation about how you pick your weapons instead of just simply taking either a strong sword or a strong staff. (Instead you can also try to change the code of the gauntlets into making it as similar as the fists).
	
### Actual behaviour
Gauntlets are generally seen as weak weapons.

### How often can this be reproduced?
Always

### Steps to reproduce the issue

1. Get gauntlets
2. Think they are too weak and get another weapon

**Comment by Kitteh6660** [comment]
I'll look into buffing the gauntlets!
