### ISSUE TITLE
1_0_2 CoC revamp glitch: Speed maxes and stuck at 60!

### ISSUE THREAD

**Issue by HubS99** [Kitteh6660/Corruption-of-Champions-Mod#1283]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [ ] The bug is still present in the latest release
- [ ] Searched the existing issues so I do not open a duplicate issue
- [ ] Filled out the template, so developers are less likely to ask for more info

### Overview
At some point past the halfway mark in my first playthrough so far, it seems like I somehow have my speed cap set down to 60 from 100. I had it usually in the 90s, but now it never goes above 60. The meter for the stat is all the way full, too. Did a glitch happen when facing a basilisk? Or maybe one of the spiders? (both of their slow down abilities)
	
### Game version
1.0.2_mod_1.4.12b (CoC w/ Revamp Mod)

### Expected behaviour
Your speed should be brought back to full stats after temporary speed reductions in certain events like mentioned with the basilisk and stuff.
	
### Actual behaviour
Now the speed stat is maxed only at 60. Nothing has changed it so far.

### How often can this be reproduced?
I have only seen it occur once, but I saved before I realized it had been stuck there. So now I'm at the end game with only 60 max speed.

[CoC_Samuel2.txt](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1850169/CoC_Samuel2.txt)

**Comment by orochi02** [comment]
are you sure you didnt just smoke the pipe at izumis place? or have hyper endowments and play on realistic?

**Comment by Stadler76** [comment]
Losing against a basilisk reduces your speed by 3 without the Basilisk Resistance perk and by 1 with Basilisk Resistance. See [line \#276 of BasiliskScene.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/efa922b746b6e2bb5a10b799b0c89da53ea40c72/classes/classes/Scenes/Areas/HighMountains/BasiliskScene.as#L276).

**Comment by HubS99** [comment]
There is realistic mode on. But I haven't seen an indication on stats or appearance that indicate something is effecting my speed stat ceiling. I'm currently having the character slowly reverse some changes to see what happens over time.

**Comment by Darth-Cthoras** [comment]
Make sure you don't have an acupuncture active - as I recall, the Attack one debuffs your max speed in exchange for more power, and the Speed one caps your Strength while halving Speed drains.

**Comment by Kitteh6660** [comment]
Speed cap of 60 indicates you have an acupuncture perk active.
