### ISSUE TITLE
[Bug] Lethicite Ring not doing anything.

### ISSUE THREAD

**Issue by Jmari0** [Kitteh6660/Corruption-of-Champions-Mod#1285]
### Item
Lethicite Ring

### Located
Tel'Adre
Shops
Jewelry 
Special Rings
Lethic.Ring

### Description 
A glowing lethicite ring

This ring appears to be made out of platinum with some lethicite crystal. Very expensive as lethicite is rare.

Type: Ring
Special: Slowly corrupts the wearer over time. 
Base value: 5000

### Issue
Effect described not taking place.

### Notes
Purity Ring works. 
Happens in latest version.
Happens %100 of times tested.

**Comment by Jmari0** [comment]
Happens on Android.

**Comment by orochi02** [comment]
sure you dont have any anti corruption stuff? for example divine bark armor?

**Comment by Stadler76** [comment]
@orochi02 wrote:
> sure you dont have any anti corruption stuff? for example divine bark armor?

Nope, I could easily repeat it. See my fix above your comment.

**Comment by orochi02** [comment]
@Stadler76 wrote:

> Nope, I could easily repeat it. See my fix above your comment.
yea sorry, when i posted my comment your fix wasnt shown to me yet
