### ISSUE TITLE
Minerva's Pregnancy has the following glitch:

### ISSUE THREAD

**Issue by Rycharde** [Kitteh6660/Corruption-of-Champions-Mod#130]
"[...] D-darling, so...so fuuuuck. It’s so good; your massive **!Unknown aspect in two-word tag “cock type”! ASCII Aspect = “type"** is so good, stretching me so much. Ooohhh.. My poor belly, [...]"

**Comment by Kitteh6660** [comment]
Should be fixed in 1.2.18.
