### ISSUE TITLE
[Bug] Upgraded ranged weapons behave like melee weapons

### ISSUE THREAD

**Issue by Mendelrock** [Kitteh6660/Corruption-of-Champions-Mod#1309]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
After upgrading a flintlock to masterwork quality, it ceased to act as a ranged weapon, featuring infinite number of shot (no reload necessary) and the inability to hit faraway opponents (easily seen agaisnt mimics)
	
### Game version
CoC 1.0.2_mod_1.4.13b, Standalone .swf version
	
### Expected behaviour
Upgrading a ranged weapon should only increase it's base damage (by 2 per improvement level, according to the wiki)
	
### Actual behaviour
Upgrading seems to increase the base damage, but also removes the special behavior of ranged weapons: damage is no longer Speed-based, reload is no longer necessary or even accessible (if applicable), and you can't attack faraway opponents. Only tested with the Crossbow and the Flintlock, the Blunderbuss not featuring those features to begin with.

### How often can this be reproduced?
100% of the time.

### Steps to reproduce the issue

1. Get a flintlock from Benoit at Bizarre Bazaar
2. Upgrade it once or twice at Tel'Adre's weaponsmith
3. Find a resilient enemy
4. Fire four times at it, then watch the attack button: no "Reload" option
5. Try to find a mimic somewhere.
6. Get some distance between you and the monster ("Run" once if you're not already faraway)
7. Watch the attack button: "Approach" is the only option, you can't use the usual "Shoot"

I'm guessing the upgrade function uses a generic template that doesn't carry over the weapon specificities, unless it's a weapon with a unique upgrade path. (e.g.: runed spellblade)

**Comment by Mendelrock** [comment]
Here is a link to an edited save with both a standard flintlock and an upgraded flintlock:
https://drive.google.com/open?id=1DBQORA7sD5ds5JBXyJ4Tz6_2vceBs2Wg
Hope you don't mind Google Drive, the file is not accepted by Github

**Comment by Eragonx0852** [comment]
I see at DebugMenu.as line 395 can be found the BLUNDR0 but none of the other upgraded variants, Same goes for other upgraded items. Dont know if this might be the problem? e.g. the upgrade to the Blunderbus is BLUNDR1 and BLUNDR2, neither of which are present in DebugMenu.as

**Comment by Mendelrock** [comment]
It might have to do with something like that, indeed. It seems the Blunderbuss acts as a melee weapon whether it have been upgraded or not.

**Comment by Kitteh6660** [comment]
Should be fixed with the latest commit now.
