### ISSUE TITLE
[Bug] Lovers tab turns to Slaves 

### ISSUE THREAD

**Issue by Andrevus2** [Kitteh6660/Corruption-of-Champions-Mod#1344]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
The Lovers button on the camp screen turns into a greyed out Slaves with a regular Slaves button right next to it if you drink milk from Isabella at 22:00 at night.

### Game version
Newest Non Vanilla+ version
	
### Expected behaviour
It should be a greyed out Lovers tab since everyone is asleep
	
### Actual behaviour
See overview

### How often can this be reproduced?
Once every ingame day.

### Steps to reproduce the issue

1. Reach 21:00 via any activity
2. Do anything that passes the time by 1 hour ( Spar with Ember/Helia/Helspawn/Valeria/Kiha, Have Sex with anyone, or do step 3 twice)
3. Initiate Sex with Isabella, then pick Drink Milk.

Note : Cannot provide save file since i play on standalone Flash Player with Hardcore file, and i don't know where those are saved, can supply Screenshot : https://imgur.com/a/zXvB9Gd

**Comment by Andrevus2** [comment]
Upon further testing i noticed that the bug also happened after other means of reaching 23:00 at night in the camp, so it seems like it's a more general bug.

**Comment by Stadler76** [comment]
I could reproduce it. Fix comes in a sec or two ;-)
