### ISSUE TITLE
[BUG?] Kelt Dialog? 

### ISSUE THREAD

**Issue by samsilly12345** [Kitteh6660/Corruption-of-Champions-Mod#1348]
I am using the newest update of the mod for CoC, version 1.4.13b 

I'm insure of how to correctly word this since i know nothing about coding or how to check this kind of stuff, but in short, when I go to see Kelt and get trained by him to use a bow, almost all of the dialog i love is gone. it completely skips the part where you strip, the part where you suck him off, the part where he talks about your tits or cock, or anything about that. It goes straight to the actual training session, the same phrases over and over, like "You're getting good, maybe you can actually defeat something. Like a huge blind giant." etc, things like that. 

The Kelt story and progression was one of my most favorite things to go and do in CoC, and it makes me very frustrated that it appears to have disappeared. Please fix or tell me why this is happening???

**Comment by brrritssocold** [comment]
@Kitteh6660 @Stadler76  Guess this can be closed as there was no response.

**Comment by brrritssocold** [comment]
What is the status of this issue? If it is resolved, please close it.
The issue can be re-opened at a later date if the issue re-occurs.

If there is no response I will request the issue be closed.
