### ISSUE TITLE
[Bug] save files

### ISSUE THREAD

**Issue by samsilly12345** [Kitteh6660/Corruption-of-Champions-Mod#1349]
- [ ✓] The bug is still present in the latest release
- [ ✓] Searched the existing issues so I do not open a duplicate issue

I try to use the "save as file" option in the game save place, instead of just "save to slot" and while it does let me save the game, it does not in any way let me load it. Do I need to use a certain suffix on the file name?
	
Game version
Most recent as of September 8th 2018, mod version 1.4.13b
	
What should happen is I save the game to file and am able to open it, this does not happen.
	
I try to open the file and it does not work whatsoever, it seems to freeze the game actually.

How often can this be reproduced?
This happens every time. 

(Also, why has my other bug/question about Kelt not been answered?)

**Comment by Stadler76** [comment]
![Ingame explanation](https://user-images.githubusercontent.com/13157984/45589800-92f48c80-b92c-11e8-8a9c-266da16e68be.png)

In other words: the save file must be in the same folder, where you've downloaded the swf to.
