### ISSUE TITLE
[Bug] Canine Pepper does not transform cock

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#1353]
### I have checked the following before submitting this issue:

- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Consuming any Canine Pepper (with the exception of the double pepper and knotty pepper) does not transform the players cock.
	
### Game version
CoC 1.0.2 - Mod v1.4.13b
	
### Expected behaviour
Using Canine Peppers will eventually turn the cock into dog's.
	
### Actual behaviour
All other transformations happen, but the cock does not transform.

### How often can this be reproduced?
Always

### Steps to reproduce the issue

1. Enter debug mode
2. Spawn different Canine Peppers 
3. Spam any type of Pepper (except the double pepper or knotty pepper)

**Comment by Stadler76** [comment]
I think I got it ([In line 336 of CaninePepper.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/ec6e0dda519392825760a039ad5c2645825b3004/classes/classes/Items/Consumables/CaninePepper.as#L336)):
```as3
				if (player.dogCocks() < player.cocks.length && ((changes < changeLimit && rand(1.6)) || type == 1) === 0) {
```
I'm working on a fix while I'm implementing type constants.

**Comment by Stadler76** [comment]
Note: Haven't looked at the blame, but it seems, that this was a regression. Hence the label.

**Comment by brrritssocold** [comment]
Odd part is that I remember the peppers working until not to long ago, maybe something else cause the bug to surface.
