### ISSUE TITLE
[Bug] Text on buttons in latest update is off

### ISSUE THREAD

**Issue by CyannaG** [Kitteh6660/Corruption-of-Champions-Mod#1355]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
- [x ] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
I just downloaded the newest version, all of the text in buttons is shifted to the right and largely cut off, it makes it kinda impossible to play.
	
### Game version
Tell us the version of the game where the issue occurs.
CoC 1.0.2 - Mod v1.4.14
	
### Expected behaviour
Tell us what should happen.
Text should be centered in buttons and readable.
	
### Actual behaviour
Tell us what happens instead.
Text is off to the right of buttons and cut off

### How often can this be reproduced?
Tell us how often this happens.
I tried re-downloading and comparing with the previous build, previous build is fine, most recent (today's) update is allways off on my computer.

### Steps to reproduce the issue

1. Download newest version of the mod
2. Open it
![untitled](https://user-images.githubusercontent.com/43503387/45920970-4f59cf80-bea4-11e8-8275-83316d23661d.png)

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by Kitteh6660** [comment]
Should be fixed in 1.4.14d now.
