### ISSUE TITLE
[Development] Dead code / Unused source files

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#1360]
What should be done with dead / unused source code?

This is code that is not used anywhere in the game and thus is not checked by the compiler (due to dead code elimination).

As time passes it will get harder to integrate the code as active code and dead code diverge more and more.
Due to the code not getting compiled, even simple syntax errors are not spotted.

My suggestion either fix and include them in the build, or remove them.

Exhibit A: [PlantGirlScene.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Scenes/Areas/Forest/PlantGirlScene.as)
Exhibit B: [NonPlayer.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/NonPlayer.as)
Exhibit C: [TestContent.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/content/TestContent.as)
Exhibit D: [Equipable.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Items/Equipable.as)
Exhibit E: [GoblinQueen.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Scenes/Monsters/GoblinQueen.as)

**Comment by Stadler76** [comment]
@brrritssocold wrote:
> Exhibit A: [PlantGirlScene.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Scenes/Areas/Forest/PlantGirlScene.as)

Since this has actual scene content in it you should ask @Kitteh6660 if this is still being worked on. If so, I'd suggest to move this into a branch.

> Exhibit B: [NonPlayer.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/NonPlayer.as)
> Exhibit C: [TestContent.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/content/TestContent.as)
> Exhibit D: [Equipable.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Items/Equipable.as)

These are all stubs and AFAICS can safely be removed. Since I intend to implement my own version of `Equipable.as` in issue #1340 and the existing version and my implementation will be completely unrelated it would totally make sense to remove this beforehand.

> Exhibit E: [GoblinQueen.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/c6dd767bffd83676c3fd94781051f499d30b7993/classes/classes/Scenes/Monsters/GoblinQueen.as)

Very old stub. Probably never to be continued. So I guess, this can safely be removed. If not, then same suggestion as for Exhibit A: Move it into a branch and keep the master branch clean.

**Comment by brrritssocold** [comment]
Could fix A and E, stick documentation in them to say that they are unfinished / abandoned.
Then add them with a `private var plantGirScene:PlantGirlScene = new PlantGirlScene()` to `CoC.as`. This would be enough to include it in the build - so any future breaking changes will fail the build. 

Case in point: `PlantGirlScene.as` uses `kFLAG` consts that were either never assigned or reclaimed, leading to build errors.

**Comment by Stadler76** [comment]
How about adding the kFLAGS consts 'temporarily' to `PlantGirlScene` and make the `flags` used in that scene local. e. g.:
```as3
private var _localFlags:DefaultDict = new DefaultDict();
```
Obviously along with a todo to move them to the `kFLAGS` later.

**Comment by brrritssocold** [comment]
Turns out that simply adding a definition e.g. `private var plantGirScene:PlantGirlScene;` is enough for the compiler to process the file.
