### ISSUE TITLE
Can't get mods or images to work

### ISSUE THREAD

**Issue by KratosPendragon** [Kitteh6660/Corruption-of-Champions-Mod#137]
Nothing seems to work for me, so I cant play the game. Every time I try this happens 
![coc problems](https://cloud.githubusercontent.com/assets/12958364/10124699/1824cd6a-6521-11e5-9a06-255a378ceb96.PNG)
  and if I click ok then this happens (all of them say the same thing)
![more coc problems](https://cloud.githubusercontent.com/assets/12958364/10124711/5e60b1fe-6521-11e5-8782-0c42d7910541.PNG)
 Sadly, I have no idea what this means other than I did something wrong. Please help!

**Comment by Kitteh6660** [comment]
It's probably not the game itself but rather, it has something to do with Flash Player.
Try uninstalling Adobe Flash Player and reinstall it. See if it works.

**Comment by Fregrant** [comment]
Maybe would try browser instead. I using Firefox for SWFs.
Not sure if imagepack will work, though.

**Comment by KratosPendragon** [comment]
Could it be a problem with what I'm using to play the game? I'm using Flash Movie Player 1.5. The main reasons I want to use this mod is the image packs and all the new content.

**Comment by KratosPendragon** [comment]
... I was just being a colossal idiot. Thanks for putting up with my stupidity.
