### ISSUE TITLE
Disgusting pedophiles on 8chan changed the CoC mod to include child rape

### ISSUE THREAD

**Issue by WHYDONTYOULIKETHEPIECEAPIE** [Kitteh6660/Corruption-of-Champions-Mod#1370]
https://8ch.net/hgg/res/263233.html

**Comment by Kitteh6660** [comment]
I have no association with 8chan whatsoever and such mods on 8chan are not supported in any way.

I do not recommend playing that one on 8chan and it's suggested that you use Discord for approved mods instead.

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment]
@Kitteh6660 
I'm here to make you aware of it. Please make fenoxo aware of this and take any appropriate measures as necessary. I also overheard that these sick bastards plan on gutting the character "urta" out of the game and turning it into another sick twisted abomination.

**Comment by brrritssocold** [comment]
Why not contact Fenoxo directly via the forum or discord?

**Comment by eksynn** [comment]
because SJW's

**Comment by brrritssocold** [comment]
Close this ticket as it has nothing to do with the Repo?

**Comment by Stadler76** [comment]
Like the others stated: This is the wrong fork to 'complain' about other CoC-mods violating FenCos ToU.

And: We are not your messengers. Complain to FenCo directly. Or do you call the plumber to tell him, that he should call the firefighters, when your house is on fire?

\~closed\~
