### ISSUE TITLE
[Bug?] Times_Fucked_Femoit stat doesn't get incremented after sex, doesn't get pregnant

### ISSUE THREAD

**Issue by Andrevus2** [Kitteh6660/Corruption-of-Champions-Mod#1374]
- [x ] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x ] Filled out the template, so developers are less likely to ask for more info

### Overview
Having sex with Benoite doesn't increase the stat mentioned in the title, while also making basilisk pregnancy from male champion and feminized Benoit not happen regardless of stats.
	
### Game version
1.4.14
	
### Expected behaviour
After RNG + calculations a pregnancy should happen if the calculated number is within the specified range for it to happen, Times_Fucked_Femoit stat in the save should be incremented regardless.

### Actual behaviour
No changes occur in the save's stat, Benoite's pregnancy is never calculated.

### How often can this be reproduced?
Every time you can have sex with her.

### Steps to reproduce the issue

1. Feminize Benoit
2. Have Sufficient Lust after the first sex scene
3. Press Sex when she's available

### Note
Tried with regular save and later with an edited save that had a 13 times multiplier on virility to better odds of pregnancy with any NPC, no change in results.

**Comment by Kitteh6660** [comment]
According to the code, you'll need to knock Femoit up at the right time. There's a clutch cycle lasting 28 days each. 21 days, she won't have a clutch. The rest of the 7 days, she'll have a clutch, that's your window of opportunity.

However, the counter being incremented will be fixed with the commit.
