### ISSUE TITLE
Hellcats!

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1380]
This is for work on the [Hellcat encounter and Subtf](https://docs.google.com/document/d/1eGEbvZvhH4bgG6Lq4j3W7-Rqwz2clSA6xv4YJy6OLlo/edit) by @Liadri.

Current working branch: https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/master...Stadler76:Hellcats

Any help would be appreciated.

**Comment by Stadler76** [comment]
Since Liadri has a PC-outage: Any help with the stubs for the Hellcat-implementation would be neat: https://gist.github.com/Stadler76/719e1cc3b83c441d5056b733905cbd8a

**Comment by Kitteh6660** [comment]
Closed due to it being a feature addition. You're welcome to add anytime but the focus is on tying up any loose ends.
