### ISSUE TITLE
[Bug] Latex Goo Girl cock description doesn't change

### ISSUE THREAD

**Issue by trashheapr** [Kitteh6660/Corruption-of-Champions-Mod#1381]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
The Latex Goo Girl's cock description is not working properly. It does not display an appropriate descriptor. 
	
### Game version
CoC_1.0.2_mod_1.4.15
	
### Expected behaviour
When the Latex Goo Girl has her cock described it should match cock type of the items she has been given.
	
### Actual behaviour
There is no unique description for any cock type.

### How often can this be reproduced?
It happens every time I try to make the Latex Goo Girl a herm.

### Steps to reproduce the issue

1. Acquire the Latex Goo Girl
2. Raise Latex Goo Girl's obedience to above 40%
3. Give the Latex Goo Girl an incubi draft. The cock description will be not include anything about type.
4. Give the Latex Goo Girl an equinum. There will be no change to the type description.

### My understanding of the problem
From my understanding of the code, the problem is a mismatch of the data types being used and expected in the GOO_DICK_TYPE flag. In LatexGirl.as the value of flags[kFLAGS.GOO_DICK_TYPE] is set to a CockTypeEnum value in the [latexyEatsADickItem](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/200c74c9091d559691276d9e014ab398e30b3ba1/classes/classes/Scenes/NPCs/LatexGirl.as#L697) method. However, when the flags[kFLAGS.GOO_DICK_TYPE] value is [read](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/200c74c9091d559691276d9e014ab398e30b3ba1/classes/classes/Scenes/NPCs/LatexGirl.as#L112) it is expecting an integer. I believe this can be resolved by either changing the descriptor function to just use the enum value in flags[kFLAGS.GOO_DICK_TYPE] or by storing the dick type index in  flags[kFLAGS.GOO_DICK_TYPE] when it is written to.

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request
