### ISSUE TITLE
[Bug] Isabella cannot be sexed

### ISSUE THREAD

**Issue by Sezmil** [Kitteh6660/Corruption-of-Champions-Mod#1384]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [X ] The bug is still present in the latest release
- [X ] Searched the existing issues so I do not open a duplicate issue
- [X ] Filled out the template, so developers are less likely to ask for more info

### Overview
When trying to have sex with Isabella system fades out the "Fuck Her" option and the tool tip says your are too big. I have tried reducing cock size to 6" and still have the same issue.
	
### Game version
1.0.2_mod_1.4.15
	
### Expected behavior
When you select the sex option from Isabella's menu, the "Fuck Her" should be available to have sex with her.
	
### Actual behavior
When you select the sex option from Isabella's menu, the "Fuck Her" option is unavailable and the tool tip says "Your dick is too big to fit"

### How often can this be reproduced?
Every time

### Steps to reproduce the issue

1. From the Main Menu Select "Lovers"
2. From the sub menu select "Isabella"
3. From Isabella's menu select "Sex"
4. In the "Sex" menu "Fuck Her" is faded and cannot be selected, tool tip says Your dick is too big"

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

[CoC_1.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/2588023/CoC_1.zip)

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [x] Trying to reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request
