### ISSUE TITLE
[Perma-Perks] Acquiring Corrupt / Enlightened Nine-Tails makes it impossible to get nine tails afterwards?

### ISSUE THREAD

**Issue by Erubetea** [Kitteh6660/Corruption-of-Champions-Mod#1387]
After acquiring both the Enlightened/Corrupted Nine-Tails perks and doing an another ascension playthrough, I found it is impossible to acquire nine tails through either the pure/corrupt method, despite hundreds of attempts with a kitsune character which possesses eight tails currently.

**Comment by brrritssocold** [comment]
**Please fill out the issue template, it's there for a reason.**

Please provide steps to reproduce the issue.

- Version number of the game or commit hash used to build the binary
- Starting state or save file
- A list of actions and events that reproduce the issue

**Comment by Stadler76** [comment]
Steps to reproduce are many, since you need to ascend at least twice to get both perks perms. But a save file for testing would be very helpful.

**Comment by Stadler76** [comment]
Steps to reproduce are many, since you need to ascend at least twice to get both perks permed. But a save file for testing would be very helpful.
