### ISSUE TITLE
Rhino TF

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#139]
It seems that the rhino skin descript vanishes from "appearances" at some point. I can't recall or find any scenes that specifically mention skin/fur/scale description(s) to test this more. 
Also, a rhino tail changes to a cat tail eventually, though again I'm not sure when this happened.

**Comment by Kitteh6660** [comment]
Turned out I forgot to include skin description for rhino face.

Try to recall when a rhino tail changes.
