### ISSUE TITLE
[Bug] Drider Ovipositor Ride blank page 

### ISSUE THREAD

**Issue by TheUwUGod** [Kitteh6660/Corruption-of-Champions-Mod#1390]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:

- [x] The bug is still present in the latest release
- [ ] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
In this save file if i win against drider (Big spider girl located in the swamp) and i try to go for RideOviAnal it is just a blank page
	
### Game version
Tell us the version of the game where the issue occurs.
1.4.15	
### Expected behaviour
Tell us what should happen.
There should be a page full of text with it ending in eggfilling	
### Actual behaviour
Tell us what happens instead.
Denied of clicking it and text disappears
### How often can this be reproduced?
Tell us how often this happens.
Every time i try to go for it.
### Steps to reproduce the issue
1. Go to swamp until you meet the big spider girl
2. Win against the spider girl with enough lust to have sex with her,
3. Go for RideOviAnal

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._
https://mega.nz/fm/BO5DgA6D
Extra Information: Playing the game in SWF File Player

**Comment by Stadler76** [comment]
The mega.nz-link doesn't work for me.
