### ISSUE TITLE
Impossible(?) to download

### ISSUE THREAD

**Issue by Cheeseburgerdude** [Kitteh6660/Corruption-of-Champions-Mod#1396]
I can't open the game because I can't open adobe flash player anymore. I can still download it but for some reason the app doesn't associate itself with the download..(??) I get an error message after downloading one of the three folders (the only one that isn't zipped) that reads "This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

https://forums.adobe.com/thread/2469426

(The last comment)
"Google Chrome is no longer supported on OS X 10.6.8.  The last version of Google Chrome that supported OS X 10.6.8 was Chrome 49.  Chrome 49 has an embedded version of Flash Player, which is no longer being updated since Chrome is no longer supported on OS X 10.6.8.  Chrome 49 is only aware of the embedded Flash Player location, therefore, when you install Flash Player Chrome 49 isn't aware of the directory it's installed to, and therefore, doesn't load it."

When I go to the Adobe folder itself to try and troubleshoot it somehow I only get as far as opening the option to uninstall it. 

Another kind of unrelated thing is that when I try to delete it, it tells me that I need to be the admin when I am the admin, I don't know what's up with that.

**Comment by brrritssocold** [comment]
Based on your issue I'm going to assume that you are running OS X (since you did not explicitly state it).

You can get the standalone flash player [here](https://www.adobe.com/support/flashplayer/debug_downloads.html)

Under the section Macintosh, select 'Download the Flash Player projector'.

While the appropriate standalone works for Windows 10 and Linux, I have not tested this on OS X (as I do not own a mac.). It may or may not work with the latest OS X.

**Comment by Cheeseburgerdude** [comment]
Yeah I'm running it on Windows 10. is there a fix for this bug?

**Comment by brrritssocold** [comment]
Have you tried running the SWF file with the 'Flash player projector' for Windows?
Can you set the exe as the default for SWF files?

If not, the patch (KB) mentioned in [this question](https://superuser.com/questions/1366302/windows-10-wont-let-me-set-default-apps-for-file-extensions) *may* resolve your issue.

**Comment by brrritssocold** [comment]
Have you had any luck getting the game to run?

**Comment by Cheeseburgerdude** [comment]
yeah I did, I ran the game via the flash projector adobe provides as you suggested, thank you. Although I still have a bunch of adobe flash player files I can't delete now lol

**Comment by brrritssocold** [comment]
Can you please close the issue if has been resolved?

**Comment by Stadler76** [comment]
Due to no reply I assume its being resolved. Hence I'm closing it.

@Cheeseburgerdude: If this issue still persists, feel free to reopen it.
