### ISSUE TITLE
How do give Kiha panties?

### ISSUE THREAD

**Issue by Havrrics** [Kitteh6660/Corruption-of-Champions-Mod#14]
I can't seem to figure out how to do it for the life of me, what am I missing here? Also unrelated could you at some point integrate the "Helspawn Quality Time" scene? Thanks in advance.

**Comment by Kitteh6660** [comment]
You'll need spider-silk panties.

I'm not sure about Helspawn Quality Time but I might eventually integrate it in some time.

**Comment by Havrrics** [comment]
One other thing, the Isabella children stuff, is that gonna be something that will be added in a coming update or is that a placeholder for an eventual update that may or may not come?
