### ISSUE TITLE
Rhino TF (snapshot 20151009)

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#140]
Hey, Kitteh.
Sooo the rhino skin description is definitely showing now...except for when the PC has a rhino face. Could you have forgotten to include a skin-type description within the face description for rhino?

As far as I can tell, the rhino tail isn't turning randomly into a cat tail for now. Will report any changes. Thanks for all you do.

**Comment by Kitteh6660** [comment]
This should hopefully be fixed in next snapshot.
