### ISSUE TITLE
Saved Games Never Stick

### ISSUE THREAD

**Issue by Cheeseburgerdude** [Kitteh6660/Corruption-of-Champions-Mod#1404]
My saved games disappear after I close the game every time, I can still save a file separately thankfully but like, I can't save it directly to the game so... yeah lol. I tried checking out the saves via the games folder itself but I can't because it's on adobe?? not sure what's up with that.

**Comment by brrritssocold** [comment]
Please fill out the issue template, it's there for a reason.

The template ask for details like:
- Version number of the game or commit hash used to build the binary
- Starting state or save file
- A list of actions and events that reproduce the issue

**Comment by brrritssocold** [comment]
@Kitteh6660 @Stadler76 Can this be closed due to lack of response?
