### ISSUE TITLE
Missing-ish Content 

### ISSUE THREAD

**Issue by Cheeseburgerdude** [Kitteh6660/Corruption-of-Champions-Mod#1405]
This isn't an issue as much as it is just unfinished work; I think, I just wasn't sure about a better place to point out that some of the text in game is weird.

I got this after eating a Neon Pink egg, I've eaten a looooot of these eggs recently to kick up my cum production but at some point it stopped saying the regular text and started saying this, (the "!Unknown subject in “eachcockUC”!" is in bold).

A strong contraction passes through your sack, almost painful in its intensity. !Unknown subject in “eachcockUC”! leaks and dribbles pre-cum down your legs as your body’s cum production kicks up even higher.

Perhaps it's worth noting that I'm in the last stage of pregnancy. I'm pretty sure they just mean my dick but honestly.... what if it means my soon to be alien dick, y'know? lol.. I just want to know what I might be missing.

**Comment by brrritssocold** [comment]
Please fill out the issue template, it's there for a reason.

The template asks for details like:
- Version number of the game or commit hash used to build the binary
- Starting state or save file
- A list of actions and events that reproduce the issue

**Comment by Stadler76** [comment]
Stupid me made a copy&paste-error in [singleArgLookups.as](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/commit/92aef8690d6162cde33ef2e91f825c2b790d44d6#diff-bf28723c2a5581cfaf71f9b7254ece40):
```as3
// Note: all key strings MUST be ENTIRELY lowercase.
```
A fix will come up soonish.
