### ISSUE TITLE
[Bug] Missing Fetish Cultists

### ISSUE THREAD

**Issue by Xeretinha** [Kitteh6660/Corruption-of-Champions-Mod#1410]
### I have checked the following before submitting this issue:
- [x ] The bug is still present in the latest release
- [x ] Searched the existing issues so I do not open a duplicate issue
- [x ] Filled out the template, so developers are less likely to ask for more info

### Overview
Fetish Cultists doesn't appearing uppon Lake explorations
	
### Game version
Revamp 1.4.15 (latest stable)
	
### Expected behaviour
Fetish Cultists being meet randomly while exploring the Lake region after PC reaching 4th lvl or more

### Actual behaviour
Did explored that region over a thousand times (Izma is even already being follower) and never faced atleast one F. Cultist. Currently at 12th lvl.

### How often can this be reproduced?
guess doesnt applyes

### Steps to reproduce the issue
guess doesnt applyes

**Comment by Stadler76** [comment]
You have to reach level 2 **and* clear the demon factory (shutdown or overload the valves).

Code for its requirements:
```as3
public function encounterChance():Number {
	return player.level >= 2 && flags[kFLAGS.FACTORY_SHUTDOWN] > 0 ? 1 : 0;
}
```

**Comment by Xeretinha** [comment]
Sorry then! 

I was taking as basis the texts at the wikies (both smutosaur and fandom), and at none of says about the need of shutting de factory down to start the encounters. Since it seemed me a bug due this lack of info, i'd decided to post about directly here instead to post at the forums.

Guess the issue can be already closed in this case.
