### ISSUE TITLE
[Question] "Impulse" (scene viewer) function?

### ISSUE THREAD

**Issue by JustPassingThrough99** [Kitteh6660/Corruption-of-Champions-Mod#1413]
Hi all,
Just a quick question. Is there a function to jump to specific scenes for debug purposes?
In TiTS you can type "impulse" then type in the name of the scene to trigger it, I was wondering if there is a similar feature here.

Thank you!

**Comment by JustPassingThrough99** [comment]
Never mind, found it.

You must edit your savegame to have the Debug Wand, then use it and go to Scene Viewer. It is actually pretty in-depth as well, although for triggering certain scenes you need to edit some flags.

**Comment by brrritssocold** [comment]
# **Spolier**
 
You can type `debug` to enter the debug menu (sometimes the first key press will not be registered, so press any key and then `debug`)
From there you can select 'Scene Test' then find the method that triggers the scene. 

You might be able to trigger the scene by using from the menu: Options > Debug Info > Test Input.
