### ISSUE TITLE
[Bug] Unable to progress past day 1

### ISSUE THREAD

**Issue by Squirrel24** [Kitteh6660/Corruption-of-Champions-Mod#1418]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [ ] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
When I press sleep, the game does not progress to the next day. Im stuck on day 1.
	
### Game version
1.4.16
	
### Expected behaviour
When I press sleep, the game progresses to the next day.
	
### Actual behaviour
The textbox becomes empty and nothing else happens. 

### How often can this be reproduced?
Any time the day ends, I have yet to gat beyond day 1, regardless of tutorial in ingnam or skipping to Mareth.

### Steps to reproduce the issue

1. Create a character
2. Play until the end of a day
3. Press the "sleep" button

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by ShadowMarker789** [comment]
I'm also getting this issue too.

**Comment by Kitteh6660** [comment]
Should be fixed in version 1.4.16b now!
