### ISSUE TITLE
missing inventory when save and reload

### ISSUE THREAD

**Issue by verinax** [Kitteh6660/Corruption-of-Champions-Mod#1422]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [ ] The bug is still present in the latest release
- [ ] Searched the existing issues so I do not open a duplicate issue
- [ ] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
	
### Game version
Tell us the version of the game where the issue occurs.
	
### Expected behaviour
Tell us what should happen.
	
### Actual behaviour
Tell us what happens instead.

### How often can this be reproduced?
Tell us how often this happens.

### Steps to reproduce the issue

1. First step
2. Second step
3. and so on...

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by verinax** [comment]
v1.4.16d for CoC 1.0.2
Everything I have in inventory as well as storage chests when I save is missing when I reload that save.

**Comment by TheNilar** [comment]
i already submitted this bug. and check my issue page on how you are supposed to write the issues.https://github.com/Kitteh6660/Corruption-of-Champions-Mod/issues/1421

**Comment by Stadler76** [comment]
Duplicate of #1421 and totally invalid use of the issue. Did you even bother reading it?
