### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NORMIESUCK** [Kitteh6660/Corruption-of-Champions-Mod#1425]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [ ] The bug is still present in the latest release
- [ ] Searched the existing issues so I do not open a duplicate issue
- [ ] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
	
### Game version
Tell us the version of the game where the issue occurs.
	
### Expected behaviour
Tell us what should happen.
	
### Actual behaviour
Tell us what happens instead.

### How often can this be reproduced?
Tell us how often this happens.

### Steps to reproduce the issue

1. First step
2. Second step
3. and so on...

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by Kitteh6660** [comment]
No context. Closed.
