### ISSUE TITLE
[Bug] Cannot Debimbo Jojo

### ISSUE THREAD

**Issue by BaldurAnthology** [Kitteh6660/Corruption-of-Champions-Mod#1427]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
_Remove this hint: these checkboxes can be checked like this: [x] - Remove this line if you read and understood the checkboxes below_
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
You can't De-bimbo Jojo. It says in theory that you can in the dialogue and stuff but when you make the De-Bimbo there's no option to give it to him. I want to be able to de-bimbo him because I want to see if there would be unique dialogue after having him regain his senses.. maybe something about how he does love you or something merging both personalities.. to make him the HIM he implies he always wanted to be for you? I just find it a bit annoying that he's the only one you can't De-bimbo
	
### Game version
1.4.17b
	
### Expected behaviour
In theory you should be able to de-bimbo Jojo and have him able to regain his old mental faculties or some combo between the two. 
	
### Actual behaviour
No option available even though he does mention the possibility.

### How often can this be reproduced?
Any time you bimbo Jojo.

### Steps to reproduce the issue

1. First step Obtain Bimbo Liqueur, example Zetaz's lair.
2. Second step Store in chest and wait requisite time.
3. Step Three tell him to catch thief so he becomes a bimbo.
4. Step Four create debimbo and attempt to turn him back to non-bimbo.

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by Kitteh6660** [comment]
The option is just not coded yet.

**Comment by BaldurAnthology** [comment]
Ah. Hopefully next update then? Also thank you for fixing that crap with the chest.. Whenever the Russet Rogue would visit it would make the chest unusable... same with ascending, so that being fixed is good.
