### ISSUE TITLE
Reloading a save causes items in chests to vanish.

### ISSUE THREAD

**Issue by Kitata** [Kitteh6660/Corruption-of-Champions-Mod#1429]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:

- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
	Ok, so basically the issue I'm getting is the fact that the chests will be empty, no matter what I put in it, when I reload a save. I kinda do this often to avoid bad ends and when trying to get certain items or transformations, so I've basically stopped using the chest.
### Game version
Tell us the version of the game where the issue occurs.
	I'm using 1.4.17.
### Expected behaviour
Tell us what should happen.
	The items should stay when you reload a save.
### Actual behaviour
Tell us what happens instead.
The items are missing when I reload a save.
### How often can this be reproduced?
Tell us how often this happens.
Every time I reload/load up a save.
### Steps to reproduce the issue

1. Get the chest.
2. Put, say, a Goblin Ale in the chest.
3. Reload the save.

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

[My Snake Drake file_2.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/3317387/My.Snake.Drake.file_2.zip)

**Comment by Kitteh6660** [comment]
I cannot replicate it with the build. When I put items inside the chest and reloaded, it's still there. Even restarted the game to reload, it's also there.

Are you using Save or Save to File?

**Comment by Kitata** [comment]
OK so I loaded up my save to find some of my original inventory (from when I started this save) and that amuses me, but not an issue. 

However, I'm now getting a similar issue where I think either the snake oil is returning to my inventory when I reload (as its not in the chest) or that the glitch is still happening, though now with a bonus glitch of items appearing in my inventory every time I reload. I'm going to attempt to see if I can see which is happening.

OK so yeah, the glitch is still happening, though now I'm just getting free items (snake oil, hair growth stuff, the beautiful sword, purity pearl, and purity ring,) but considering that I had originally made this save on a different version, I might do a test of a new save.

**Comment by Kitata** [comment]
OK! So I think I found the issue and its most likely the fact that since CoCED wasn't working for the recent versions, I made a save and edited it on a previous version and then used played the save in the recent version. I just made a new save to test it, and its only with the snake drake save. Thanks for your time, though!

**Comment by Kitata** [comment]
Oh wait, for the save or save to file question (do not know how I missed that!) I was using the save option!
