### ISSUE TITLE
Isabella children problems

### ISSUE THREAD

**Issue by timo103** [Kitteh6660/Corruption-of-Champions-Mod#143]
In the lovers tab cowgirl children show up as human herms. The two human herms should be cowgirls?

Isabella is sitting down with a knife, the blade flashing in the sun as wood shavings fall to the ground. Her hands move with mechanical, practiced rhythm as she carves a few hunks of shapeless old wood into tools or art. Isabella has set up a small part of her “corner” in the camp as a nursery. She has sawn a number of barrels in half and lined them with blankets and pillows to serve as rocking cribs. You have a human son, a human daughter and two human herms with her, all living here; unlike native Marethians, they will need years and years of care before they can go out into the world on their own.

In the stats page they do show up correctly as cowgirls.

I don't even know if Isabella can have actual herm children.

**Comment by Kitteh6660** [comment]
Fixed in 1.3.1.
