### ISSUE TITLE
[Bug] "Tension" Encounter does not turn penis demonic

### ISSUE THREAD

**Issue by SargMjr24** [Kitteh6660/Corruption-of-Champions-Mod#1430]
### Overview
The "Tension" encounter at the Demon Factory does not turn penis demonic, as it is supposed to.
	
### Game version
Latest release (1.4.17b)
	
### Expected behaviour
Penis should turn demonic.
	
### Actual behaviour
Penis does not turn demonic.

### How often can this be reproduced?
100% of the time.

### Steps to reproduce the issue
1. Have non-demonic penis.
2. Visit Demon Factory and select "Tension".
3. Leave and check "Appearance" to see that it is not in fact demonic.

**Comment by Kitteh6660** [comment]
It doesn't, that's how it was in vanilla.

The mention of infernal dick, that actually belongs to someone else.

**Comment by SargMjr24** [comment]
Are there any other ways to get infernal dicks then?
