### ISSUE TITLE
Benoit won't stop rambling about Basilisk Womb recipe

### ISSUE THREAD

**Issue by Kitata** [Kitteh6660/Corruption-of-Champions-Mod#1431]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:

- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
	Benoit is once again rambling about the way to get the Basilisk Womb perk. I've talked to him about three or four times since getting the perk, and its all he talks about right now.
### Game version
Tell us the version of the game where the issue occurs.
	1.4.17c.
### Expected behaviour
Tell us what should happen.
	Benoit should be talking about a variety of subjects that relates to him.
### Actual behaviour
Tell us what happens instead.
He just repeats the dialogue that tips you to how to get the Basilisk Womb perk.
### How often can this be reproduced?
Tell us how often this happens.
After getting the perk, every time I talk to him.
### Steps to reproduce the issue

1. Get Basilisk Womb Perk.
2. Talk to Benoit
3. Redo step 2 a few times.

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by Kitteh6660** [comment]
I've taken a look and realized that the conditions have not changed.

Try having sex one more time or lose a pussy, and see if that will change.
