### ISSUE TITLE
[Bug] Greta's Garments shop won't well cock socks

### ISSUE THREAD

**Issue by JantraBelakar** [Kitteh6660/Corruption-of-Champions-Mod#1437]
_Please prefix the title with the issue type: [Bug], [Enhancement], [Question], [Other]_

### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Give us short description of the issue.
Greta's Garments in the Bazaar never expands its stock to sell cock socks, no matter how much time passes in-game or however often the "Low Stock" option is chosen.
	
### Game version
Tell us the version of the game where the issue occurs.
1.4.17c

### Expected behaviour
Tell us what should happen.
Greta should not have the cock socks for sale at first, but once the "Low Stock" option is chosen and one in-game day passes, she should sell the cock socks.

### Actual behaviour
Tell us what happens instead.
Greta forever has no cock socks for sale, and the "Low Stock" option never leaves her store. However, on a save from the previous version of the game where Greta's store had already been used, she still sells the cock socks when that save is used in this version. Attempting to choose the "Low Stock" option again, waiting for many days, and even buying the bikini have not expanded her stock.

### How often can this be reproduced?
Tell us how often this happens.
On two separate playthroughs starting at the beginning on 1.4.17c, this behavior has occured. No attempts to get her to sell cock socks have been successful on this version.

### Steps to reproduce the issue

1. Create new game, or load a save in which Greta has not been spoken to.
2. Enter Greta's store for the first time and choose the "Low Stock" option.
3. Come back the next day, or any amount of time later, to find that she still does not sell cock socks.

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by Roksik-ever** [comment]
Can confirm, same thing on 1.4.17 android version.

**Comment by linklight2** [comment]
Can confirm, visited the shop at around day 30 asking about low stock, day 120 still low stock

**Comment by Kitteh6660** [comment]
This will be fixed in 1.4.18!
