### ISSUE TITLE
[Bug] Living Statue messes up the Pacifist run

### ISSUE THREAD

**Issue by Roksik-ever** [Kitteh6660/Corruption-of-Champions-Mod#1439]
### I have checked the following before submitting this issue:
- [x] The bug is still present in the latest release
- [x] Searched the existing issues so I do not open a duplicate issue
- [x] Filled out the template, so developers are less likely to ask for more info

### Overview
Trying in vain to get the Pacifist achievement on a NG+ without save editing. There is a major issue: the Living Statue can only be killed through HP damage and that sets the TOTAL_HP_VICTORIES count to 1. Editing it back to 0 and going through the remaining battles does result in the achievement, but right now the statue part is either bugged, or, if it can after all be defeated through lust, this is WAY too unobvious.

These is also a smaller issue with Lethice I kept running into: during the second (last) battle she will ALWAYS shield herself from lust attacks making tease/arouse/tentacle hair useless. I found that constricting her with a naga tail allows for successful teases, but I wonder whether it's the intended solution.
	
### Game version
1.0.2_mod_1.4.17 Android version
	
### Expected behaviour
Killing the Living Statue should not raise the TOTAL_HP_VICTORIES counter
OR
The statue should be defeatable by lust.
ALSO
Lethice always shields against lust in the last battle.
	
### Actual behaviour
1. Killing the Living Statue messes up the pacifist run.
2. Can not defeat Lethice through lust without a naga tail.

### How often can this be reproduced?
Every time.

### Steps to reproduce the issue
1. Only fighting with lust, sparing NPCs all the way to the stronghold. Before the statue I have the TOTAL_HP_VICTORIES count at 0.
2. Kiling the statue, checking TOTAL_HP_VICTORIES: it's at 1.

**Comment by Kitteh6660** [comment]
Should be resolved and will eventually make its way to 1.4.18.
