### ISSUE TITLE
[Feature request] Allow Shouldra to save the player from oversized bad end

### ISSUE THREAD

**Issue by alexolog** [Kitteh6660/Corruption-of-Champions-Mod#144]
Shouldra, as a follower, can (reluctantly) shrink oversized body parts.
If realistic mode is engaged and the player is over the limit, a shrinking-by-Shouldra scene could be triggered, similarly to srinking by reducto or being saved by Jojo.

**Comment by zevelorgani** [comment]
Great!  I am a huge fan of Shouldra, any chance of having more content with her?
