### ISSUE TITLE
Travis is on a failfest again ... yay!

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#1440]
Travis is on a fail party again...

See [this example job](https://travis-ci.org/Kitteh6660/Corruption-of-Champions-Mod/jobs/576591755) always failing with:
![grafik](https://user-images.githubusercontent.com/13157984/63659167-2460b580-c7b0-11e9-99ba-ac3a21fb86cf.png)

**Comment by Kitteh6660** [comment]
I don't know why it broke. All I did was changing some unrelated code. Someone should look into it. I didn't set up Travis myself.

**Comment by Stadler76** [comment]
@brrritssocold did. But I can't assign him to this issue. According to [this issue comment] Travis has moved from Oracle JDK to OpenJDK and the latter not having the command `jdk_switcher` anymore. I hope, that he sees this, since I tend to fail horribly when attempting to fix Travis builds ...

**Comment by brrritssocold** [comment]
Sorry, did not see this until now. Travis CI has upgraded the default worker VM image to Xenial.
Should be able to get this up and running shortly.
