### ISSUE TITLE
ExtraCoC - gimme answer

### ISSUE THREAD

**Issue by Deadmanovi4** [Kitteh6660/Corruption-of-Champions-Mod#145]
At first, i give you a thanks for updating a code. Your update give me a second wind.

I'm Dezerdnore, novice modder at ActionScript and i try create my mod ExtraCoC since 06.11.15.
Almost all coding time i spend to russification CoC and adding some new scenes for vanilla monsters.
Sorry, I bad speak english (because i'm russian), so please try to undestand my words and help me with my problem.

I read all of the code and was sure that I understood how it works. Until a certain time. First of all I added default appearanse and flags and added them to the list appearanse. I wrote the first monster and gave him a few new defaulted body parts. I run the test and saw that the monster did not add. Adding new body parts were failed. Starting the scenes did not occur, and the report shows that the parts of the body are not initiated. Check again codes, check with other monsters and scenes. Nothing.

As soon as I saw that you were able to add a new part of the body and initiate them - it surprised me.
Please, if you is not difficult, explain what I did wrong?

Codes on Yandex Drive. Here: https://yadi.sk/d/A4NaTdIikwqQS
As soon as I finish at least a part of my creation, i copy all ExtraCoC codes and add it on GitHub as source code modification (though only in the Russian version, because i'm a worthless translator ]: ).
The codes in Yadi.sk I update daily. Something plans, adds or change.

My Mod will be a miserable addition of 4 new locations, 30-50 monsters, 120+ scenes, 2 parasites, cheats (where the same without them), the ability to switch between languages ​​(between Russian and English) and advanced magic (junk and placeholder, please ignore extraChars =) ), and use Ember in sex scenes and sometimes transformate him\her into something new (at least one sex scene with him\her is added, SpawnScene).

My defaults are
here -> includes / extraDefs.as
and here -> classes / classes / ExtraCoC / Basic / extraFlags.as
Flags are functioning as expected, default is not very much, as i want.

Thank you for modification. Thanks for menu(), it became easier to make NPCs.

I'm sure our paths will cross more and we will do CoC better.

Dezerdnore

P.S. Disable ExtraCoC\NPC\CheatHelper.as. I not complete him.

**Comment by Netys** [comment]
Дохлое дело, как по мне. Если в английском языке подход с подстановками реальзуется легко, то в русском окончания придется через слово менять в зависимости от пола персонажа. Или использовать весьма странные безличные построения.

А что касается самого вопроса я не совсем понял - ты пытаешься добавить новую часть тела, которой раньше не было, или просто еще одну расу? Лезть в я.диск не хочется, он мягко говоря не особо удобен для просмотра кода, надо всё скачивать.

**Comment by Kitteh6660** [comment]
You might have to copy and paste the definition code, unfortunately. It's probably due to some limitations.

You'll have to add some things to appearanceDefs.as file under includes then look into Appearance.as under classes.

I would recommend leaving some space in case in the future I ever decide to add more TFs.

I'm going to be interested in such modification!

**Comment by Deadmanovi4** [comment]
Ya.disk can open .as files as text document.

I update some code and find a answer for my question. New updates incoming =)
