### ISSUE TITLE
Android Build Crashes on Droid Maxx (Model No. 1080m)

### ISSUE THREAD

**Issue by PwnzLPs** [Kitteh6660/Corruption-of-Champions-Mod#149]
I installed the latest build of CoC Revamp Android I could find (1.3.2), and when I try opening it, the game crashes the second I try opening it. Don't know if I can pull a crash log from that but I can try. I'll give you more info as I get it, as well as any info once I get my tablet working if that has issues too.

**Comment by dragontamer8740** [comment]
Does it still happen in this build I made of 1.3.7?
https://dl.dropboxusercontent.com/u/74519404/CoC-AIR_0.9.4_mod1.3.7-git.apk
Note that this will not overwrite your current revamp app, and you'll need to use 'save to file' to transfer saves over to it. Also, I haven't really changed it, so it could just be a difference in build settings. I'm interested to know.

**Comment by PwnzLPs** [comment]
I'll install it and let you know.

**Comment by PwnzLPs** [comment]
Success! It loaded up perfectly on my phone. No crashes. Just took a little longer than normal CoC, but that is to be expected from a mod

**Comment by dragontamer8740** [comment]
In that case, I'll share my XML file with my iOS/android build configurations.

This should be a .XML file, but github is stupid. Rename it to .xml. It has some filenames that only I use, so kitteh will have to change those.

@Kitteh6660 please take a look at this file. Apparently it works for @PwnzLPs and I've tested it for my personal Android/iOS builds. You may want to remove lines 34 through 41 which prevent the app from appearing in the 'recents' menu on android devices.

[coc-app.txt](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/102723/coc-app.txt)

**Comment by dragontamer8740** [comment]
P.S. Maybe you need to upgrade your Adobe AIR runtime - my APK comes with the runtime packaged. Yours might be out of date and the official APK's packaged without the runtime to reduce file size.

**Comment by PwnzLPs** [comment]
Yeah. I originally installed the original apk, so I know my AIR is good. I
checked first to see if that might had been it.

**Comment by Kitteh6660** [comment]
I'll continue to investigate the issues.

**Comment by fawce1** [comment]
Dear Dragontamer 
Thanks for the post and I will try it out as soon as possible and let you know what the outcome is.
Unfortunately the link doesn't seem to be working at the present and was wondering if you have another link that I could use.
Thanks again for the work you have done.

**Comment by dragontamer8740** [comment]
I've packed up all my build environment stuff:
FlashDevelop, libs, AIR, Flex:
https://mega.nz/#!bgY20bRD!6lEiUof-GS-Jkkhv3DGbSuHoc2OhvZjVqknpe7K2N0w

My packaging directory for the compiled AIR swf:
https://mega.nz/#!ChoUWRzQ!f4UqQu3gZkZapWIlPHft3vFywI6BjzgtlXEvjmAN3A0

You'll have to specify the path to the SDK's in flashdevelop, but after that it should be smooth sailing.

**Comment by Kitteh6660** [comment]
The APKs I compiled were captive AIR.

I'm still trying to figure out.

**Comment by dragontamer8740** [comment]
@Kitteh6660 Does my application XML file work? You should be able to use it as a drop-in replacement for yours, I think. Compare the settings in mine to the ones in yours - I have a couple unnecessary things, like disallowing rotation (a pet peeve of mine), but things like `renderMode` and especially the android `manifestAdditions` could be important. It could be yours is missing permissions for writing to the sd card (`android.permission.WRITE_EXTERNAL_STORAGE`). Also for some (very stupid) reason, Android requires internet access for AIR apps to run, so you'll need `android.permission.INTERNET`, too.
I used AIR 18.0, Adobe Flex SDK 4.6.0.
Apache Flex (newer versions) probably work, too.


```
<?xml version="1.0" encoding="utf-8" ?> 
<application xmlns="http://ns.adobe.com/air/application/3.7"> 
    <id>com.dragontamer8740.cocMod</id> 
    <versionNumber>0.9.4</versionNumber> 
    <filename>CoC-mod-droid</filename> 
    <name>CoC-Mod</name> 
     <description> 
        <text xml:lang="en">Corruption of Champions Mod</text> 
    </description> 
    <copyright>Copyright (c) 2015 Fenoxo/Kitteh6660</copyright> 
    <initialWindow> 
        <content>./CoC-AIR_1.0.2_mod_1.3.24b.swf</content>
        <fullScreen>true</fullScreen>
        <aspectRatio>landscape</aspectRatio>
        <autoOrients>false</autoOrients>
        <visible>true</visible>
        <renderMode>gpu</renderMode>
    </initialWindow>
    <icon> 
        <image29x29>icons/Icon_29.png</image29x29> 
        <image57x57>icons/Icon_57.png</image57x57> 
        <image512x512>icons/Icon_512.png</image512x512>  

    </icon> 
<android>
  <manifestAdditions>
          <![CDATA[
              <manifest android:installLocation="auto">
            <uses-permission android:name="android.permission.INTERNET"/>
			<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

                  <supports-screens android:normalScreens="true"/>
<!--                  <uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch"/>-->
                  <application android:enabled="true">
                      <activity android:excludeFromRecents="true">
                          <intent-filter>
                        <action android:name="android.intent.action.MAIN"/>
                        <category android:name="android.intent.category.LAUNCHER"/>
                          </intent-filter>
                      </activity>
                  </application>
              </manifest>
          ]]>
      </manifestAdditions>
    </android>
	<iPhone>
		<InfoAdditions>
			<![CDATA[
				<key>UIDeviceFamily</key>
				<array>
					<string>1</string>
					<string>2</string>
				</array>
				<key>UIViewControllerBasedStatusBarAppearance</key>
					<false/>
			]]>
		</InfoAdditions>
		<requestedDisplayResolution>high</requestedDisplayResolution>
	</iPhone>
</application>
```
