### ISSUE TITLE
Wrong function used in chooseEndowment

### ISSUE THREAD

**Issue by Mandarynek** [Kitteh6660/Corruption-of-Champions-Mod#15]
In CharCreation.as there is:
addButton(8, "Lots of Jizz", confirmEndowmentBigCock); 
what should be:
addButton(8, "Lots of Jizz", confirmEndowmentMessyOrgasms);

**Comment by Kitteh6660** [comment]
Closed via 7bc78da82d824acbff480e916be4076a728ee3b3
