### ISSUE TITLE
Typo in Kelt's Bad End

### ISSUE THREAD

**Issue by Teruah** [Kitteh6660/Corruption-of-Champions-Mod#157]
When submitting to Kelt at 100% submission, the Bad End text has a typo:

What she found was not what she expected. Two centaurs, wrapped in carnal bliss. Well, the hermaphrodite, at least, seemed wrapped in carnal bliss. She groaned worshipfully beneath her mate, whimpering and kneading her own watermelon sized breasts as the powerful male pumped her again and again with his oversized, equine cock. Even as the heroine watched, fascinated, the female centaur orgasmed explosively, shouting her satisfaction to the high heavens. If the thick puddle of juices and cumbelow......
 them were any judge, this must have been her last orgasm among many. She was almost half the size of her mate, and clearly savoring every thrust of his oversized cock into her distended equine cunt, lewdly thrusting back and begging him to cum inside her again.

"cumbelow" should likely be "cum below".

**Comment by Kitteh6660** [comment]
Fixed in 1.3.7.
