### ISSUE TITLE
Tel'Adre will NOT let me in.

### ISSUE THREAD

**Issue by PhantomKitty** [Kitteh6660/Corruption-of-Champions-Mod#161]
The first time I found Tel'Adre, I had a corruption of 32. Urta and Edryn wouldn't let me in, so I thought to myself "Hey, maybe Kitteh6660 made a change to the coding so that your corruption has to be even lower than in the original game."

But that doesn't seem to be the case. I've lowered my corruption to complete 0 through the use of Pure Honey and meditation with Jojo, and they STILL won't let me in. Each time I get a message about being too corrupt, and if I manage to "lower my corruption," to come back.

Am I missing something or doing something wrong?

**Comment by Kitteh6660** [comment]
Do you have any cocks possessed by Exgartuan?

**Comment by PhantomKitty** [comment]
Ah, that would be the problem. But how do I get rid of Exgartuan?

**Comment by Kitteh6660** [comment]
You can either get rid of your cocks with pink eggs or shrink cocks with Reducto.

**Comment by PhantomKitty** [comment]
Exgartuan has possessed my breasts (playing as a female PC at the moment). I figured out that the gargoyle can get rid of him/her/it. Thanks so much for your help!
