### ISSUE TITLE
Compile error in classes/classes/Scenes/Places/TelAdre.as

### ISSUE THREAD

**Issue by Ikazoid** [Kitteh6660/Corruption-of-Champions-Mod#163]
Hello, just starting to check things out here. I'm able to compile and run the un-modded version of CoC in my Linux environment, but with this mod I get the following error:

```
TelAdre.as(1977): col: 10 Error: Target of assignment must be a reference value.

		player.keyItemv1("Carpenter's Toolbox") -= nail;
		       ^
```

Seems like a simple issue of trying to assign a new value to an rvalue. From what I can tell it should instead say something like `player.addKeyValue(...)` with a negative number, but I'd like to have this verified before trying to tackle it myself as I'm pretty new to CoC's code and this mod's code.

**Comment by Ikazoid** [comment]
Additionally, if I fix the compilation error, I either get a Java out of memory exception or a garbage collection error when compiling. I've tried increasing the JVM memory allocation and I've tried both Windows and Linux environments, but it will still occur. Any tips?

I'll try to find an older version that can compile and see if I can figure out what the cause is, but if someone already knows a solution that would be great too.

**Comment by Ikazoid** [comment]
Ah, scratch that comment. It just turns out that 64-bit java is prone to issues with mxmlc; switching to 32-bit allows me to compile and run the debug build swf.

**Comment by dragontamer8740** [comment]
@Ikazoid that is correct, you want `player.addKeyValue`. Ormael did not test his code at all.

**Comment by Kitteh6660** [comment]
Fixed now.
