### ISSUE TITLE
Ormael did not try to build his source before uploading badly broken code

### ISSUE THREAD

**Issue by dragontamer8740** [Kitteh6660/Corruption-of-Champions-Mod#165]
The code is currently badly broken in many places.

Here's where all I remember - I forget what all I did to fix them though, and I've since tried to git pull and thus lost my changes.

1) Tel Ardre
Ormael forgot to define a stones variable anywhere.
Also, I think there was a problem buying nails.

2) Valkyrie shield drop table
Commit eb50a25b1abd6fe05ee8ac7e61d859224dca2282 used an undefined method for shield drops that was never implemented. It's an easy fix.

3) Perks not properly defined/included
I forget what all it was, but there was definitely a problem here.

4) Zebras in codex
the codex button for 'zebras' was broken (missing two quotation marks so that two variables passed to a function were seen as one function (e.g. this:)
myFunction should have 3 arguments passed:
`myFunction("var1","var2",var3)`

but instead, it was like this.
`myFunction("var1,var2",var3)`

5) maximum lust and demonScore
the place where he's checking for demonScore >=4 does not have demonScore in it's scope.

6) Phylla
Phylla's supposed to be able to get you stones now but the same problem with the undefined stones variable is here.

Even after that, try starting a new game with the game when I finally was able to make it compile.

https://dl.dropboxusercontent.com/u/74519404/CoC-STANDALONE_0.9.4_mod1.3.7_v2.swf

I hope someone can either make Ormael test his own code before committing badly broken crap, or teach him how to install flash builder.

**Comment by Kitteh6660** [comment]
Fortunately, I've managed to fix the issues with the release of version 1.3.8. It includes code fixes.
