### ISSUE TITLE
Non-compiling (broken) or untested code should NOT go in the master branch

### ISSUE THREAD

**Issue by dragontamer8740** [Kitteh6660/Corruption-of-Champions-Mod#169]
Recently Ormael has been making a lot of commits, which is all well and good (more content), but at the same time, I can tell he clearly does not try to compile his code or test his code before he commits.

Broken code should not be committed (or have pull requests accepted) until tested and fixed, or if it's going to be committed anyway, it should be on a branch besides master, so people who try to compile the source can actually do so without spending a half hour looking for functions that were never defined, improper use of undefined-in-scope objects, and so on.

**Comment by Kitteh6660** [comment]
It should be resolved now.
