### ISSUE TITLE
Re entering prison

### ISSUE THREAD

**Issue by kalleangka** [Kitteh6660/Corruption-of-Champions-Mod#17]
Hey again, notes when you try to re enter the prison from the back ally at bazaar the game kind got stuck you cant prees next or nothing, nether text or any other button can or are visible exept for the next button, may also add it when i done a question to Elly (the one that you need to get fuck by 5 monster)

**Comment by Kitteh6660** [comment]
Fixed via a0ef2144a53c5bac8ff7ed8598d0369f60fdc58e
