### ISSUE TITLE
Simple Text Error

### ISSUE THREAD

**Issue by PwnzLPs** [Kitteh6660/Corruption-of-Champions-Mod#171]
I don't know if I'm the only one that has seen this (hopefully...) but, I have a male Ember, and for some reason, there's a text bug.

“But” what, you reply? “Since you seem to be so worried about me; there is a thing you could do for me.” You ask him what that might? Ember averts his eyes and rubs the back of his neck. “Stay,” **she** utters quietly.

**Comment by EllaKreal** [comment]
I was looking into some outstanding Ember stuff and fixed this while I was in the ember code.

**Comment by Kitteh6660** [comment]
Should be fixed in one of the pull requests. This will be in 1.3.9 if I ever compile it.
