### ISSUE TITLE
Build Error with HairDye.as

### ISSUE THREAD

**Issue by hatternumber0** [Kitteh6660/Corruption-of-Champions-Mod#177]
I'm having trouble testing the project in FlashDevelop on version 1.3.8. I'm getting the error:

> C:\Users\Name\Downloads\CoC\CoC Source\Corruption-of-Champions-Mod-0.9.4_mod_1.3.8\classes\classes\Items\Consumables\HairDye.as(12): col: 78 Error: Parameter initializer unknown or is not a compile-time constant.
> 		public function HairDye(id:String, color:String, value:int = ConsumableLib.DEFAULT_VALUE)

Google tells me it's probably a problem with HairDye.as being compiled before it knows what ConsumableLib.DEFAULT_VALUE is.

I'm using the base source code and haven't edited anything.

Any ideas on what i've done wrong?

**Comment by Kitteh6660** [comment]
I've updated the code to 1.3.9, which should work. Let me know if you still have issues.

**Comment by hatternumber0** [comment]
Unfortunatly not. Looks like its a problem on my end. I'll try a different program later and see if that helps.
