### ISSUE TITLE
"Event tester" and other debug dialogs missing

### ISSUE THREAD

**Issue by dragontamer8740** [Kitteh6660/Corruption-of-Champions-Mod#179]
See title. The event tester and other dialogs are missing from new builds. I used them a lot - please bring them back!

**Comment by Kitteh6660** [comment]
The reason I disabled these is because they relied on Markdown. I've completely removed showdown.as from CoC and with it, Markdown.

If you look at one of the version changes on change log, you can see the debug options are removed.

I might bring them back although not everything will be the same.

**Comment by Kitteh6660** [comment]
Should be returned in 1.3.12 although it's not exactly the same.
