### ISSUE TITLE
Bad ends

### ISSUE THREAD

**Issue by DuskFantail** [Kitteh6660/Corruption-of-Champions-Mod#18]
Whenever I get a bad end. The continue option Goes to a black screen
![coc](https://cloud.githubusercontent.com/assets/12084250/7448326/39cbea32-f25a-11e4-850e-155f790da4c5.png)

**Comment by DuskFantail** [comment]
Thanks Kitteh6660

**Comment by Kitteh6660** [comment]
Fixed via a0ef2144a53c5bac8ff7ed8598d0369f60fdc58e
