### ISSUE TITLE
Bog-Lizan Rogue-Spar-Use Dick Bug

### ISSUE THREAD

**Issue by danigam** [Kitteh6660/Corruption-of-Champions-Mod#180]
Like a snake his tongue slithers from his lips and begins to encircle your !Unknown subject in “cockBiggest”!, the moves on until it has formed at least two coils around each of your cocks. The surprisingly firm snake like organ massages all of your dicks in firm rhythmic strokes. It feels like a family of hot, wet snakes are writhing around one of your pricks, squeezing with practiced ease as saliva trickles down your shafts. You groan as you feel his spit drip down your duo of baseball-sized balls and legs.

**Comment by Kitteh6660** [comment]
I've looked around and there's no issue. I suggest you download the latest version.
