### ISSUE TITLE
Camp Attacks

### ISSUE THREAD

**Issue by Hizorian** [Kitteh6660/Corruption-of-Champions-Mod#181]
Been thinking about adding in camp attacks. That victory or defeat will depend on camp defenses and who is guarding, plus player strength. But the magnitude of the attack will depend on the defenses. 

Any help on how I should go about this?

**Comment by Hizorian** [comment]
Right now I could use some help with a few things. How would I code a probability chance of an attack happening when you wake up or come back from exploration?

-Sorry new to ActionScript.

**Comment by Kitteh6660** [comment]
Use rand() function to determine a random number between 0 (inclusive) and x (exclusive)
