### ISSUE TITLE
Found 3 iisues.

### ISSUE THREAD

**Issue by mazfaz** [Kitteh6660/Corruption-of-Champions-Mod#182]
1. Game dont recognize SucubiMilk/PureSucubiM when trying to grow Katherine's brests biger.
2. When using debug chit in volunteering to the sand witches u wakes up in the Factory.
3. After corrupting Kelt u can't corrupt the farm.
(4.) Its easy to grow penis but hard to grow balls.

**Comment by Kitteh6660** [comment]
1. You can't give tainted succubi milk to Katherine, only the pure variant.
2. This will be resolved in 1.3.16.
3. I don't see anything wrong. You'll need at least 70 corruption. Did you disable prompt?
4. It's simple. Just get succubi's delight.
