### ISSUE TITLE
[BUG or sillyEditor] Corruption Tolerance Perk locking out Amily (v1.3.14)

### ISSUE THREAD

**Issue by hatternumber0** [Kitteh6660/Corruption-of-Champions-Mod#186]
Having a Corruption Tolerance level of >14 and a corruption level of >25 can lock out Amily. I'm not actually certain that level can be achieved legitimately or just with the save editor, so could just be player shenanigans.

In AmilyScene.as:

if (flags[kFLAGS.AMILY_CORRUPT_FLIPOUT] == 0 && flags[kFLAGS.AMILY_MET] > 0 && player.cor > 25 + player.corruptionTolerance()) {
   meetAmilyAsACorruptAsshat();
   return;
}
//CORRUPTIONZ
if (flags[kFLAGS.AMILY_CORRUPT_FLIPOUT] > 0 && player.cor > 25) {
   //Cook amily a snack if player doesnt have key item for it.
   if (player.hasKeyItem("Potent Mixture") < 0 && flags[kFLAGS.UNKNOWN_FLAG_NUMBER_00170] < 3) {
      cookAmilyASnack();
      return;
   }
   //Has snacks!
   else {
      if (flags[kFLAGS.UNKNOWN_FLAG_NUMBER_00170] == 0) stalkingZeAmiliez();
      else if (flags[kFLAGS.UNKNOWN_FLAG_NUMBER_00170] == 1) stalkingZeAmiliez2();
      else if (flags[kFLAGS.UNKNOWN_FLAG_NUMBER_00170] == 2) stalkingZeAmiliez3();
      else rapeCorruptAmily4Meeting();
      return;
   }
}

**Comment by Darth-Cthoras** [comment]
Unless this is confirmed as an issue with the latest 1.3.16 (as of typing), I wouldn't waste time on patching it at this point, given we're already two versions ahead and looking forward. Will check the code later if I have time and figure out a fix, assuming this isn't intentional and legitimately possible.

**Comment by hatternumber0** [comment]
Ah. My bad. Didn't notice it was an old version. Just checked with v1.3.16 and it still happens.

**Comment by Darth-Cthoras** [comment]
Thanks for checking. Update the thread title with 1.3.16 to ensure it's noticed as a bug needing fixing, then - old versions will be ignored or put on the back burner. I'll go examine the code myself...

**Comment by hatternumber0** [comment]
An example. Lets say your corruption level is 40, you haven't met Amily as a corrupt and your tolerance perk level is 20.

According to the code when exploring the ruins, you can only activate the meetAmilyAsACorruptAsshat() scene if player.cor > 25 + player.corruptionTolerance(). Which would need your corruption to be over 125, which isn't achievable.

Code moves onto the next statement. Which lets you corrupt amily. It only activates however if the players corruption is over 25 and you have done the meetAmilyAsACorruptAsshat() scene which is locked out.

The next statement will activate if the players corruption is over 25. You'll find nothing in the ruins and go back to camp.

As long as the player is locked out of the meetAmilyAsACorruptAsshat() scene, they can never corrupt Amily and just endlessly cycle an empty ruins.

**Comment by Darth-Cthoras** [comment]
Oh, I see. Well, I somehow completely overlooked that, 'and' misunderstood how the system functioned. Still getting used to ActionScript - I worked with BASIC, QBasic, VisualBASIC, and NWScript on and off for a couple decades - and it didn't help I was looking at this right before bed. Thanks for the explanation.
