### ISSUE TITLE
Urta weight gain

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#191]
I'm not sure if this was intentional or not (so potentially sorry for wasting your time), but even in non-survival mode, giving Urta an under-the-table BJ now increases thickness by +2.

**Comment by Kitteh6660** [comment]
Actually, the weight gain is intended. I haven't touched the code aside from integrating hunger refilling.

In non-survival mode, you gain weight due to the lack of hunger system.
