### ISSUE TITLE
Rathazul potentially locked out in current build

### ISSUE THREAD

**Issue by wyvvern** [Kitteh6660/Corruption-of-Champions-Mod#195]
I usually recruit Rath by saving up 150 gems then finding him and buying three dyes all at once. There's an error in the current build that prevents his recruitment under these circumstances:

On line 249 in Rathazul.as the line:

totalOffers += pCounter;

needs to be:

totalOffers++;

pCounter is used to track the # of items the player has available to purify. If he's offering dyes, the offer count should be increased, not have pCounter added to it. If the player has no items in their inventory that he can purify, pCounter will be zero, and they'll be thrown to camp and out of the encounter even if they can afford to buy the dye by the code:

if (totalOffers == 0 && spoken) {
    doNext(camp.returnToCampUseOneHour);
    return true;
}

on lines 302-5.

**Comment by Darth-Cthoras** [comment]
Just tested with a New Game+ and no items available for purification in inventory. Rathazul appeared, offered dyes, I bought three on the spot, he asked, and I moved him to camp.

**Comment by wyvvern** [comment]
Try it in new game. This only triggers if there's NO other offers available and certain status effects and flags are zero. (player.statusEffectv2(StatusEffects.MetRathazul) needs to be < 4 for example)

This WILL throw the player to camp if the player has less than 100 gems && more than 50 gems and no other offers are available, and it shouldn't.

Just read the code.

The logic makes zero sense. The number of items the player has available to be purified has nothing at all to do with the ability to buy dye. The gem check at the start of the block controls that. As with all the other code blocks that check the player simply has enough cash available the total offer count needs to be increased, not have pCounter added to it.

**Comment by Kitteh6660** [comment]
Looked into the issues and hopefully this will be fixed in 1.3.18.
