### ISSUE TITLE
Derpy forgoten last detail for Salamander TF

### ISSUE THREAD

**Issue by Ormael** [Kitteh6660/Corruption-of-Champions-Mod#208]
Well I tried find it in your new code but...I can't.
Thing is lustzerk similar like berzerk need to lower one of defenses in this case lust one.
In old code in engineCore was function lustPercent()
there between 2 last lines that was looking like that
        lust = Math.round(lust);
	return lust;
I added line:
        if (player.findStatusAffect(StatusAffects.Lustzerking) >= 0) lust = 100; (which ofc was to make player set lust resistance at 0% till end of fight) - so I not know were this part of code went after refactoring but you need to add this lane there to make lustzerk properly lower lust resistance.

**Comment by Kitteh6660** [comment]
It's all right. However, I'll tweak lustserk to halve the lust resistance as there are only few ways to increase maximum lust.

**Comment by Ormael** [comment]
Ok then I think I didn't forgot anything else on this TF. Time for me to perfect my gorgon one TF ^^
