### ISSUE TITLE
[BUG] Lethice? Dialogue (1.3.21)

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#210]
By the time I was done killing the Minotaur King and Excellia, I had 100 Libido and 100 Corruption. However, the dialogue directly following the kill was blank, leaving me solely with FIGHT and CONSORT buttons below an empty screen, without any lead-up, warnings, or explanations.

**Comment by Kitteh6660** [comment]
I don't know. Maybe you could try to make a pull request.
