### ISSUE TITLE
[BUG?] Lethice Consort

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#212]
Currently, choosing Consort at the battle with Lethice automatically gives you General Achievement - You Bastard... which, when I finished the game and returned to the main menu, stated as its description:

You Bastard: Unlocked - Remove cocks from at least seven dedickable NPCs. Take that, dedickers! - Shadow Achievement

Bug or intentional? Logically, to me, that should have been something about how you became the Demon Champion.

**Comment by Kitteh6660** [comment]
The achievement description is a bit outdated and will be changed.
