### ISSUE TITLE
Tamani "Buttfuck" option broken

### ISSUE THREAD

**Issue by SpearM3064** [Kitteh6660/Corruption-of-Champions-Mod#216]
Looks like some of the changes to Tamani's code have broken this option.  All you get is a blank screen, with the options "fuck", "buttfuck", and "leave" still on-screen.  ("fuck" and "leave" work fine; only "buttfuck" is broken.)

**Comment by Darth-Cthoras** [comment]
Which version are you seeing this problem in? Looking the code over in 1.3.21, I don't see a problem, nor am I running across this error in said version...

Yep. Just tested, it worked fine for me in 1.3.21.

**Comment by SpearM3064** [comment]
It's version 1.3.21.  I went back to the same character and confirmed... I can click on Buttfuck until the cows come home, and not a damn thing happens but a blank screen.  But it's only with that one character... I switched to a different male character (created a long time ago... unmodified version 0.9.4), and it worked.  So I tried it with a different male character.  Again, it worked.  So I switched to *another* character (a herm)... blank screen, didn't work.

For some reason, it appears to happen only with specific characters.  In case someone wants to try to analyze the save files to figure out why, I tried to attach a ZIP file containing the two characters for which the Buttfuck option does NOT work, but GitHub basically told me "We don't support ZIP.  Try again with a ZIP."  So, here's a link to the ZIP file in Dropbox.  (I placed them in slots 13 and 14.)

https://www.dropbox.com/s/gji3q1rwcshl948/CoC_chars.zip?dl=0

**Comment by Darth-Cthoras** [comment]
I'll take a look at it, but no promises I can find out where it's borking up, if it's failing only for specific characters. The best bet, in my opinion, would probably be to convert a working save and a broken save to raw format and do a cross-check comparison. I'll see what can be done.

**Comment by SpearM3064** [comment]
Yeah, I'm a programmer too (though my programming skills are VERY rusty at this point... it's been 15 years since I used them for anything other than personal projects).  As soon as I figured out that it was only with specific characters, I thought "uh-oh... this won't be an easy one to winnow out."

**Comment by Darth-Cthoras** [comment]
Still no luck with pinning down a specific culprit, unfortunately, but that might be cause I'm so unfamiliar with the languages / code structure used here - likely I'm overlooking something. I was raised on BASIC and QBasic, on my IBM PS/50 waaaay back in the day, but I've never had formal training in any other languages, though I did spend a few years mucking with NWScript off and on, as well as modding Baldur's Gate. So this ActionScript is new to me, but not so far removed I can't make (some) sense of it, for the most part. Learning as I go. ^_^ I hope to be able to make some major contributions, in time, but for now stuck on minor tasks like this... and judging by this one, failing miserably >_<;

**Comment by Killette2** [comment]
I think this happens when your dick is too big.

**Comment by SpearM3064** [comment]
That was exactly the problem.  The button was not properly deactivating.
