### ISSUE TITLE
Bimbo Jojo

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#219]
I'm not seeing any way to debimbo Jojo, which means missing out on Jojo's perks in that playthrough unless you manage to get them pre-Bimbo. Is there going to be a method, or did I just not look hard enough and overlook it? I had Bimbo drinks in my Stash when I ascended, and very quickly Jojo wound up a bimbo before I could learn anything from him.

**Comment by Kitteh6660** [comment]
There will eventually be an option to debimbo her though it'll only remove her bimbo personality and her sexuality will stay.

**Comment by Darth-Cthoras** [comment]
Good to hear, thanks! =) Now I can go ahead and ascend without worries.

**Comment by Kitteh6660** [comment]
I've looked into the code and the counter doesn't tick if you have bimbo liqueur before you invite Jojo. It starts ticking if you invite him to your camp. So you can ascend and not have to worry.

**Comment by Darth-Cthoras** [comment]
Yeah, that's what happened. I had BL's in storage and ascended. He joined my camp, and some days later the event proc'd and POOF, bimbo jojo. So the trick is to just remove BL's from storage before inviting him to camp.
