### ISSUE TITLE
[Q&A] GitHub Forks Updating

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#223]
Prior to wanting to help make CoC all that it can be, I never used GitHub or forks before, since all my coding was just done by myself. Is it important to keep the fork up-to-date with this repository, and if so, how can I ensure my fork remains so? I don't want to accidentally push an outdated file and wind up reverting a newer file.

**Comment by Kitteh6660** [comment]
Yes, it's important to keep the fork up to date with repository.

In order to do so, if you have Github for Windows, you can click on the button that says update from fork.

**Comment by Darth-Cthoras** [comment]
Thanks =) I'll go download that, then.

**Comment by Darth-Cthoras** [comment]
Actually, it just occurred to me - there isn't a way to do it through the site by simply doing some sort of reverse pull from repo to fork? Sounds counterintuitive if so, though that might just be inexperience talking.

**Comment by herp-a-derp** [comment]
You can open a pull request from the upstream (in this case `Kitteh6660/Corruption-of-Champions-Mod`) to your fork, entirely through the web-site, though it's not exactly straight forward.

You can also do it with git on the CLI, or via TortoiseGit. Merging across forks is a core component of the git workflow, it's a very well supported operation.

Roughly speaking, from your repository home, click "New Pull Request". You may then have to swap the targets in the "Comparing changes" dialog. You want to set `Kitteh6660/Corruption-of-Champions-Mod` as the "head fork". You may need to click the "compare across forks" link button, depending on what mode things come up in.

**Comment by Darth-Cthoras** [comment]
Oh, thank you for that explanation. I'll be sure to check that prior to working, in the future. Don't worry, I won't be a newbie forever =) Bear with it, I learn quick!

**Comment by herp-a-derp** [comment]
Git is.... very confusing. Particularly when you want to do complex things.

In general, you can assume that whatever you want to do is possible, but you may need to go on an archaeological expedition through some byzantine man pages to figure out how do do whatever you're looking to do.
