### ISSUE TITLE
[BUG?] Recruiting Mitzi in D3

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#224]
Does having [kFLAGS.MITZI_RECRUITED] = 1 actually 'do' anything in game? It gets set if you recruit Mitzi after defeating the drider/incubus in D3 (Lethice's palace), but other than that, I'm not finding any info on this NPC. The PC tells her to go wait outside, but I've never found her again - I assume she just runs away?

**Comment by Kitteh6660** [comment]
Mitzi isn't implemented yet.

It's one of the possibilities for post-game however. If someone writes.

**Comment by Darth-Cthoras** [comment]
So there's no data on this NPC at all? No character notes or anything, personality, corruption, tastes...? Hm. A clean slate if so, though I assume from where she's found that massive corruption would be implied.

**Comment by Kitteh6660** [comment]
I've left a card on Trello if you want.
