### ISSUE TITLE
[Perma-Perks] Corrupt / Enlightened Nine-Tails mutually exclusive? Ninth tail problems

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#226]
Unsure if this's a bug or intentional. Having just made Enlightened Nine-Tails permanent, I then proceeded to try for Corrupted Nine-Tails in the ascended playthrough ... and wound up blowing through probably four, five hundred mystic fox jewels in debug mode when the ninth tail was refusing to appear, by holding down 1 to use item / press next. Even went through Fox Jewels until the meditate / enhance hint came up and spammed a ton more Mystic Fox Jewels - no go, no ninth tail, and no Terror / Corrupted Foxfire.

**Comment by Darth-Cthoras** [comment]
....also, I noticed during my fights through the last playthrough, that the Perma'd Enlightened Nine-Tails perk was NOT restoring 1-5 Fatigue per round in combat as it should have, or at least wasn't during the final boss fights of Lethice's palace, which is when I noticed it as I was running low on available fatigue.

**Comment by Kitteh6660** [comment]
Going to be fixed in 1.3.23.

**Comment by Darth-Cthoras** [comment]
As a heads up, Corrupted Nine-Tails is likely to also have the same fatigue-restoring issue as the Enlightened version, so that should probably get checked as well.
