### ISSUE TITLE
[Large Feature Request] Alternate interface for dealing with large numbers of options

### ISSUE THREAD

**Issue by PowerOfVoid** [Kitteh6660/Corruption-of-Champions-Mod#23]
The CoC "button" interface does not handle selection from among large numbers of options well. It's blatant once you have 16 options, but it starts feeling a bit clunky once you get beyond about 5.

I'm not sure how viable this is:

![buttonslider](https://cloud.githubusercontent.com/assets/3876355/7465518/61db1bde-f29f-11e4-9789-fe2641de0d5a.png)

**Comment by Kitteh6660** [comment]
Third row was introduced in one of the updates.

Unfortunately, implementing something like that would require a massive change to interface system.

It currently has two uses: For cleaner dungeon layout and for multi-page menus. In multi-page menus, the 5th column is dedicated for Next, Previous, and Back. It allowed for infinite number of pages.

I'll probably change the next, previous, and back buttons to be a bit easier to distinguish.

Dungeon buttons layout
![image](http://i1061.photobucket.com/albums/t469/Kitteh6660/Corruption%20of%20Champions/Buttonslayout_zpsc757ef5b.png)

Multi-page buttons layout
![image2](http://i1061.photobucket.com/albums/t469/Kitteh6660/Corruption%20of%20Champions/MultipageMenu_zpsgmokeath.png)

**Comment by PowerOfVoid** [comment]
Is your concern that implementing the new system would be hard in and of itself, or that converting everything to use it would be hard?

If the latter, something that could be used to ease a transition would be to allow content to choose whether to use the "new" style or the "old" style, so content could be updated to use the new system as coders find it convenient.

... or at least, I think that would work.

**Comment by PowerOfVoid** [comment]
Also, allowing buttons to be colored seems relatively simple.

**Comment by Kitteh6660** [comment]
The menu is fine as it is, especially with each page holding up to 12 buttons. Three of the button slots, on the right-most column, is dedicated for navigation.
