### ISSUE TITLE
permanent Marae's perks 

### ISSUE THREAD

**Issue by Linulanielly** [Kitteh6660/Corruption-of-Champions-Mod#233]
After ascension I have made Marar's stud permanent perk. But in new gameplay I managed to get second Marae's Stud perk (there were 2 perks in my perk list).
Probably findPerk method in Creature.as file should now look at perkv4 array too.

And also in MaraeScene for herms there are no codes to get Buttslut perk... Is it how it should to be?

**Comment by Kitteh6660** [comment]
Made some code changes so it's no longer possible to get duplicate perks.

And for Buttslut perk, the changes will come into next patch to make it possible to get the perk as herm.
