### ISSUE TITLE
Permable perks

### ISSUE THREAD

**Issue by 19jind** [Kitteh6660/Corruption-of-Champions-Mod#236]
Excuse me, but in the permable perks menu, after ascension, there is no back button to leave the menu. Where the back button is usually is covered by Raphael's misdirection perk.

**Comment by Kitteh6660** [comment]
Send me the save and I'll look into fixing.

**Comment by 19jind** [comment]
Well, if it's a problem with the save, then there are probably a lot of things that need fixing. (I use CoCed.) That's probably where the issue lies, but here anyway. (Save really broken.) Thank you in advance, and sorry for wasting your time.

[CoC_14.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/311210/CoC_14.zip)
