### ISSUE TITLE
COC Crashes on Android Zenpad 

### ISSUE THREAD

**Issue by fawce1** [Kitteh6660/Corruption-of-Champions-Mod#237]
Android refuses to run the programme. Will install and open but just closes straight away. Ran OK on my old tablet on 4.4 but not on the new one. Would be great if you have any suggestions that could help me with this problem. Runs the original game fine o at my wit's end 
Thanks

**Comment by Kitteh6660** [comment]
Grab the newest versions at: https://github.com/Hexxah/CoC-MOD-Android-Build

Hopefully it should be solved.
