### ISSUE TITLE
[Bug] Gem Count does not change

### ISSUE THREAD

**Issue by JackDoherty** [Kitteh6660/Corruption-of-Champions-Mod#238]
Gem count does not change no matter what I do, sell things, or kill monsters. I cannot gain gems, it's just stuck at zero. I have deleted and reinstalled the game and reloaded my file but this did nothing. If I start a new file, they do not have the issue, but my old files still have it

**Comment by Kitteh6660** [comment]
Send me the save and I'll look into it.

**Comment by JackDoherty** [comment]
Here
[Save.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/310745/Save.zip)

**Comment by Kitteh6660** [comment]
Found the issue and this will be fixed in 1.3.24.
