### ISSUE TITLE
Katherine-Urta Drunk Scene Issue?

### ISSUE THREAD

**Issue by dartonus** [Kitteh6660/Corruption-of-Champions-Mod#243]
The scene for having Katherine Drink and then See Urta includes the line "On the other hand everyone enjoys an orgy.", but does not display the Orgy button. Checking the Katherine.as file the culprit is that the button is placed in the if(submissiveness() < 3) block.

**Comment by DullDanger** [comment]
... and https://wiki.smutosaur.us/CoC/Katherine says "Requires submissiveness of 3+"
