### ISSUE TITLE
Mander Tail Slap applied to all tails that get a Tail Whip

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#248]
Due to a missing `break;` after `addButton(button++, "Tail Whip", [...]);` the **Tail Slap**-attack gets applied to all tails that grant a **Tail Whip**, but Manders only get their Tail Slap. I doubt, that this was intended. :)

In my patch I'll move the Tail Slap code above the other `case TAIL_TYPE_XYZ:` and leave the `break;` commented out, so manders get both attacks and others only get Tail Whip as intended.

branch + PR follows

**Comment by Stadler76** [comment]
Created PR: #249

**Comment by Stadler76** [comment]
Although I think, this goes without asking, I'll send Savin a PM, if my PR is acceptable.

**Comment by Kitteh6660** [comment]
Merged and will be fixed in 1.3.24c.
