### ISSUE TITLE
[Feature] Deprecate EYES_FOUR_SPIDER_EYES in favor of eyeCount (new property)?

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#250]
While writing on my patch and adding new EYE_TYPEs. I started considering if we could allow multiple races to have four eyes. At present this wouldn't be needed, but in the future, if more EYE_TYPEs are being added I think, this would be nice to have. What do you think?

At present I'm not working on it, but heres how I probably would implement it:
- Creature.as:

``` as3
        public var eyeCount:Number = 2;
        // [...]
        // acting similar to isTaur(). Dunno, if we really need a method for this.
        public function hasSpiderEyes():Boolean
        {
            return eyeCount > 2;
        }
```
- Replace `player.eyeType = EYES_FOUR_SPIDER_EYES;` with `player.eyeCount = 4;`
- Replace `if (player.eyeType == EYES_FOUR_SPIDER_EYES)` with `if (player.eyeCount > 2)` or `if (player.hasSpiderEyes())`
- Add `player.eyeCount = 2;` below every occurrence of `player.eyeType = EYES_HUMAN`.
- Consider, which TF should retain eyeCount > 2 and which shouldn't.

PS: Should I suggest this over at your Trello-page?

**Comment by anonymph** [comment]
I would recommend doing this the opposite way around. Have a method/accessor to determine the amount of eyes off of the eye type. Something like this:
```actionscript3
public function get eyeCount ():Number {
    if (eyeType == EYES_FOUR_SPIDER_EYES || eyeType == EYES_FOUR_WHATEVER)
        return 4;
    else
        return 2;
}
```
This would be much cleaner, as `player.eyeCount` would derive directly from `player.eyeType`.

**Comment by Stadler76** [comment]
Nope, that would be useless to implement. Adding EYES_FOUR_XXX for every dawn eyeType is somewhat bloated.
Note, that I intend to implement an approach similar to tauric lower body. Don't forget, that taurs have four legs, but they're not always hoofed.
I intend to allow different races to have an extra set of their typical eyes. Note, that cats for example already have something like that implemented. The face description includes the eyes description, And the four spider eyes description simply states, that you have a second set of eyes on your forehead:
```as3
			if (player.eyeType == EYES_FOUR_SPIDER_EYES) 
				outputText("  In addition to your primary two eyes, you have a second, smaller pair on your forehead.", false);
```
Imagine a dragon with four dragon eyes or a sand trap with four black sand trap eyes and so on.

Actually I intend to add a new solution to Rathazul's Alchemy tab.
The name would be something, like **Oculum Arachnae** acting similar to Taurinum.

**Comment by Stadler76** [comment]
Oh another explanation for my reasoning. Take a look at the lowerBody stuff in appearanceDefs.as:
```as3
// lowerBody
public static const LOWER_BODY_TYPE_HUMAN:int                                       =   0;
public static const LOWER_BODY_TYPE_HOOFED:int                                      =   1;
public static const LOWER_BODY_TYPE_DOG:int                                         =   2;
public static const LOWER_BODY_TYPE_NAGA:int                                        =   3;
public static const LOWER_BODY_TYPE_CENTAUR:int                                     =   4; // DEPRECATED, use LOWER_BODY_TYPE_HOOFED and legCount=4
public static const LOWER_BODY_TYPE_DEMONIC_HIGH_HEELS:int                          =   5;
public static const LOWER_BODY_TYPE_DEMONIC_CLAWS:int                               =   6;
public static const LOWER_BODY_TYPE_BEE:int                                         =   7;
public static const LOWER_BODY_TYPE_GOO:int                                         =   8;
public static const LOWER_BODY_TYPE_CAT:int                                         =   9;
public static const LOWER_BODY_TYPE_LIZARD:int                                      =  10;
public static const LOWER_BODY_TYPE_PONY:int                                        =  11;
public static const LOWER_BODY_TYPE_BUNNY:int                                       =  12;
public static const LOWER_BODY_TYPE_HARPY:int                                       =  13;
public static const LOWER_BODY_TYPE_KANGAROO:int                                    =  14;
public static const LOWER_BODY_TYPE_CHITINOUS_SPIDER_LEGS:int                       =  15;
public static const LOWER_BODY_TYPE_DRIDER_LOWER_BODY:int                           =  16;
public static const LOWER_BODY_TYPE_FOX:int                                         =  17;
public static const LOWER_BODY_TYPE_DRAGON:int                                      =  18;
public static const LOWER_BODY_TYPE_RACCOON:int                                     =  19;
public static const LOWER_BODY_TYPE_FERRET:int                                      =  20;
public static const LOWER_BODY_TYPE_CLOVEN_HOOFED:int                               =  21;
//public static const LOWER_BODY_TYPE_RHINO:int                                       =  22;
public static const LOWER_BODY_TYPE_ECHIDNA:int                                     =  23;
public static const LOWER_BODY_TYPE_DEERTAUR:int                                    =  24; // DEPRECATED, use LOWER_BODY_TYPE_CLOVEN_HOOFED and legCount=4
public static const LOWER_BODY_TYPE_SALAMANDER:int                                  =  25;
```
As you can see, two lower body types have been deprecated in favor of using `legCount` or `Creature:isTaur()`.
I just don't want to reintroduce such an unwanted behaviour for eyes. Hence why I intend to split that up into two creature-/player-properties actually I even intend to add EYES_CAT to the list.
Aaand: What would happen, if you want 6-eyed or even 8-eyed species? Add yet another eye type to every damn existing eye type?
The result would be something, like
```as3
// eyeType
public static const EYES_HUMAN:int                                                  =   0;
public static const EYES_FOUR_SPIDER_EYES:int                                       =   1;
public static const EYES_BLACK_EYES_SAND_TRAP:int                                   =   2;
public static const EYES_LIZARD:int                                                 =   3;
public static const EYES_DRAGON:int                                                 =   4; // Slightly different description/TF and *maybe* in the future(!) grant different perks/combat abilities
public static const EYES_BASILISK:int                                               =   5;
public static const EYES_FOUR_BASILISK_EYES:int                                     =   6;
public static const EYES_SIX_BASILISK_EYES:int                                      =   7;
public static const EYES_EIGHT_BASILISK_EYES:int                                    =   8;
public static const EYES_FOUR_HUMAN_EYES:int                                        =   9;
public static const EYES_SIX_HUMAN_EYES:int                                         =   10;
public static const EYES_EIGHT_HUMAN_EYES:int                                       =   11;
public static const EYES_FOUR_SAND_TRAP_EYES:int                                    =   12;
public static const EYES_SIX_SAND_TRAP_EYES:int                                     =   13;
public static const EYES_EIGHT_HSAND_TRAP_EYES:int                                  =   14;
public static const EYES_FOUR_LIZARD_EYES:int                                       =   15;
public static const EYES_SIX_LIZARD_EYES:int                                        =   16;
public static const EYES_EIGHT_LIZARD_EYES:int                                      =   17;
public static const EYES_FOUR_DRAGON_EYES:int                                       =   18;
public static const EYES_SIX_DRAGON_EYES:int                                        =   19;
public static const EYES_EIGHT_DRAGON_EYES:int                                      =   20;
public static const EYES_CAT:int                                                    =   21;
public static const EYES_FOUR_CAT_EYES:int                                          =   22;
public static const EYES_SIX_CAT_EYES:int                                           =   23;
public static const EYES_EIGHT_CAT_EYES:int                                         =   24;
```
By all means, I don't intend to do this for the sake of not adding a new creature-/player-property.

**Comment by anonymph** [comment]
Ah, yeah, if you intend for an arbitrary combination of eye types and eye numbers, it's absolutely better to add a new variable. 

Your replacements (and `hasSpiderEyes()`) seems misguided in that case, though. It would add a bunch of weird arbitrary logic, which we would need to clean up, the moment we decide to fuck around with many eyed (non-arachnid) monstrosities. (**Oculum Arachnae** is a great idea!)

Wouldn't it work nicer if we replaced:
- `EYES_FOUR_SPIDER_EYES` with `EYES_SPIDER`.
- `player.eyeType = EYES_FOUR_SPIDER_EYES;` with `player.eyeType = EYES_SPIDER; player.eyeCount = 4;`.
- `if (player.eyeType == EYES_FOUR_SPIDER_EYES)` with `if (player.eyeType == EYES_SPIDER && player.eyeCount == 4)`.

This way we are ready to support those arbitrary combinations already.

_PS. Would it be possible to label this issue with "Enhancement"?_

**Comment by Stadler76** [comment]
Actually hasSpiderEyes() is the equivalent of isTaur() but for eyes. If you have a more fitting name for a function, that returns true if your eyeCount is greater, than 2. Then tell me.

Look closely at the TF and at the player appearance for EYES_FOUR_SPIDER_EYES. I guess: EYES_FOUR_EYES would describe this better. So actually: when you are a spider-morph or a drider you'll have 4 human eyes. Meaning: They don't change in color or shape at all.

To make a long story short: For driders and spiders I'd probably tend to go for the following in the eye TF:
```as3
if (eyeType != EYES_HUMAN || eyeCount < 4) {
	if (eyeType != EYES_HUMAN) {
		outputText("\n\nYou eyes revert to be human eyes.");
		eyeType = EYES_HUMAN;
		if (eyeCount < 4) {
			outputText("  In addition to that, you now have an extra set of eyes[...]");
			eyeCount = 4;
		}
	} else /* if (eyeType == EYES_HUMAN && eyeCount < 4) */ {
		outputText("\n\nYou now have an extra set of eyes[...]");
		eyeCount = 4;
	}
	outputText("  <b>(You now have spider eyes!)</b>");
	changes++;
}
```
Texts shortened and code simplyfied in this example code.

**Comment by anonymph** [comment]
Oh, the confusion is about what "spider" and "arachnid" means in the scenes. I'm always imagining the eyes on an actual spider, but you've understood it as the number of eyes?

To avoid this confusion in the future, why not use "four/six/eight/many eyes", when we're talking about a large number of eyes, and "spider eyes" when were talking specifically about eyes that would belong on an actual spider?

Then I'm gonna vote for excluding the `hasSpiderEyes()` method (or at least call it `hasManyEyes()`). `player.eyeCount > 2` is good enough.

**Comment by Stadler76** [comment]
mmh, `hasManyEyes()` is a bit vague. Actually it reminds me of the YouTube-Video **Onyxia wipe animation**:
"_Left side ... even side ... **many whelps** ... NOW! HANDLE IT!!!_"

I guess I'd go for `hasExtraEyeRows()`
btw: I've updated the latter code in the comment above.
Additionally I'd add the method `isTriclops()` to exclude the player having exactly 3 eyes.

### Code for the method definitions in `Creature.as`:
```as3
		public function hasExtraEyeRows():Boolean
		{
			return eyeCount > 2 && !isTriclops(); // always exclude eyeCount == 3!
		}

		public function isTriclops():Boolean // for the future and for the sake of excluding the player having exactly 3 eyes! Better be safe, than sorry (Stadler76)
		{
			return eyeCount == 3; 
		}
```

### Simplified drider/spider-eyes TF code snippet in `Mutations.as`:
```as3
if (eyeType != EYES_HUMAN || !hasExtraEyeRows()) {
    if (eyeType != EYES_HUMAN && !hasExtraEyeRows()) { // if (true || true)
        outputText("\n\nYou eyes revert to be human eyes.[...]"
                  +"  And you now have an extra set of eyes[...]");
        eyeType = EYES_HUMAN;
        eyeCount = 4;
    } else if (eyeType == EYES_HUMAN ) { // if (false || true)
        outputText("\n\nYou now have an extra set of eyes[...]");
        eyeCount = 4;
    } else {  // if (true || false)
        outputText("\n\nYou eyes revert to be human eyes.");
        eyeType = EYES_HUMAN;
    }
    outputText("  <b>(You now have spider eyes!)</b>");
    changes++;
}
```
### Note
- I tend to add (Stadler76) to a few of my comments. I don't do this to tag the code with my name. I just don't want, that other coders have to backtrack (aka blame) the code to find out, whose opionion that is.

**Comment by anonymph** [comment]
Still not sure we need those methods. `hasExtraEyeRows()` is equivalent to `eyeCount > 3`, `isTriclops()` is just `eyeCount == 3`. They are less concise, less expressive, and would look somewhat ugly in a `if...else if...else` statement:
```actionscript3
if      (player.eyesCount == 2)  outputText("Two Eyes");
else if (isCyclops())            outputText("Three Eyes");
else if (hasExtraEyeRows())      outputText("Many eyes");
// VS
if      (player.eyesCount == 2)  outputText("Two Eyes");
else if (player.eyesCount == 3)  outputText("Three Eyes");
else if (player.eyesCount >= 4)  outputText("Many eyes");
```

I've created [a branch](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/master...anonymph:eyeCount), with how I think this should be done. Every instance of `EYES_FOUR_SPIDER_EYES` have been replaced with appropriate logic and text. (Excluding `saves.as` and `appearanceDefs.as` obviously.) Input would be very appreciated.

**Comment by Stadler76** [comment]
Because `!hasExtraEyeRows()` would return true for `eyeCount <= 3` without `isTriclops()` and this is not intended.

**Comment by anonymph** [comment]
Although I favor no method at all, `player.hasExtraEyes()` is a fine solution. I've got no further objections to this, you're welcome to go ahead.

**Comment by Stadler76** [comment]
Ok, goodie.

And if we ever add triclopses to the game I can always refactor this. And for the sake of simlicicity it would **then** (/me points at the word then) check for `player.eyeCount() >= 4;`

### The following example is for future uses, so don't nail me on that
**Simplified example of the code in spider/drider mutation:**
```as3
if (!player.hasExtraEyeRows()) // if (player.eyeCount < 4) {
	if (player.isTriClops()) // eyeCount == 3. Will be in Creature.as, since its not only for players.
		outputText("The eye on your forehead splits up into two eyes.");

	outputText("  <b>You now have two smaller eyes on your forehead.</b>");
	player.eyeCount = 4;
	// we have no cyclopses or ppl. without eyes so we'll just silently ignore that.
	// Actually: if the player has an eyeCount < 2 this TF will silently discard and fix that for now
}
```

### Important
- Again: we don't have cyclopses or triclopses. So I've decided not to fix what isn't broken.
- If we ever add one of these, refactoring a method name is easier than wading through the code again to replace any `if (player.eyeCount > 2)` check again and then again for the other.
- Many IDEs support refactoring and refactoring is a matter of a few clicks and keystrokes to rename a function or method.
- `player.isTriclops()` is just for the sake on being an example and could safely be replaced with `player.eyeCount == 3`

**Comment by Kitteh6660** [comment]
Go ahead, do it.
