### ISSUE TITLE
Game Freeze When Saving

### ISSUE THREAD

**Issue by croachasfu** [Kitteh6660/Corruption-of-Champions-Mod#268]
When I try to save to the game after playing for about a minute or so, I get this prompt but am unable to do anything other than close the game. I have however been able to prevent this by saving to file, but that's a bit annoying. I also have been having this issue with vanilla TiTs.
![screenshot_6](https://cloud.githubusercontent.com/assets/20416848/16762639/2de1f546-47da-11e6-879f-7edb301d5649.png)

Apologies if I'm lacking info, this is my first post here. Just let me know if more information is needed to help with this

**Comment by Kitteh6660** [comment]
If this happens in vanilla CoC then that unfortunately is something I couldn't do at the moment.

**Comment by Kitteh6660** [comment]
Try setting to allow local to save information.
