### ISSUE TITLE
pure jojo to corrupt jojo bug

### ISSUE THREAD

**Issue by thenonamezz** [Kitteh6660/Corruption-of-Champions-Mod#276]
when going too corrupt with pure jojo in camp he leaves. and if you meet him in the forrest and rape him (i did it like 15 times) nothing happens. i recuted vapula and then he left again

**Comment by XavierBro-13** [comment]
What's your libido stat? That may be your problem.

**Comment by thenonamezz** [comment]
sadly i dont have that exact save anymore but i can tell you how i fixed it
i used these in the test input under debug info
[button jojoScene.lowCorruptionJojoEncounter | test]
[button jojoScene.highCorruptionJojoEncounter | test]

first low corr once then high i did that like 5-7 times i think and that fixed it
