### ISSUE TITLE
[Feature Request] Android Build

### ISSUE THREAD

**Issue by PowerOfVoid** [Kitteh6660/Corruption-of-Champions-Mod#28]
Apparently some people play this game on Android, and apparently that needs to be built specially.

**Comment by EternalDragon** [comment]
From the Forum Main Post:

> Please don't request iOS/Android version. I DON'T know how to compile these versions.

Don't know if Kitteh has found a way yet or is willing...

**Comment by Kitteh6660** [comment]
I have no current knowledge so if anyone here knows how to compile Android builds, go nuts.

**Comment by Kitteh6660** [comment]
Actually, I've finally figured it out! 

[Check it out!](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/releases/tag/0.9.4_mod_1.2.8)
