### ISSUE TITLE
hellos and questions and comments and maybe bug spidersilk panties and bra

### ISSUE THREAD

**Issue by JynxZox** [Kitteh6660/Corruption-of-Champions-Mod#284]
hello everyone, found the game sometime ago but just started playing it a lot the last few days (this the first area i found for posting stuff and not spotted a forum if there is one and i should post there please let me know)

the bug i might have found when i went to buy a set of spidersilk panties (unsure this happens with the bra) i did not have enough gems no warning about having not enough gem took all my gems down to 0 and from then on could not go back up, did it twice after a reload ... so i forget the name of the person who makes them but as i recall they were at the camp when it happen, getting more gems later the gems still stayed at 0 ..don't know if it when to a negative number and would count up and get back into positive numbers did not test it 

so i am looking for (if its is ready) the newest mod of the game with the slave (sub game?) where the champion is taken buy slavers and all that, i have greatly enjoyed that part of the game and know its rough still with dream placeholders and all but still like it and cant wait to see more 

next and i know its not for everyone but when you turn on fetishes watersports was thinking i would see a bit more then just peeing into a bucket with the behemoth, i was thinking there be scenes of being peed in and on someone asking for the champion to pee on them, drinks etc ... new to the game so maybe there somewhere else this happens and i have just missed it 

lastly i have no knowledge of writing code, and if it was not for built in spellcheckers my typos would have typos   

ps thank you for your time

**Comment by JustGregory** [comment]
The character who transforms/crafts resources into armor is Rathazul. He can be found when exploring around the lake, and will also offer to craft things if you have the resources when you come across him there.

Also, if you would like to try a visual editor to read in the saved data, look to @tmedwards 's ```CoCEd``` repository. You can click the "Releases" to obtain the most recent compiled applet. (It is by no means a "pretty" applet, at least to my aesthetic specs; but, ... eh, to "cheat", "tweak", or even just "error-check" the state of a game and various character/game properties, ... it works.)

[ ... I have no comment on the watersports part; I avoid it and the worms like the plague. ]

**Comment by JynxZox** [comment]
worms i avoid too... and i know watersports is not for everyone... i can make suggestions if someone like to contact me about it... 

i am mostly just a user of my computer and lots of the working are a mystery to me... i dont have the saves with the bug ..i have even restarted the game as i went looking in the area the saves should be they are not there and i tried to save to a file and reload to a newer game and either i am doing something wrong or they are not compatible

**Comment by Kitteh6660** [comment]
The gem bug will be fixed in 1.4. Turned out that it deducted 500 even for the undergarments instead of 200. Whoops! Negative gems are going to be patched too.

The slave part is the Prisoner Mod by FeiFongWong. It's unfortunately abandoned and I have yet to find someone willing to make a PR with more complete scenes.

And as for watersports, I want to eventually add more scenes, yes.
