### ISSUE TITLE
[Prison] Retrieved equipment should default to re-equipping if slot is empty

### ISSUE THREAD

**Issue by PowerOfVoid** [Kitteh6660/Corruption-of-Champions-Mod#30]
Exactly what it says.

When your character escapes, he/she/it/ze should re-equip armor/weapons/shields rather than putting them in the backpack.

**Comment by Kitteh6660** [comment]
Closed via 49bc66758e6cdd7f26e12eb1dfc2ed5dcbf6fa9e.
