### ISSUE TITLE
Game won't compile anymore again due to the changes in ImpScene.as

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#303]
### First things first
@anonymph: I have **absolutely no problem** with fixing the bugs you cause, meaning:
- no need to apologize
- you have yet to learn more about coding
- and (most importantly) **keep up the good work**. :)

### Back on topic
The recent changes to ImpScene.as cause a couple of errors:
`Error: Implicit coercion of a value of type Boolean to an unrelated type Number.`
I'll file a PR to fix this in a whiff

**Comment by anonymph** [comment]
Oh, damned, I'm using a compiler, that supports implicit `Boolean to Number` translation. Maybe we need a styleguide, to make sure everyone is one the same page?

@Stadler76: Thank you. I'll still try to reduce the number of bugs.

**Comment by Stadler76** [comment]
PR #304 filed and merged.
closing
