### ISSUE TITLE
[Feature] Renaming the button 'Fire Breath' to 'Terra Fire'

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#311]
I plan to rename the Combat button 'Fire Breath' to 'Terra Fire' and to change the tooltip accordingly.

Reasons:
- I have heard about a plan to add more Breath attacks including 'Fire Breath' in the future.
- IMHO it fits better to that attack and its description, when you unleash it:

  > A growl rumbles deep with your chest as you charge the terrestrial fire. When you can hold it no longer, you release an ear splitting roar and hurl a giant green conflagration at your enemy.
- It sounds more, like an earth based breath attack to me.

### The diff would look, like the following:
```diff
diff --git a/classes/classes/Scenes/Combat/CombatAbilities.as b/classes/classes/Scenes/Combat/CombatAbilities.as
index 22fb8cd..dd00422 100644
--- a/classes/classes/Scenes/Combat/CombatAbilities.as
+++ b/classes/classes/Scenes/Combat/CombatAbilities.as
@@ -689,7 +689,7 @@ package classes.Scenes.Combat
 				addButton(button++, "DragonFire", dragonBreath, null, null, null, "Unleash fire from your mouth. This can only be done once a day. \n\nFatigue Cost: " + player.spellCost(20), "Dragon Fire");
 			}
 			if (player.findPerk(PerkLib.FireLord) >= 0) {
-				addButton(button++,"Fire Breath",fireballuuuuu, null, null, null, "Unleash fire from your mouth. \n\nFatigue Cost: 20", "Fire Breath");
+				addButton(button++, "Terra Fire", fireballuuuuu, null, null, null, "Unleash terrestrial fire from your mouth. \n\nFatigue Cost: 20", "Terra Fire");
 			}
 			if (player.findPerk(PerkLib.Hellfire) >= 0) {
 				addButton(button++,"Hellfire",hellFire, null, null, null, "Unleash fire from your mouth. \n\nFatigue Cost: " + player.spellCost(20));
```

### Opinions? Objections?
Escpecially @Kitteh6660: I'll file a PR for that soonish unless anyone has objections.

**Comment by Tomash667** [comment]
Wtf is terrestrial fire?

**Comment by Darth-Cthoras** [comment]
Ackbal's Terrestrial Fire. The demon panther in the Deep Forest - he gives it to you if you submit enough times and have a huge amount of corruption.

**Comment by Stadler76** [comment]
PR #312 filed, accepted and merged

**closing**
