### ISSUE TITLE
Quickload and especially quicksave is a little too quick for me.

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#313]
From time to time I accidentally hit one of the function keys, while playing the game, which resulted in accidentally overwriting one of my precious save games. So I think, that this should include a confirmation dialogue.
I have tested my approach with quickload for starters and it seems to work fine. For the sake of simplicity and for easier testing I have added a method to `CoC.as`.
Additionally I plan to relocate more of these bindings into a function call in a new class called Bindings or BindingHandler or similar, rather than adding up to this copy&paste-mess in `includes/ControlBindings.as`.

### diff for the quick and dirty test I wrote:
```diff
diff --git a/classes/classes/CoC.as b/classes/classes/CoC.as
index a52a4a7..80a0e88 100644
--- a/classes/classes/CoC.as
+++ b/classes/classes/CoC.as
@@ -335,6 +335,32 @@ the text from being too boring.
 			return Utils.rand(max);
 		}
 
+		// I'll probably relocate this to a seperate class file later, e. g. Bindings.as (Stadler76)
+		public function doQuickload(slot:uint):void
+		{
+			if (mainView.menuButtonIsVisible(MainView.MENU_DATA))
+			{
+				var saveFile:* = SharedObject.getLocal("CoC_" + slot, "/");
+				if (saveFile.data.exists)
+				{
+					clearOutput();
+					outputText("You are about to quickload the current game from slot <b>" + slot + "</b>\n\nAre you sure?");
+					menu();
+					addButton(0, "No", playerMenu);
+					addButton(1, "Yes", function():void {
+						if (saves.loadGame("CoC_" + slot))
+						{
+							showStats();
+							statScreenRefresh();
+							outputText("Slot " + slot + " Loaded!", true);
+							doNext(playerMenu);
+						}
+					});
+				}
+			}
+		}
+
+
 		public function CoC()
 		{
 			// Cheatmode.
diff --git a/includes/ControlBindings.as b/includes/ControlBindings.as
index 021e3e1..666d932 100644
--- a/includes/ControlBindings.as
+++ b/includes/ControlBindings.as
@@ -88,26 +88,8 @@ inputManager.AddBindableControl(
 			doNext(playerMenu);
 		}
 	});
-	
-inputManager.AddBindableControl(
-	"Quickload 1",
-	"Quickload the current game from slot 1",
-	function():void {
-		if (mainView.menuButtonIsVisible(MainView.MENU_DATA))
-		{
-			var saveFile:* = SharedObject.getLocal("CoC_1", "/");
-			if (saveFile.data.exists)
-			{
-				if (saves.loadGame("CoC_1"))
-				{
-					showStats();
-					statScreenRefresh();
-					outputText("Slot 1 Loaded!", true);
-					doNext(playerMenu);
-				}
-			}
-		}
-	});
+
+inputManager.AddBindableControl("Quickload 1", "Quickload the current game from slot 1", function():void { kGAMECLASS.doQuickload(1); });
 
 inputManager.AddBindableControl(
 	"Quickload 2",
```

**Comment by Darth-Cthoras** [comment]
Make sure to add an option to toggle confirmation on/off.

**Comment by Stadler76** [comment]
Well, then you would have to hit F6 --> 2 --> 1 for example in that case, but I'll see, what I can do about that.
Probably in Interface settings and it would be a flag stored in the perm object aka the global save file. And maybe even off by default.
Either I'll use two settings (One for quick save and one for quick load) or one setting either for both or for quick save only. I'd probably go for the last option. What do you think?

**Comment by Darth-Cthoras** [comment]
It isn't difficult to mistakenly hit F6 instead of F5, or vice versa, and lose progress or save unwanted progress. A switch for each would probably be ideal.

**Comment by Stadler76** [comment]
Ok, first step done (see above). Next step would be to add these two options to Settings -> Interface

**Comment by Stadler76** [comment]
And the second (final) step is done, too.

@Darth-Cthoras: Tell me, if you want to test this. I'll upload the compiled game to my Dropbox-account and share it, but I recommend you to backup things first, since this is from the development version of CoC Revamp.

**Comment by Darth-Cthoras** [comment]
@Stadler76 Sure, why not. I'll give it a look.

**Comment by Stadler76** [comment]
Here we go: https://www.dropbox.com/sh/cq94w7xzqxc73wc/AACqF9yWeLSpqJwesYxWafnya?dl=0

Please note, that the dialog only appears, if you have actually loaded a game. Wouldn't make sense, if quickload won't overwrite anything ^^.

**Comment by Stadler76** [comment]
Sigh ... do you want to login here, upgrade your account to dropbox pro there. Dropbox starts to suck more and more. I guess I'll ditch dropbox sooner or later ...

I've just copied the file to Google Drive: https://drive.google.com/file/d/0B6ayFYXDcvsAWFBtejYyOHdQeUk/view?usp=sharing
Hopefully this is less annoying ...

**Comment by Darth-Cthoras** [comment]
Awesome, it works :+1:  Though the default controls did really weird stuff, for whatever reason, acting as if I was typing in special names. Once I reset the controls, it was fine, though.

**Comment by Stadler76** [comment]
> Awesome, it works :+1:

Goodie. I'll file a PR soon.

> Though the default controls did really weird stuff, for whatever reason, acting as if I was typing in special names. Once I reset the controls, it was fine, though.

The key bindings aren't saved in the global save file. You have to set them for every savegame.

But I guess, the whole **Keyboard Control Bindings**-system needs some rework. No go back button. The key you hit is instantly stored. No unbind button and so on. and you can't set key combinations. While the latter requires more work I guess, I could do something about the other two issues sooner or later.

**Comment by mrttao** [comment]
A confirmation dialog makes it not be quick anymore.

Typically the solution to accidentally hitting F6 instead of F5 is to separate them out. Make quickload F5 and quicksave F9 or vice versa. That big separate between the two makes it impossible to accidentally mix the two, while still allowing quickload/save to be quick.

**Comment by Stadler76** [comment]
Go to Main **Menu → Settings → Interface** to disable these confirmation dialogs and you can always set the **Keyboard Control Bindings**.

**Comment by mrttao** [comment]
I didn't realize they are optional, in that case I rescind my concern. Optional features are great

**Comment by Stadler76** [comment]
I've decided to open an issue about that before filing a PR since I considered, that ppl. may want that to be optional.

You should have read the whole discussion ;)
