### ISSUE TITLE
Revamp the output-system to prefer using the new Output-class

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#318]
## Intro

I'm planning to revamp the output-system and to implement a new class called `Output`
For a sneak peek take a look at the [branch I'm working on](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/master...Stadler76:Output-system-rework), especially at the changes in `PlayerAppearance.as`
## Reasons
- I don't like most of the include-files. It just sucks, when you try to trace the methods in there to their definition in your IDE
- I like to introduce the so called '[Fluent interface](https://en.wikipedia.org/wiki/Fluent_interface)' aka method chaining. If you know, how to code jQuery you should probably know, what I'm talking about.
- In don't like these overlong `outputText("...", false|true);` lines. Use `output.text("...");` respectively `output.clear().text("...");` instead.
  - Setting the second param to its default in nearly every call to `outputText()` is somewhat stupid anyway IMHO.
## Notes
- The old system will still work, so it is not required, that you replace every single call to them with the new ones immediately.
- I'd suggest that we all replace the old calls with the new ones and **slowly, but sure** deprecate the old ones.
- Be aware, that both output.text("...") and output.markdown("...") have no second `clearOutput:Boolean = false` parameter, so you have to remove `, false);` a the end of these calls, when replacing them.
- Short method chains can be in one line, while longer method chains should be in multiple lines (See the examples below).
#### Old version

``` as3
// this
clearOutput();
outputText("blah, blah, blah, very long line of text");
// or this
outputText("blah, blah, blah, overlong line of text", true);
```
#### New version

``` as3
// could become this:
output.clear().text("blah, blah, blah, very long line of text");
// or this:
output.clear();
output.text("blah, blah, blah, very long line of text");
// or this:
output.clear()
      .text("blah, blah, blah, very long line of text");
```
#### Old version

``` as3
// this
clearOutput();
displayHeader("Hello, World!");
```
#### New version

``` as3
// could become this
output.clear().header("Hello, World!");
// or this
output.clear();
output.header("Hello, World!");
// or this
output.clear()
      .header("Hello, World!");
```
#### Old Version

``` as3
flushOutputTextToGUI();
```
#### New Version

``` as3
output.flush();
```
### Markdown example

Note, that markdown support is disabled atm, since its very experimental and uses an incomplete shoddy implementation. So this example is non-functional and does the same as `output.text()`
#### Old Version

``` as3
outputText("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores.", true, true);
outputText("Lorem ipsum dolor sit amet, consetetur sadipscing [...].", false, true);
```
#### New Version

``` as3
output.clear().markdown("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores.");
output.markdown("Lorem ipsum dolor sit amet, consetetur sadipscing [...].");
```

**Comment by Stadler76** [comment]
I've updated the markdown example to make things clearer to you:
In the old variants you have to scroll to the right unless you have word-wrap active in your IDE to see if the output should be cleared or not and to see, if it uses markdown or normal text. In the new variants you'll see it immediately with out scrolling.

**Comment by JustGregory** [comment]
Funny you should mention revamping the output.... I began tinkering with something like this, just two or three months ago.

In my iteration of it, though, I had a ```Messages``` class that contained an array of ```Message``` objects, each Message being a paragraph. My Messages contained getter/setter methods to add or retrieve Message paragraphs wholesale, as well as add individual sentences to the last-added paragraph. And, of course, a method to clear all.

I was also tinkering with including in ```Messages``` one or more methods where a developer could pass in instances of items, the player, or other characters, and auto-generate the respective descriptions (for Examine actions).

**Comment by Stadler76** [comment]
Actually I had the same idea, but I intended to name it 'texts'
An example call could be something, like:
output.text(message.transformations.lowerBody(tfSource, player.lowerBody);

**Comment by Stadler76** [comment]
To give you an idea, what tfSource is, check the changes in PR #289 and #309

**Comment by JustGregory** [comment]
Eh, you might be waiting a while; I was only working on a blind-copy of the source downloaded from months ago, it's probably long out-of-sync with the repo by now. If I actually wanted to submit, I'd be a while checking out and copying/editing back in my personal changes.

One of the reasons I was taking the above approach, I might add, was that it "feels" inefficient to have all the "\n" bits at the beginning of a paragraph or new-line, when clearly it might be simpler to (in my case of a ```Messages``` class with static methods) call ```Messages.addParagraph("Shouldra says hello, Sparky.");```

**Comment by Stadler76** [comment]
mmh, IIRC the parser replaces [pb] with \n\n
And I have no idea, if AS3 and/or Flash supports formatting `<p>`-tags

PS: I've just changed the visibility of _addText(...) from private to protected, though I'd suggest, that you call `text()` or `markdown()`
And I'd suggest, that you extend the output-class, once I filed my PR
And don't be afraid to rename `Output` to `OutputBase` or something, like that and to move it to classes.Output. Then you could add your paragraph methods to `class Output extends OutputBase`
Method names could be
```as3
public function addParagraph(...para:String):Output { /* ... */ return text(resultText); }
public function addMDParagraph(...para:String):Output { /* ... */ return markdown(resultText); }
```

**Comment by Stadler76** [comment]
Ok, now that I see this:
Actually my idea was to relocate certain texts to a new class or a new package hierarchy. Note, that some TF texts are copy&pasted into multiple files with slight to no changes at all. Keeping track of them or finding examples of them can be a burden, especially for those, who have yet to learn about the file structure or to learn, how to use grep.
However: This would be a seperate issue and as of speaking I only have vague ideas, how to solve this.
Note, this this class should **not** output anything directly. Instead it should **return** complete texts, phrases or even paragraphs.

**Comment by JustGregory** [comment]
- Note, this this class should 'not' output anything directly. Instead it should  return  complete texts, phrases or even paragraphs.

Yes! That's my idea! It was my trying to study the nature or "push" versus "pull" methodologies for the message system. Basically, the paradigm I'd envisioned was that instead of the "push" metaphor of appending text directly to a text area, that it merely pushes to an *array of paragraphs* -- after that, the core level of processing (clicking on buttons, etc) would respond to the event and "pull" the text to the text area. Well, once upon a time there might have been a little more to the idea, too; an idea to "have fun with" the text after it's displayed ... but it will depend upon output-overhaul, so I'll wait.

**Comment by Stadler76** [comment]
Actually, the system buffers all texts until it actually flushes to the output.
What I intend to have is:
The **output system** is responsible for adding texts to the buffer, clearing the buffer and flushing the buffer to the output. In CoC (probably because of the limitations of flash) flushing the buffer doesn't clear it, so you can add more text to the output after flushing it. This includes adding paragraphs to the buffer.
The **messages system** stitches texts together and returns them as complete phrases, paragraphs and so on, so you could add them to the output(-buffer) by calling the output-methods.
Assume, that writing a new sex scene is just cherry-picking paragraphs of already existing texts where all needed factors, like gender, player is a taur, penis size and type and, and, and is already accounted for and the rest is plain coding. e. g.: player is taur and dick not long enough? 
```as3
output.text(messages.sexScenes.getParagraph('xyz'));
output.text(messages.sexScenes.Benoite.getPregged()); // Different texts depending on Benoit**e** pregged, already pregnant or not pregged due to other limitations
if (player.isTaur() && player.longestCockSize() >= x ) {
	// set flags 'n stuff to make benoit pregnant
}
```
For starters these texts should be for mutations, since many of these texts are just copy&pasted through the whole codebase aka start simple and improve later.

**Comment by JustGregory** [comment]
One step closer to supporting A11Y/I18N/L10N then, right?

**Comment by Stadler76** [comment]
Yepp

**Comment by Stadler76** [comment]
> One step closer to supporting A11Y/I18N/L10N then, right?

Yepp.

**Comment by Stadler76** [comment]
> One step closer to supporting A11Y/I18N/L10N then, right?

Yepp

**Comment by anonymph** [comment]
This is a really nice way to fix some of the issues I've got with CoC/actionscript's handling of text.

It would help with compositing longer texts:
```actionscript3
clearOutput();
outputText("Wow, this is a long text, I better have another line\n\n")
outputText("Damned, nice, this is a good newline.")
// VS
output.clear()
      .text("Wow, this is a long text, I better have another line\n\n")
      .text("Damned, nice, this is a good newline.")
```
And with some of the simpler text variations:
```actionscript3
clearOutput();
outputText("Damned "+player.name+", look at that ");
if (player.hasCar())  outputText("car");
else                  outputText("bicycle");
outputText(", what a nice "+(player.hasCar() ? "car." : "bicycle."));
// VS
output.clear()
      .text("Damned ")
      .text(player.name)
      .text(", look at that ")
      .text(player.hasCar() ? "car" : "bicycle")
      .text(", what a nice ")
      .text(player.hasCar() ? "car." : "bicycle.");
```

It really is much more readable, because of the ability to use vertical space in a better way. Not sure if more complex variation can become better with this, though:

```actionscript3
clearOutput();
outputText("Hey, that sure is a ");
if      (player.carSize <  3)  outputText("tiny");
else if (player.carSize <  7)  outputText("small");
else if (player.carSize < 10)  outputText("large");
else                           outputText("HUGE");
outputText((player.hasCar() ? " car" : " bicycle")+" you've got there.");
// VS
output.clear()
      .text("Hey, that sure is a ");
if      (player.carSize <  3)  output.text("tiny");
else if (player.carSize <  7)  output.text("small");
else if (player.carSize < 10)  output.text("large");
else                           output.text("HUGE");
output.text(player.hasCar() ? " car" : " bicycle")
      .text(" you've got there.");
```

**Comment by Stadler76** [comment]
For longer texts you can use
```as3
	outputText("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy"
	          +" eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
	          +" voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet"
	          +" clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit"
	          +" amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam"
	          +" nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,"
	          +" sed diam voluptua. At vero eos et accusam et justo duo dolores et ea"
	          +" rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem"
	          +" ipsum dolor sit amet.");
```
Note, that I use a combinaton of indenting with tabs and aligning with spaces in this example.
And I've realized, that I can use the parser to save us from cluttered things, like `" + player.name + "`

About match_lt: that would be a different class. Actually you should use something, like
```as3
output.text(
	match(player.carSize)
		.lowerThan(3).addText("tiny")
		.lowerThan(7).addText("small")
		.lowerThan(10).addText("small")
		.else().addText("small")
	.end()
);
```
Don't forget, that output adds text to the output. In other words: It just a wrapper around `print`ing and/or `echo`ing to the output or the output buffer directly, so you shouldn't chain output.text()-calls unless they still support L10N, I18N and so on.

In my PHP-framework Output.php is more powerful, since its repsonsible for creating and buffering a full and valid HTML-page starting with the doctype and ending with the final `</html>` at the end of it. It hasn't been exposed to the public yet, because the license (currently BSD-3-clause) is not finally decided and I don't want to reveal the name of it yet until I've registered a few domains for it. I'll point you to it, when I'll publicize it.
```php
$out = Output::init(); // this is slightly different in my FW, but I don't wanna reveal too much of it yet ;)
$out->setTitle("Hello, monkey world!");
$out->addJQueryUI('themename');
$out->addAuthor('Christian Stadler');
// and so on
// since the output is initialized
// this
$out->add(__('There are {1} monkeys in the tree', $monkeycount));
// does the same as
echo __('There are {1} monkeys in the tree', $monkeycount);
// output buffering and shutdown functions ftw! ^^
```
It has full support of method chaining, but such an example would look way too cluttered.

**Comment by anonymph** [comment]
Chaining `output.text()`-calls would function fine, assuming `output.text()` returns the `output` object, because the text is added to the buffer in the same order.

## Following is a proof that `output.text()` chaining is allowed ##

Fluent interface is a programming design pattern to simplify repeated calls to the same object. It's often used for initiating objects, like in jQuery. It does this by returning the object itself when calling it's methods. This allows code like:
```actionscript3
person.setName("Tom");
person.setAge(40);
// To be written efficiently like:
person.setName("Tom").setAge(40);
```
This builds upon the common behavior in modern programming languages, that:
```actionscript3
intermediate_obj = callOne();
end_result = intermediate_obj.callTwo();
// Can be abbreviated to:
end_result = callOne().callTwo();
```
This works in any case, no matter what side-effects either call may incur.

So lets say we have the following code: (And `output.text()` returns `output` itself.)
```actionscript3
output.text("a");
output.text("b");
output.text("c");
```

It's clear to see, that we can change this to: (The compiler won't accept this, but that's because actionscript is shit.)
```actionscript3
var output:Output = output;
var output:Output = output.text("a");
var output:Output = output.text("b");
output.text("c");
```

And that this is equivalent to:
```actionscript3
var a:Output = output;
var b:Output = a.text("a");
var c:Output = b.text("b");
c.text("c");
// And that
assess( output == a && a == b && b == c );
```

Now it's obvious that we can change this to:
```actionscript3
output.text("a").text("b").text("c");
```

Thus there is no issue with chaining `output.text()` calls, even though it may initially look like there would be one.

**Comment by Stadler76** [comment]
output.text() doesn't return text. It returns a reference to the instance ... Thats the problem. Well actually, this isn't the problem, its my intention.
See [`protected function _addText(text:String, /* ... */):Output`](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/compare/master...Stadler76:Output-system-rework#diff-83944acd95fa467249b5ccfe2db5637dR24) for a reference.
I could have named it `output.addTextToBuffer("...")` or just `output.addText("...")` but I wanted to keep the names short.

And again: Output is for output and Message(s) is for generating messages.

Your example should read:
```as3
output.text(message.add("a").add("b").add("c")); // or use messages.add(...), if you named that class Messages
```

PS: `assess( output == a && a == b && b == c );` I guess, you've meant `assert(...)`, right?

**Comment by Stadler76** [comment]
PPS:
```as3
assess( output == a && a == b && b == c );
//     ^--- yuck                       ^--- yuck
```
please don't add whitespace after `(` and/or before `)`

**Comment by anonymph** [comment]
Yeah, thats the point. `output.text()` returns the instance of `Output` you've just called it on. That's why you can chain them.

Yeah, meant `assert`. It was just meant to signify that `output`, `a`, `b` and `c` was the same instance.

**Comment by Stadler76** [comment]
Yepp, you **can** chain them. But I strongly recommend not to chain them to stitch text fragments together.
But, what you can use is:
```as3
output.clear().header("Hello, World!")
      .text("First sentence or Paragraph 1")
      .text("Second sentence or Paragraph 2")
      .text("and so on");
```
If you indent to recherche, how A11Y/I18N/L10N works, I'd recommend you to take a glimpse at the PHP implementation of [GNU gettext](http://php.net/manual/en/function.gettext.php). Wordpress for instance uses gettext for its localisation (L10N).

**Comment by Stadler76** [comment]
Sorry for comment-spam, but:
```as3
output.text("Hello, ").text("my ").text("name ").text("is ").text("John Doe!");
```
would be a step away from A11Y/I18N/L10N. But I guess, your examples didn't intend to step away from A11Y/I18N/L10N, since they were just that: Examples and nothing else.

**Comment by anonymph** [comment]
Alright, the focus is on "A11Y/I18N/L10N", not on extending the expressiveness of the text. Well, then I've lost interest in this discussion. Good luck, though.

**Comment by Stadler76** [comment]
Ok, to make you interested again to this:
After the PR for this was filed and merged, I'll rework some of the methods in `MutationsHelper.as`
Would be something, like
```as3
var message:String = "";
//...
if (/* ... */) message += "\n\n";
if (/* ... */) message += "blah, blah";
// ...
output.text(message)
      .text("  <b>You have normal human arms again.</b>");
```
and point you to it, to make things clearer to you.

**Comment by JustGregory** [comment]
Mmm, I'm a little less in favor of method-chaining, it's just my personal practice though. For every chained instance you are adding an additional computation to return the object value. Now, this may not be incredibly processor-intensive for _this_ game; however, I'm less in favor of the method chaining than using plain void-type methods to only append text.

In the end, though, ... as long as the normal game-flow isn't impacted too terribly, I have no complaint.

**Comment by Stadler76** [comment]
Actually, I'll try to reduce calls to outputText or output.text, thus keeping chains short.

And about @anonymph's example:
```as3
output.clear()
      .text("Damned ")
      .text(player.name)
      .text(", look at that ")
      .text(player.hasCar() ? "car" : "bicycle")
      .text(", what a nice ")
      .text(player.hasCar() ? "car." : "bicycle.");
```
I'd rather use:
```as3
// this
output.clear()
      .text("Damned "
           + player.name
           +", look at that "
           + (player.hasCar() ? "car" : "bicycle")
           +", what a nice "
           + (player.hasCar() ? "car." : "bicycle.")
      );
// or (better) this
output.clear()
      .text("Damned [name], look at that " + (player.hasCar() ? "car" : "bicycle")
           +", what a nice " + (player.hasCar() ? "car." : "bicycle.")
      );
// this could work too, if the conditional [hascar true|false] is added to the parser:
output.clear()
      .text("Damned [name], look at that [hascar car|bicycle], what a nice [hascar car|bicycle]."));
// or you could add a tag to the parser, called [vehicle]:
output.clear().text("Damned [name], look at that [vehicle], what a nice [vehicle]."));
```
And in my example above, that should actually read:
```as3
	output.text("Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy"
	           +" eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam"
	           +" voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet"
	           +" clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit"
	           +" amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam"
	           +" nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,"
	           +" sed diam voluptua. At vero eos et accusam et justo duo dolores et ea"
	           +" rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem"
	           +" ipsum dolor sit amet.");
```

**Comment by Stadler76** [comment]
I've added ASDoc-comments to all methods in Output.as. Ran some final tests, along with some more finetunings and finally filed PR #326 for it.

After this has been accepted and merged, I'll file one or two PR to give you examples.

PS: My first victim of deprecation and removal would be `flushOutputTextToGUI();`

**Comment by Stadler76** [comment]
@anonymph: Here you go: PR #333 (updated MutationsHelper.restoreArms to use the Output class) filed.

**Comment by Kitteh6660** [comment]
If it ain't broke, don't fix it.
