### ISSUE TITLE
Rename used unknown flags

### ISSUE THREAD

**Issue by anonymph** [Kitteh6660/Corruption-of-Champions-Mod#323]
We currently have some flags in use without appropriate names, which is confusing and bad practice. This is mostly an issue for flags with values in the 141 to 350 range.

This should be a pretty easy change, as it's pretty much just a search&replace job. Don't do them all in a single commit though. Also ensure formatting of `kFLAGS.as` is correct after.

**Comment by Stadler76** [comment]
Ok, I've grepped through the code and compiled a table with the help of the included php-script. Maybe this could help you: [unknown-flag-number.tar.gz](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/417426/unknown-flag-number.tar.gz)

**Comment by anonymph** [comment]
That's pretty nicely done. This reveals some pretty weird bugs, like how `UNKNOWN_FLAG_NUMBER_00294` are ever only checked, but never assigned. Or how the only use of `UNKNOWN_FLAG_NUMBER_00418` is commented out.

Now I'm curious to do some more analyzing of flags.

**Comment by Kitteh6660** [comment]
Flags should be named by now.
