### ISSUE TITLE
Bug - Battlemage Perk + Sex with Pure Jojo Follower

### ISSUE THREAD

**Issue by jamesrussels** [Kitteh6660/Corruption-of-Champions-Mod#339]
Here's the deal: I've unlocked the sex menu for Pure Jojo Follower, and then I got the Battlemage perk.  If I approach him for sex while sufficiently aroused to proc the might effect from Battlemage, when we go to the forest to choose the type of sexual encounter, Battlemage activates.  I suppose the game is putting you into a combat area for some reason.  The problem is that when the sex scene is over, Battlemage never de-activates, and so you're left with the strength and toughness bonuses from might that never go away.  Not sure if Spellsword is similarly bugged, as I'm no coder, and I'm not really sure if that would even matter.  Anyways, just thought you should be aware of this one.

Edit: Noticed another one with Battlemage.  I entered into the third Kiha fight (the one where you fight a gang of spiders after fighting her) with low arousal, and cast Might as Battlemage had not activated.  Then, when it transitioned to the spider fight, I was sufficiently aroused for Battlemage to activate, and it activated on top of the Might I had already casted.  When the spider phase was over, I only lost one activation of Might, again resulting in permanent stat increases.

Edit: Another similar problem.  Battlemage will activate, and not de-activate, if you approach the Sand Mother's throne in the Desert Cave with sufficient lust, after completing the dungeon (explaining your situation the the Sand Mother, making her non-hostile).

**Comment by PrestonLaw** [comment]
I think I know what you're talking about.  However, I'm pretty sure that this is only a minor bug; when I got it, the bug went away after a different battle (I don't remember the specifics).

**Comment by KWJG** [comment]
function pureJojoSexMenu() (in NPCs\JojoScene.as) has following codes unconditional:

        startCombat(new Jojo());
	kGAMECLASS.inCombat = false;

I don't get it why these codes are here, because I don't fully understand the deeper layers of the codes...

**Comment by Kitteh6660** [comment]
This will be patched once I put up a commit.
