### ISSUE TITLE
Need help compiling.

### ISSUE THREAD

**Issue by thermad** [Kitteh6660/Corruption-of-Champions-Mod#343]
I apologize in advance if this isn't the correct place to post this. I have been trying to figure this out on my own for ~4 hours now and have been unsuccessful.

I am unfamiliar with flash environments, and am unable to compile the open source code. I am a college student majoring in applied mathematics and CS. I figured modifying this game, both for custom versions and possibly for the community as a whole would be a good way to learn something.

I cannot get my project to compile nor can I find the appropriate SDK to do so. Clearly these issues are related. My experience in java, limited as it is, makes it pretty easy to navigate the scripts themselves and write/edit code, so that shouldn't be a worry.

Could someone walk me through how one would go about compiling the source code into a functioning swf file if they were to download it immediately off of github?

**Comment by Stadler76** [comment]
Theres a [guide in the forum](https://fenoxo.com/forum/index.php?/topic/3915-guide-how-to-mod-corruption-of-champions/) for that.

**Comment by Stadlen** [comment]
link is broken

**Comment by Stadler76** [comment]
[x] Fixed
