### ISSUE TITLE
Cannot discover new areas

### ISSUE THREAD

**Issue by dragontamer8740** [Kitteh6660/Corruption-of-Champions-Mod#346]
I've been exploring for 15 days and still not discovered any locations using the latest source code.

**Comment by Kitteh6660** [comment]
Are you using Kaizo/Grimdark?

I'll investigate the bug further.

**Comment by dragontamer8740** [comment]
It's working now, it wasn't in one build a while ago. I am not using 'kaizo'/'grimdark' and do not remember what those are. Sorry, I forgot to close the bug.
