### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by jackdarker** [Kitteh6660/Corruption-of-Champions-Mod#347]
Hi,

I played COC ever since but now started to mod it because I have the feeling of missing a "normal" male-wolf character.

Whats the plan:
- add new NPC Fenris - an shy,adolescent,anthro-wolfman 
- indirectly reshape him by giving him guidance and support to hulking werebeast or feminine boycunt
- add quest for/with him 
- develop him into a follower, lover , slave or enemy
- extend prison scene (Fenris is trained as slave)
- add scenes in different areas where you can fight with him or let him down and watch  
- add some new gear (just for him): cockcage, muzzle, armbinder
- add Perk/StatusEffect to call him in for support in combat
- make him level with player

I would like to ask if you could merge this into your git before I start modding even more existing code. 
(https://github.com/jackdarker/Corruption-of-Champions-Mod)
I didnt contribute with git until now, so I dont know how exactly contribution works, should I create a pull request? A big portion of the code isnt tested so far, but I would like some backfeed (for coding style, embeding in old code) before continuing work on it. And I had to touch some code I didnt want to ,so I dont know if you would accept this complex pull request.
I'm not a writer and english isnt my native tongue, so I could use some help with storytelling and spellchecking. I'm more the programer-type but didnt do anything fancy in AS so far.

Done so far:
- added classes.Scenes.NPCs.Fenris;
  classes.Scenes.NPCs.FenrisScene;
  classes.Scenes.NPCs.FenrisMonster;
- uses kFlags 1950 & 1951 but persistant data saved with saveawareinterface
- modified COC to add references - Fenris implemented as singleton
- modified Lake for occurence
- basic layout of questline and started implementig it
- added classes.internals.TakeoutDrop as alternative Drop-Method
- added classes.internals.ReturnResult to make it easier to return function-results
- added bound:CombatStatusEffect as a generic bound-Status instead f.e. Bound; I had to modify Monster and Combat for this too :(

Kind regards JD

**Comment by Kitteh6660** [comment]
If you want but try to make sure everything works properly. You should change bound back and use existing status effects unless necessary.

**Comment by jackdarker** [comment]
There is no existing bound-status effect that I could reuse without getting weird textual output.
F.e. the original Bound has hardcoded in Combat.as description "The feel of tight leather completely immobilizing .." and code 
if (player.findStatusEffect(StatusEffects.Bound) >= 0) {
					addButton(0, "Struggle", (monster as Ceraph).ceraphBindingStruggle);...
That doesnt make much sense in all situations so I tried to separate description and combat logic.

**Comment by Kitteh6660** [comment]
You can add a check if the opponent is Ceraph and put different texts.

**Comment by jackdarker** [comment]
You mean in Combat.as combatMenu(..)
create some switch case inside this?
if (player.findStatusEffect(StatusEffects.Bound) >= 0) {
					addButton(0, "Struggle", (monster as Ceraph).ceraphBindingStruggle);
					addButton(1, "Wait", (monster as Ceraph).ceraphBoundWait);
}

**Comment by Kitteh6660** [comment]
Yes, you can.

**Comment by Kitteh6660** [comment]
No new responses and this is not an issue so it's now closed.
