### ISSUE TITLE
Some codex entries outputText forgot ending semicolon.

### ISSUE THREAD

**Issue by JustGregory** [Kitteh6660/Corruption-of-Champions-Mod#348]
As described in the issue title. I noticed last night while poking around in the Codex source, that several of the lines (maybe more than a half dozen, maybe a dozen, didn't count while fixing in my copy) of code are missing the ending semicolon, typically the ```outputText(String)``` lines of code. I noticed them in my copy of Stadler's source, and then again in this repo just now, and there are probably some upstream in the herp-a-derp repo, didn't go that far to check; and probably duplicated to other forks. Not sure why these have not been caught yet or why that would not have crashed a game when someone went to view the codex entries, ... but ... there ya go.

The fix is really simple; but as my copy is not a forked repo but a dumb-copy download of the sources, I don't know how to "push" a PR. I guess anyone can fix them.

**Comment by Stadler76** [comment]
ActionScript is derived from JavaScript and so in both semicolons are optional at the end of each line.
See [AS3 fundamentals: Syntax -> Semicolons](http://www.adobe.com/devnet/actionscript/learning/as3-fundamentals/syntax.html#articlecontentAdobe_numberedheader_0) for ActionScript or [Your Guide to Semicolons in JavaScript](https://www.codecademy.com/blog/78) for JavaScript (better explained).

Although its always a good practice to end **every** command with a semicolon, you shouldn't fix something, thats not really broken with PRs that just adds noise without changing any functionality.

**Comment by JustGregory** [comment]
Ah, okay. I come from using Java as my primary/only language, so I just *assume* sometimes...
