### ISSUE TITLE
Issues loading saves

### ISSUE THREAD

**Issue by ngforever1989** [Kitteh6660/Corruption-of-Champions-Mod#349]

**Comment by ngforever1989** [comment]
This is what i get with a standalone flash player. its in the same directory tho


![screenshot 5](https://cloud.githubusercontent.com/assets/24365388/20864611/4f3fac70-b9c6-11e6-897f-2d4b6a0b9883.png)

**Comment by JustGregory** [comment]
Issues are not deleted, but closed.

**Comment by ngforever1989** [comment]
can u reopen it? im still having an issue. i realized i only partly fixed it

**Comment by JustGregory** [comment]
My apologies, I edited in the 2nd sentence after posting just the first; I thought it would give more helpful / meaningful response to that.

**Comment by ngforever1989** [comment]
Thats alright. Well, i tracked down the location it stores the slot saves. And those work fine, its just the load from file that isnt work. Sadly I also realized that this mod cant use my image pack for COC. Its been a while since i played and finally realized it. Vanilla will use the image pack, but the mod version does not. Anyone know if one exist that works? or does the mod not look for it?

**Comment by JustGregory** [comment]
Just by chance, which OS are you using? 32/64 bit? Are using a somewhat aggressive antivirus / antimalware software? Also, are you perhaps running as a "limited user" or "admin"?

In some cases, I wonder if Windows or something else gives the expected SharedObject path/file the permissions as desired, or may be "neutering" your access to certain plugins like Flash to protect you from yourself. [I don't know Flash coding well enough to be sure if such permissions can be checked when the game actually loads, but if so it would be incredibly useful to display an un-missable RED ALERT warning that such read/write or load/save methodologies might or might not work as desired, depending on where it's launched from or the user's permissions.]

**Comment by ngforever1989** [comment]
10 64 bit. I not doing anything different from normal and it used to work. Admin running

**Comment by JustGregory** [comment]
I just thought of something, probably not what's causing your problem, but it's good to eliminate the obvious things first, right?

In discussing a similar problem with my younger sister I had asked how you get the flash player; do you click the link and download/save-as the flash player, or just "run" from clicking the flash player link? Because I personally am in the habit of always-always-ALWAYS downloading first, then checking the file properties, THEN running the executable. It has the obvious benefit of also allowing me to run a antivirus check manually, even if my AV would do some minimal scan while downloading.

**Comment by ngforever1989** [comment]
i have it downloaded in a folder with the saves and image pack

**Comment by PrestonLaw** [comment]
I have also been having this issue.  I am running Ubuntu 16.04, with continuous updates.  I have downloaded the .swf file, and embed it in a custom HTML file I wrote specifically to play flash files that I then open in Chrome.

Did you find a solution for your problem?

**Comment by Kitteh6660** [comment]
Does this happen to vanilla CoC too? If so, then it's not the mod problem.

**Comment by brrritssocold** [comment]
Has this issue been resolved and can be closed?

**Comment by ngforever1989** [comment]
it is still an issue, vanilla or a a modded game.
