### ISSUE TITLE
Naga ability "Constrict" using too much fatigue

### ISSUE THREAD

**Issue by Fortilicious** [Kitteh6660/Corruption-of-Champions-Mod#355]
When using the "Constrict" ability for the Naga, the original version of the game only applies Fatigue on the use of the ability "Constrict" and _not_ on the continuation/maintain ability "Squeeze".  In your mod version, fatigue is being applied on **both** "Constrict" and "Squeeze" which means your character is nearly completely fatigued after only one use of "Constrict" in most cases.

**Comment by BelshazzarII** [comment]
It's very simple change, but I'm not sure if it's a bug. Might just be a balance change.

Perhaps toning it down to 5 fatigue per squeeze would be a good balance?

**Comment by Kitteh6660** [comment]
I'll reduce the fatigue from squeezing from 20 to 10. Just remember that the Iron Man perk affects fatigue from Squeeze.
