### ISSUE TITLE
"Clinic" in Tel Adre glitch

### ISSUE THREAD

**Issue by Fortilicious** [Kitteh6660/Corruption-of-Champions-Mod#356]
The clinic in Tel Adre is showing up as available to visit before you meet Loppe for the first time.  Not sure if it was intended or not, but the text when visiting the clinic is stating that you've already met Loppe and have her as a girlfriend, even if you haven't met her yet.

**Comment by Kitteh6660** [comment]
The change to make clinic accessible the moment you enter Tel'Adre is intended to eliminate content lockout if you choose Uninterested.

However, I'll make the fix so Uma won't refer you as girlfriend of Loppe if you're not her girlfriend.

**Comment by Darth-Cthoras** [comment]
Don't forget to ensure she doesn't offer you the discount for being Loppe's girlfriend if you're getting her services prior to doing the dirty with Loppe.

**Comment by Kitteh6660** [comment]
Already accounted for from the time Uma's shop is made available without the need for meeting Loppe. :)
