### ISSUE TITLE
FoxFire STILL not properly showing damage done (CoC 1.0.2 - Mod v1.3.25)

### ISSUE THREAD

**Issue by Darth-Cthoras** [Kitteh6660/Corruption-of-Champions-Mod#379]
Earlier fix at https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/283 is apparently not solving the issue. Just used FoxFire a bunch just now, 0 damage reported each time, despite causing varying amounts of actual damage. Could this be reporting LUST damage? FoxFire is found in the M. Attack menu during combat and is gained from the Enlightened Nine Tails perk (Kitsune transformation series, 9 tails). When used in combat, it says it does (0) damage - and yet if you watch enemy HP, it can be very, very powerful indeed.

**Comment by CapriciousClowns** [comment]
yeah same thing happened to me 2 when I use corrupted fox fire and fox fire it only shows up 0 dmg whenever I fight a random monster

**Comment by bleachisback** [comment]
The build you are on came out 12 days before that commit. It doesn't have that fix in it.

**Comment by Darth-Cthoras** [comment]
*checks* ...oh. Well, now I feel dumb. Thanks for noticing that. XD
