### ISSUE TITLE
Unintentional 'Dickgirl' Status

### ISSUE THREAD

**Issue by Lanterngirl** [Kitteh6660/Corruption-of-Champions-Mod#385]
It used to be that a male character could have a hyper-feminine face without being classified as a dick-girl; but it's now impossible to have a boy with a hyper-feminine face that isn't classified as a girl with a dick. My character is still a boy, just with very feminine features! Can we please stop changing the gender title based on the masculine/feminine face score to avoid this in the future? I'd like to be able to play as a masculine looking girl who is still a girl or a feminine looking boy who is still a boy.

**Comment by CapriciousClowns** [comment]
Oh boy that sounds very confusing and complicated thing to do ya know I think that makes sense it kinda gives your whole gender thing a new perspective if you want you can be classified as a boy girl or herm and your appearance won't matter in who you are it'll be like your a male with a very feminine features or girl with masculine features or a herm that's well both I guess idk lol but that be cool like you will change genders if you end up with a dick or a pussie and stuff :p

**Comment by JustGregory** [comment]
@CapriciousClowns much words need punctuation please or else it gets tedious to read through all that because the human mind strains at finding sentences and understandable concepts in lengthy run-on sentences please do something about this.

**Comment by Kitteh6660** [comment]
What's your breast size? That could be the issue.

**Comment by Lanterngirl** [comment]
Hi! Sorry, I ended up losing my information for this account for... Pretty much an entire year??
Even when the breasts are completely flat, my male character is classified as a 'dick girl'.
I've even tried to get the androgyny perk to see if that fixes it, but no matter what, a high enough femininity score results in being called a dick girl.

I really just want my character to be a startlingly beautiful, feminine boy. He's not a girl who just happens to have a dick, he's a boy-- who is just jaw-droppingly beautiful.
I'm sorry if this sounds picky, though. 

Is there any way I can help out with this issue, by the way?
I love this mod, so I'd like to do anything I can to help it out.

**Comment by Stadler76** [comment]
According to https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/633fac0a9897309ec008cedfc99676844aad10c5/classes/classes/Creature.as#L2172
the female string is returned, if your femininity is 75 or higher. Maybe you want to reduce it to be just below 75?

**Comment by Stadler76** [comment]
Ok, I've just rewritten the two responsible methods, hoping they are more readable now:
```as3
public function mf(male:String, female:String):String
{
	if (hasCock() && hasVagina()) // herm
		return (biggestTitSize() >= 2 || biggestTitSize() == 1 && femininity >= 50 || femininity >= 75) ? female : male;

	if (hasCock()) // male
		return (biggestTitSize() >= 1 && femininity > 55 || femininity >= 75) ? female : male;

	if (hasVagina()) // pure female
		return (biggestTitSize() > 1 || femininity >= 45) ? female : male;

	// genderless
	return (biggestTitSize() >= 3 || femininity >= 75) ? female : male;
}

public function maleFemaleHerm(caps:Boolean = false):String
{
	switch (gender) {
		case GENDER_NONE:   return caps ? mf("Genderless", "Fem-genderless") : mf("genderless", "fem-genderless");
		case GENDER_MALE:   return caps ? mf("Male", "Dickgirl")             : mf("male", "dickgirl");
		case GENDER_FEMALE: return caps ? mf("Cuntboy", "Female")            : mf("cuntboy", "female");
		case GENDER_HERM:   return caps ? mf("Maleherm", "Hermaphrodite")    : mf("maleherm", "hermaphrodite");
		default: return "<b>Gender error!</b>";
	}
}
```

**Comment by Lanterngirl** [comment]
Oh! Thank you for taking the time to do that!
I have no idea what any of that means, I couldn't understand code if it was beamed into my head. Is this something I should be trying to edit in a file or some such?

I've been a bit sad that my lovely boy can't have the jaw-droppingly feminine description without going up into dickgirl status, but if it can't be helped, I'm sure I can deal with it. I really appreciate you taking the time to go through the code like that!

**Comment by Stadler76** [comment]
Simply check these two lines in my cleaned up `function mf(...)`:
```as3
if (hasCock()) // male
	return (biggestTitSize() >= 1 && femininity > 55 || femininity >= 75) ? female : male;
```
Since you've said, that you've reduced your tit size to flats, if should return "dickgirl" if your femininity is greater or equal to 75 (`femininity >= 75`)

Anyway: A 100% female face with flats and a dick would look more awkward, than like the 'lovely feminine boy' you're imagining IMHO.
