### ISSUE TITLE
Rubi’s Orifice Capacity: 224%

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#389]
May be it happens after i teased her serveral times in a row...
[Rubis Orifice Capacity 224.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/735437/Rubis.Orifice.Capacity.224.zip)

**Comment by Kitteh6660** [comment]
If you have debug enabled, Rubi would have extra 200% capacity.
