### ISSUE TITLE
Kiha affection is not shown

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#391]
CoC_1.0.2_mod_1.3.25.swf

She is friendly, next meeting leads to threesome with Hel

http://i.imgur.com/I8VttFc.png

[Kiha affection is not shown.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/737143/Kiha.affection.is.not.shown.zip)

**Comment by DullDanger** [comment]
Kiha Affection: -10% http://i.imgur.com/FeFOkrT.png
[Kiha affection -10.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/737833/Kiha.affection.-10.zip)

**Comment by Kitteh6660** [comment]
How did you get negative affection? Way to break the game!

**Comment by Stadler76** [comment]
Telling her, her cooking is yucky reduces her affection by 10%. AFAICS its the only way to reduce her affection.
