### ISSUE TITLE
poison bite don't works

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#393]
I get poison fangs from snake oil, but don't see any effects after succeful 'bite' attack (imp, goo-girl, phoenix, goblin warrior...)
CoC_1.0.2_mod_1.3.25.swf
[poison_fangs.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/740130/poison_fangs.zip)

**Comment by Stadler76** [comment]
Actually it reduces the monsters speed by 5-9 and its strength by 5-9 per application.

The problem is, that the ability blurb only tells you, that it succeeded, but not, what it did actually.

**Comment by Stadler76** [comment]
I've added a fix for that to PR #405
