### ISSUE TITLE
bimbo jojo not happening

### ISSUE THREAD

**Issue by Champion23467** [Kitteh6660/Corruption-of-Champions-Mod#394]
I am following all the directions on how to turn JoJo into a bimbo however for some reason it's not working which makes no sense at all because when it first came out it was working and now after the new update is not working at all

**Comment by Kitteh6660** [comment]
Did you ask Jojo to chase the thief or did you choose to bimbofy him yourself?

**Comment by Kitteh6660** [comment]
Closed due to the lack of response. If you can provide more details, I might be able to narrow it down.
