### ISSUE TITLE
Redemption: editbox over text

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#395]
![redemption](https://cloud.githubusercontent.com/assets/25287445/22508114/60258ab0-e8aa-11e6-9d32-cefb5386c233.png)

**Comment by border999** [comment]
I've noticed this issue as well, I know I should put a name in the box but the overlap is slightly bothersome since I don't know what the full line of Dialogue is then.

**Comment by DullDanger** [comment]
> What name do you give the new woman you and Marae have made?

**Comment by JustGregory** [comment]
Since it looks like a question is being asked by the text underneath the box, shouldn't the text box be on the next line?

**Comment by Stadler76** [comment]
@JustGregory wrote:
> Since it looks like a question is being asked by the text underneath the box, shouldn't the text box be on the next line?

Sure. And you're stating the obvious here ;-)

Heres the snippet to set the position of that box:
```as3
private function redemptionIII():void
{
	clearOutput();
	outputText("What name do you give the new woman you and Marae have made?");
	mainView.nameBox.text = "";
	mainView.nameBox.visible = true;
	mainView.nameBox.width = 165;
	mainView.nameBox.x = mainView.mainText.x + 5;
	mainView.nameBox.y = mainView.mainText.y + 3 + mainView.mainText.textHeight;
	menu();
	addButton(0,"Next",redemptionIIIGoName);
}
```

The problem is, that TextField.textHeight is buggy in recent versions of Flash. See http://stackoverflow.com/questions/18433889/finding-the-actual-text-height-as3

So you either have to use a nasty workaround to fix that issue or to set a fixed value there instead of using textHeight. e. g.:
```as3
mainView.nameBox.y = mainView.mainText.y + 3 + 20; // old: + mainView.mainText.textHeight;
```

**Comment by JustGregory** [comment]
>Sure. And you're stating the obvious here ;-)

I do that, sometimes. Hey, I'm human -- more or less. ;-P

**Comment by DullDanger** [comment]
Same code in nameDatHelspawn() works as it should:
![helspawn](https://cloud.githubusercontent.com/assets/25287445/22664076/e4afeddc-ecd0-11e6-9807-df84cceed409.png)

**Comment by Stadler76** [comment]
I guess, I got the problem: In the function `menu()` the outputText is flushed to the output and in scenes, where it works without issues the call to `menu()` is before the textbox is being positioned, but not in `redemptionIII()`. Can't test that right now, but moving the call a few lines up should do the trick.
