### ISSUE TITLE
Wearing goo armor prevents "Follow..." and "All Your..." achievements

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#397]
CoC_1.0.2_mod_1.3.25.swf

I received them only when put on another armor.

**Comment by PrestonLaw** [comment]
Honestly, it's kind-of-sort-of working as intended.  I mean, Valeria is a follower, but she's not an in-camp follower until you take her off.

I'll let Kitteh rule on this one, though.

**Comment by Stadler76** [comment]
In terms of code you just need to replace (in `classes/classes/Scenes/Camp.as`)
```as3
if (flags[kFLAGS.VALARIA_AT_CAMP] == 1) counter++;
```
with
```as3
if (flags[kFLAGS.VALARIA_AT_CAMP] == 1 || player.armor == armors.GOOARMR) counter++;
```
But, like @PrestonLaw stated, this may be intended, hence I'm not touching it.

**Comment by Kitteh6660** [comment]
Will be fixed.
