### ISSUE TITLE
Removing minimal lust from Shouldra

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#400]
I ignored Shouldra and she gave me 50 minimum lust, after clicking 'Folowers', 'Shouldra', 'Back', 'Back' minimal lust becomes zero.

[Shouldra_lust_removing.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/755742/Shouldra_lust_removing.zip)

**Comment by Kitteh6660** [comment]
Pretty sure you need to do sex with her to remove the minimum lust.

**Comment by PrestonLaw** [comment]
Talking also removes minimum lust as well.
