### ISSUE TITLE
Anzu commit breaks build due to missing flag

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#414]
The commit acc9624ac6dbef0c6e82b9ae86edbbdcc3e5ba0d causes the build to fail with the following errors:

[mxmlc] Corruption-of-Champions-Mod\classes\classes\Scenes\Dungeons\AnzuPalace\AnzuScene.as(475): col: 21 Error: Access of possibly undefined property ANZU_TIMES_SEXED through a reference with static type Class.
    [mxmlc]
    [mxmlc]                     if (flags[kFLAGS.ANZU_TIMES_SEXED] == 0) {
    [mxmlc]                                      ^
    [mxmlc]
    [mxmlc] Corruption-of-Champions-Mod\classes\classes\Scenes\Dungeons\AnzuPalace\AnzuScene.as(496): col: 31 Error: Access of undefined property catchAnal.
    [mxmlc]
    [mxmlc]                     addButton(0, "Anal Catch", catchAnal, null, null, null, "Have Anzu stuff you anally. \n\nNOTE: This is a REALLY long scene.");
    [mxmlc]                                                ^
    [mxmlc]
    [mxmlc] Corruption-of-Champions-Mod\classes\classes\Scenes\Dungeons\AnzuPalace\AnzuScene.as(845): col: 17 Error: Access of possibly undefined property ANZU_FEEDING_COUNTER through a reference with static type Class.
    [mxmlc]
    [mxmlc]                     flags[kFLAGS.ANZU_FEEDING_COUNTER]++;
    [mxmlc]                                  ^
    [mxmlc]

**Comment by Kitteh6660** [comment]
Should be fixed.
