### ISSUE TITLE
Lethice First Battle Bugs/Help Question

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#415]
I killed the Minotaur that comes prior to the first battle, and got faced with an empty text box. Screenshot of it: http://prntscr.com/ee7j3v

Both Fight and Consort, when clicked on, displayed text. It seemed unique to post-dealing with the Minotaur (and I say post-dealing as in choosing to kill or release lust on the Minotaur).

I assume this is caused by my 100 Corruption, as when I'm not corrupted, it displays fine.

--

Second issue is after you beat her in battle, just that there's a bit of broken text that reads (!Unknown subject in "himher"!). Screenshot: http://prntscr.com/ee7jx2

Don't know if these are already known, tried skimming the other issues posted but didn't see it. Apologies if this is a repeat!

**Comment by Stadler76** [comment]
Actually the scene text for corruption 90+ isn't written, when you're about to encounter Lethice:
```as3
public function encounterLethice():void {
	if (player.cor < 90)
		goFight();
	else {
		menu();
		addButton(0,"Fight",goFight);
		addButton(1,"Consort",joinHer);
	}
}

private function goFight():void
{
	outputText("<i>“So be it.”</i> Lethice rises from her throne, pacing pensively back and forth. Wings unfurl from behind her back, casting you into the darkness of her demonic shadow. <i>“You seek a fight with the Queen of Mareth, and you shall have one.”</i> With feline grace, she launches herself dozens of feet into the air, flips forward, and snaps her wings out to catch her midair. <i>“My pets! My lovelies! Watch what this mortal’s foolishness earns " + player.mf("him","her") + "!”</i>");
	outputText("\n\nScattered applause breaks out as Lethice wings around to engage you.");
	// [...]
}
```

**Comment by Foxwells** [comment]
Ah, all right. I am not too good at navigating this coding, especially since there's no search, so I wasn't able to find that x3 Maybe it should be removed until it's written...?

**Comment by Foxwells** [comment]
Hm, sorry to bump/double post, but I've kiiiinda picked up that people are allowed to write scenes to possibly be implemented? Is this true? And if so, where would I go to find more information on this/submit something? I may or may not have something in mind for this~

Coding would NOT be an issue for me, btw :p AS is very similar to C#, the latter of which I know, so I pretty much know what's going on with this all.
