### ISSUE TITLE
I can only destroy items in inventory

### ISSUE THREAD

**Issue by sars1492** [Kitteh6660/Corruption-of-Champions-Mod#418]
Hello, I'm using Mozilla **Firefox v. 51.0.1** on **Linux** Fedora 25. 

Original CoC by Fenoxo (v 1.0.2) is going without problems in my browser, but I have issue with this mod. I tried CoC 1.0.2 - Vanilla+ Release 2, I used first Canine Pepper from farm without problems from inventory, but after it, It gives me only option to destroy a item after clicking it without shift. I've tried everything but I can only destroy items from inventory. 

Sorry for my bad English. I'm not a native speaker.

**Comment by Kitteh6660** [comment]
Press Shift key. This should unstick the flag.

**Comment by sars1492** [comment]
Unfortunatelly It doesn't work :(. It works only for the first item. Every next items I can only destroy. I tried to use right and left shift, Caps etc. No change. 

I have idea than I turn off this feature in source code and compile again. What source code file contains this feature?

**Comment by Kitteh6660** [comment]
Inventory.as but please don't make a pull request to remove it, unless you put an alternative. There's still the time when you want to get rid of junk items.

**Comment by brrritssocold** [comment]
@Kitteh6660 @Stadler76 This can be closed as a fix was merged.
