### ISSUE TITLE
De-Bimbo Sophie Rathazul Chat Error

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#421]
Small thing, there seems to be a broken value in the conversation with Rathazul about de-bimboing Sophie. http://prntscr.com/ehhw2o

> **You await _getGoodPost()_ further clarification**, but the old rat just stands there, staring off into space. Coughing politely, you reacquire his attention, causing him to jump.

I do not know if this happens with other bimbo'd characters, as Jojo can't be de-bimbo'd and I haven't bimbo'd anyone else. It might be worth checking that this isn't an issue with other de-bimbo chats.

**Comment by Stadler76** [comment]
Shouldn't be. Actually its a coders joke on only appears in silly-mode:
https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/dda21ec98a4818a31e79e37e69725364dfbeb57c/classes/classes/Scenes/NPCs/Rathazul.as#L957

**Comment by Foxwells** [comment]
Whoops. I forgot I had silly mode even on.
