### ISSUE TITLE
lottie is not interactable in gym

### ISSUE THREAD

**Issue by CarbonComixx** [Kitteh6660/Corruption-of-Champions-Mod#423]

**Comment by Foxwells** [comment]
Can you provide more information? Such as, what interactions you've had with her thusfar, the version you're playing, a screenshot, etc?

**Comment by BelshazzarII** [comment]
Seems that one of the more recent updates added an impossible check for lotte's appearance in TelAdre.as

**Comment by Foxwells** [comment]
How is it an impossible check? It hooks up right from what I've read.

**Comment by Kitteh6660** [comment]
Should be fixed in latest build (pre1). If not, re-open this issue.
