### ISSUE TITLE
[Suggestion] Include more children for AP

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#424]
Right now the AP child formula is this:

> childPerformance += (flags[kFLAGS.MINERVA_CHILDREN] + flags[kFLAGS.BEHEMOTH_CHILDREN] + flags[kFLAGS.MARBLE_KIDS] + (flags[kFLAGS.SHEILA_JOEYS] + flags[kFLAGS.SHEILA_IMPS]) + izmaScene.totalIzmaChildren() + isabellaScene.totalIsabellaChildren() + kihaFollower.totalKihaChildren() + emberScene.emberChildren() + urtaPregs.urtaKids() + sophieBimbo.sophieChildren() + (flags[kFLAGS.TAMANI_NUMBER_OF_DAUGHTERS] / 4));

However, that discludes a lot of possible children: Amily, Jojo/Joy, Sophie non-Bimbo, Ember Eggs (if I read right), Heila, Beniot, Cotton, Edryn, probably others I'm forgetting. I'm listing what someone mentioned on the Wikia. I imagine if Anzu becomes capable of impregnating you, he'll be accidentally skipped over as well. So, my suggestion is pretty much just to add these into the pool. I'm not sure if Jojo/Joy counts litters or children since I've never had children with Jojo/Joy, but if the latter, it could probably have a divider like Tamani. If Lynette children were to be added, she should probably get one too.

This could possibly make AP a bit more bountiful than intended, but I don't know of a legitimate reason to not include them. It gives me the impression that they were just forgotten. If there's something I'm missing, though, feel free to inform me.

**Comment by Kitteh6660** [comment]
Non-bimbo Sophie is already included.

A single litter would be treated as 1 child for ascension points.

There will be a refactor so instead of a single line, it will be moved to its function for readability as well as making it easier to add for future NPCs supporting pregnancy.
