### ISSUE TITLE
feeder perk

### ISSUE THREAD

**Issue by aedionevahuoy** [Kitteh6660/Corruption-of-Champions-Mod#426]
seems to disappear after going somewhere, without any message

**Comment by Foxwells** [comment]
Where exactly do you go? And what actions do you take prior? Do you use LaBova or ProBova? And what's your corruption? It goes away if your corruption drops below 20.

**Comment by aedionevahuoy** [comment]
corruption at 85, used labova, clicked desert, disappeared after without message, happens when going anywhere

**Comment by Foxwells** [comment]
Hm... I can't seem to mimic your issue. My perk menu still shows I have it. How do you know it disappeared? Does it disappear from your perk menu, and does the CoCEd also say it's gone?

Just to be clear, you're playing the mod, right? If so, what version? I'm personally using the 1.4 3/05 snapshot, so IDK if it's fixed and you're just using an old version :p

**Comment by aedionevahuoy** [comment]
i'm using the newest as well. the game doesn't say anything but it disappears from the perk menu.

**Comment by Foxwells** [comment]
Aight, making sure, you won't believe the amount of people using the vanilla build on the wiki asking why mod stuff isn't there/working--

Again, does the CoCEd also say it's gone? It might be a visual thing and it's invisibly there. If not, there's definitely something awry with your character that's making it go away, could be species or other statuses or your settings or... a lotta stuff. There's a lot of possible variables. Could you possibly attach a copy of your save file? It'd make it a lot easier to diagnose.

**Comment by aedionevahuoy** [comment]
coced says its gone, all feeder related buttons are gone as well. it might have something to do with how much I've been messing around with coced since I just really want everything in the game
[y_u_no_allow_github.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/852609/y_u_no_allow_github.zip)

**Comment by Foxwells** [comment]
You have the Bro Body perk, which gets rid of the Feeder perk :-) Check it out for yourself [here](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/PlayerEvents.as#L566).

`			if (player.findPerk(PerkLib.BroBody) >= 0) { //Bro checks
				player.removeStatusEffect(StatusEffects.Feeder);
				player.removePerk(PerkLib.Feeder);
			}`

**Comment by aedionevahuoy** [comment]
k thanks, couldn't find in perks and there wasn't any message so I assumed it was a problem
