### ISSUE TITLE
[Forest] Corrupt Jojo Slave -> 40% truffle encounter rate in forest and no tentacles

### ISSUE THREAD

**Issue by PowerOfVoid** [Kitteh6660/Corruption-of-Champions-Mod#43]
```var chooser:Number = rand(5);```
Possible states:
0: 20%
1: 20%
2: 20%
3: 20%
4: 20%

```if (chooser == 3 && rand(2)) chooser = rand(3);```
Possible states:
0: 23.3%
1: 23.3%
2: 23.3%
3: 10%
4: 20%

``` if (chooser == 1 && kGAMECLASS.monk >= 2) { /* blah, roll on 0, 2, 3, 3 */ } ```
States:
0: 29.1%
1: 0%
2: 29.1%
3: 21.6%
4: 20%

```if ( /* Jojo isn't here */ ) { if (chooser >= 1) chooser++; } ```
States:
0: 29.1%
1: 0%
2: 0%
3: 29.1%
4: 21.6%
5: 20%

But 4 and 5 are both truffles, so:

Goblin/Imp: 29.1%
Jojo: 0% (expected)
Tentacles: 0% (!!!)
Bees: 29.1%
Truffle: 41.6% (!!!)

Personally, I think the forest encounter should default to bee-girls, but maybe that's just me.

**Comment by PowerOfVoid** [comment]
The forest should probably be switched over to a ```choice[choice.length] =``` system like the Lake

**Comment by PowerOfVoid** [comment]
Oh, huh, I guess that number is also dependent on you not being in a "harvesting wood" phase.

Still should be fixed, though, IMO.

**Comment by Kitteh6660** [comment]
There will be some refactor in encounter mechanisms to be cleaner.

It'll use switch and case. Also, it will use the choices array.

Eventually, all zones will use the new mechanism. I just levelled up my OCD skills!
