### ISSUE TITLE
how to bimbofie izma

### ISSUE THREAD

**Issue by Xel101stars** [Kitteh6660/Corruption-of-Champions-Mod#435]
as put in the new pre releses you can bimbofie izma but it dosent say how we can do this only that she can be and that you can unbimbo her

**Comment by Foxwells** [comment]
Likely in the same way you would Bro-fie her.

**Comment by Xel101stars** [comment]
how would u do that does the option pops up when your have he item or...

**Comment by Foxwells** [comment]
Idk my dude, I don't broify characters. You probably just need the Bimbo Liquor and DeBimbo in your inventory. Have you considered looking at her code? [This](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/NPCs/IzmaScene.as#L1746) is how she is brofied. You can then find out how to un-broify her from there.

**Comment by border999** [comment]
There doesn't actually appear to be any coding that involves bimboing Izma. At that link in the box above press Ctrl+G and type 'bimbo' in the resulting box. The only results are for reacting to a bimbo Sophie.

**Comment by Foxwells** [comment]
.... Oh, they wanted to bimbo Izma as in make her a bimbo, not just undo broify. Wow. My reading comprehension is great.

Yeah no bimbo Izma isn't a thing. However, she can be given Bimbo Liquor and DeBimbo to undo Broify, which will result in her becoming a Futa. Unsure of how Bimbo it makes her look, haven't tried it.

**Comment by Kitteh6660** [comment]
There's no bimbofy. The option is just there to revert Izmael back to Izma.
