### ISSUE TITLE
Suddenly not recognizing saves

### ISSUE THREAD

**Issue by imthebigguy** [Kitteh6660/Corruption-of-Champions-Mod#438]
I still have all my saves in sol format, and they're in the same localhost folder as they've always been, all I've done is download the newest mod version. Loading from file doesn't work or display errors, it just displays a blank game window and the next button.

**Comment by imthebigguy** [comment]
Forgot to mention, creating a new game and saving it does nothing as far as I can tell, on the next game open it isn't there.

**Comment by Kitteh6660** [comment]
Did it also happen for 1.3.25 after downloading the prerelease?

If it happens in vanilla then it might have something to do with Flash issues.

**Comment by PrestonLaw** [comment]
I had a similar problem to this.
I was forced to stop saving my games to file; I believe it's because of some new security requirements that Chrome imposes on Flash.
You may want to try using Firefox.  If that doesn't work, then your only option will be using the other save method, as far as I can tell.

**Comment by DullDanger** [comment]
Try standalone flash player (projector): http://www.adobe.com/support/flashplayer/debug_downloads.html

**Comment by brrritssocold** [comment]
Had the save issue when I symlinked my `AppData` folder.
Adobe products hate symlinks.

Is this issue resolved?

Had the save issue when I symlinked my `AppData` folder.
Adobe products hate symlinks.

**Comment by brrritssocold** [comment]
@Kitteh6660 @Stadler76 Can this be closed as there has been no answer for over 2 months?
(Sorry to use the @, but since i do not have collaborator status, i cannot close issues)
