### ISSUE TITLE
Pay to play? April Fool's Joke?

### ISSUE THREAD

**Issue by WhyNotV2** [Kitteh6660/Corruption-of-Champions-Mod#445]
I've been playing CoC off and on for a while now and have unlocked a fair amount of content. Today I tried going to the Volcanic Craig as I have done many many times before and it stated to do so I had to "Get the Extreme Zones DLC to be able to visit Glacial Rift and Volcanic Crag and discover the realms within!

You can purchase Extreme Zones DLC for $4.99. Would you like to purchase it now?"

So previously available content is not Pay to Play?

**Comment by Kitteh6660** [comment]
It's definitely April Fools. Try to check out and the "paywall" will be disabled.

**Comment by WhyNotV2** [comment]
Thank you. I was getting pissy at it :(  Guess the joke was on me!!!

**Comment by FabianValladares** [comment]
LOL damitt i fell for the joke, I was like wth for real?? bs lol
