### ISSUE TITLE
Scrolling jumps when switching to the flash player window

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#447]
Open any scene with scrolling (long camp screen for example): http://i.imgur.com/z2iPapz.png
Press down arrow on keyboard (nothing happens) and scroll with mouse to the end: http://i.imgur.com/3kescsu.png
Switch to another program and back to game - scrolling jumped to 1 line from top: http://i.imgur.com/9MSsCbX.png

CoC_1.0.2_mod_1.4_pre2.swf, standalone flash player.
[scroll_bug.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/888614/scroll_bug.zip)

**Comment by Kitteh6660** [comment]
It probably has something to do with your hardware.

Have this happened in vanilla?
