### ISSUE TITLE
Lethicite Usable Item Function

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#448]
Does the usable item Lethicite (as dropped by Precilla) actually have a function? I tried searching the coding for anything and found nothing, and anyone I bring the Lethicite to won't interact with it.

**Comment by Kitteh6660** [comment]
It will eventually be usable for making lethicite staff, which is no longer obtainable since placeholder Lethice was replaced with canon Lethice.

**Comment by Foxwells** [comment]
Aaahh, that's what happened to the Lethicite Staff... Wondered why I could never find it...

Anyways. All right, thank you!
