### ISSUE TITLE
Drider Incubus venom don't wears off

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#449]
[Drider_Incubus_venom.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/888799/Drider_Incubus_venom.zip)

**Comment by Foxwells** [comment]
Can you give any more information? The file save you sent is post-game, so it's kind of hard to test all the possible variables that could go into a lasting stat reduction, as people can't replicate what you did.

**Comment by DullDanger** [comment]
I was biten by drider incubus in Stronghold, his venom permanently lowered my strength by 30 - gym don't rise it.
[before_drider_incubus.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/907277/before_drider_incubus.zip)

**Comment by Stadler76** [comment]
The gym doesn't raise your strength anymore, if its at 90+
You could either raise it with the combat guide from Izma or with Vitality Tincture.

**Comment by Foxwells** [comment]
^ I personally spam Vitality Tinctures...

Anyways, do we have confirmation that Kinariel's Venom should be removed if you finish the battle before it wears off? I tried scouring the codes, but couldn't find any reference for how long it should last, let alone special removal conditions.

**Comment by Kitteh6660** [comment]
It turns out that the strength regained was incorrectly using value 1 instead of value 2. This will be corrected with a commit. Unfortunately, for saves affected by this, you'll need to raise your strength through usual methods again.

The second value is the amount of strength lost from venom.
