### ISSUE TITLE
Sand Witch

### ISSUE THREAD

**Issue by DuskFantail** [Kitteh6660/Corruption-of-Champions-Mod#45]
I just defeated a sand witch and there was no option available to me after her defeat

**Comment by PowerOfVoid** [comment]
How high was your lust?

**Comment by DuskFantail** [comment]
Male penis bellow 30

**Comment by DuskFantail** [comment]
It went to the she is defeated scene and then no options appeared I had a full inv of 5 but not enough lust to perform any sexual actions I will try and recreate it again for you

**Comment by DuskFantail** [comment]
![coc](https://cloud.githubusercontent.com/assets/12084250/7668401/aa21c184-fc79-11e4-85fb-fab42f44c355.png)

**Comment by DuskFantail** [comment]
Thanks Kitteh

**Comment by PowerOfVoid** [comment]
I think you generally need to have a certain amount of lust in order to initiate victory rape scenes.
