### ISSUE TITLE
450

### ISSUE THREAD

**Issue by CapriciousClowns** [Kitteh6660/Corruption-of-Champions-Mod#450]

**Comment by Foxwells** [comment]
Yeah, can confirm that this happens. Sometimes creating a new character then reloading an old save in the prison gets the buttons back, but I haven't done enough testing to figure out what of that works. I'm also really unsure as to what specifically causes this blank screen; Regardless of my stats or what action I took, it'd just randomly trigger.

Can do further testing/code diving in... a little while. It might be best to temporarily remove the prison considering that this breaks the game though.

**Comment by Kitteh6660** [comment]
The prison is presently a can of worms that is in complete need of overhaul.
