### ISSUE TITLE
Dragging swf file into browser just re downloads a copy of the swf file

### ISSUE THREAD

**Issue by Devin-Beesley** [Kitteh6660/Corruption-of-Champions-Mod#451]
thought I'd drop a line and let you know that trying to open the file results in another copy being downloaded.

**Comment by Kitteh6660** [comment]
What browser are you using? Do you have Flash Player installed? It may not play well with Chrome.

**Comment by Devin-Beesley** [comment]
I have flash installed and I have tried to open it in both chrome and
windows edge. It used to load fine and then it just stopped working
completely.

**Comment by Kitteh6660** [comment]
You'll have to drag it to the tabs. Open a new tab that will play the file.

CoC currently doesn't have loading bar.

**Comment by Devin-Beesley** [comment]
dragging the file into anew tab is what is causing the re-download
