### ISSUE TITLE
Isabella: blank appearance screen

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#454]
CoC_1.0.2_mod_1.4_pre2.swf

[Isabella_no_appearance.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/896418/Isabella_no_appearance.zip)

**Comment by Foxwells** [comment]
I think that's just you. http://www.filedropper.com/idkman

![screenshot_106](https://cloud.githubusercontent.com/assets/15647033/24820155/480185fc-1bad-11e7-9427-ce48477d4c7f.png)
![screenshot_107](https://cloud.githubusercontent.com/assets/15647033/24820154/48005132-1bad-11e7-9ecb-fd11a3e2b68a.png)

**Comment by DullDanger** [comment]
I think it may be pregnancy caused that: http://i.imgur.com/g0sv6pk.jpg
Now it shown as before: http://i.imgur.com/QpsHKDu.png
