### ISSUE TITLE
Can't Play in Browser

### ISSUE THREAD

**Issue by Siegward** [Kitteh6660/Corruption-of-Champions-Mod#456]
This is probably stupidity on my part. I dragged the .swf file into the browser and it just downloaded itself again.

**Comment by Foxwells** [comment]
Download the file and use SWF File Player. Browsers are generally a bad idea for playing downloadable Flash games.

**Comment by Kitteh6660** [comment]
Dragging onto the browser content will cause it to attempt to download itself. Instead, drag it onto the tabs.

Or use a standalone flash player, like Foxwells said.
