### ISSUE TITLE
Another method for playing in-browser

### ISSUE THREAD

**Issue by PrestonLaw** [Kitteh6660/Corruption-of-Champions-Mod#457]
This isn't really an issue, but... I had difficulties with playing the SWF directly in-browser a while back, and I ended up finding a method to play by embedding the SWF file inside a webpage, as follows:

<html>
<head>
<title>Corruption of Champions</title>

</head>
<body>
<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=20.0.0.306" WIDTH="100%" HEIGHT="100%" id="Corruption of Champions" ALIGN="">
<PARAM NAME=movie VALUE="CoC_1.0.2_mod_1.3.25.swf">
<PARAM NAME=quality VALUE=high>
<PARAM NAME=bgcolor VALUE=#000000>
<EMBED src="CoC_1.0.2_mod_1.3.25.swf" quality=high bgcolor=#333399 WIDTH="100%" HEIGHT="100%" NAME="CoC_1.0.2_mod_1.3.25.swf" ALIGN="" TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED></OBJECT> 
</body>
</html>

Putting that code into a HTML file and opening it in-browser will run the game with no fiddling (note that you have to provide the version number in 3 places).  You may want to provide such an HTML page by default, especially since I've never had problems with this solution.

**Comment by PrestonLaw** [comment]
Um, I think it ate the HTML code I pasted.  Let's try that again.

`<html>`
`<head>`
`<title>Corruption of Champions</title>`
`<!-- Three places to replace the version number. -->`
`</head>`
`<body>`
`<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=20.0.0.306" WIDTH="100%" HEIGHT="100%" id="Corruption of Champions" ALIGN="">`
`<PARAM NAME=movie VALUE="CoC_1.0.2_mod_1.3.25.swf">`
`<PARAM NAME=quality VALUE=high>`
`<PARAM NAME=bgcolor VALUE=#000000>`
`<EMBED src="CoC_1.0.2_mod_1.3.25.swf" quality=high bgcolor=#333399 WIDTH="100%"` `HEIGHT="100%" NAME="CoC_1.0.2_mod_1.3.25.swf" ALIGN="" TYPE="application/x-shockwave-flash"` `PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer">
</EMBED>
</OBJECT>`
`</body>`
`</html>`

**Comment by Foxwells** [comment]
Don't browsers block Adobe Flash player now, or is that exclusive to web pages? IDK anymore, I stopped using Google Chrome and my current browser actually allows Flash.

Well, anyway. I do think this is a useful idea for those who don't want to download an SWF-compatible program. May I ask for a screenshot of how the file looks, though? I'm not sure width being 100% would do well at first glance. It might just be that I'm not as familiar with how ActionScript is processed, but that sounds like it'd awkwardly stretch out the game as opposed to width being auto.

~I also err to the side of vh over % units, but again, I don't know how that'd look and that's a me thing.~
