### ISSUE TITLE
Goostuffed pregnancy duration bug

### ISSUE THREAD

**Issue by ReisenII** [Kitteh6660/Corruption-of-Champions-Mod#459]
When the PC gets stuffed with goo (by valeriaGooRapeII), she gets the faux goo pregnancy that blocks other pregnancies until cleared.
The goostuff duration depends on the StatusEffects.GooStuffed and goes between 10 + rnd(300), while PregnancyStore.PREGNANCY_GOO_STUFFED, 500  is used as blocking value for other pregnancies.
If the player has pregnancy multiplier, the duration of PregnancyStore.PREGNANCY_GOO_STUFFED can go to 0 before the StatusEffects.GooStuffed do (because it's unaffected by pregnancy multiplier), enabling the player to get impregnated while still in goostuffed status.

I tested with multiplier 5, bit 2 is enough to replicate the bug (since 500/2 can be > 10 + rnd(300)
This also is a CoC vanilla bug

(I could add an image showing double pregnancy, but it would appear the same as my other worm pregnancy Issue)

I *think* it can be fixed by setting the PregnancyStore.PREGNANCY_GOO_STUFFED to at least 2000 (or a value that can always outlast the StatusEffects.GooStuffed duration even at maximum pregnancy speed)

**Comment by brrritssocold** [comment]
- What was the version of the game?
- Do you have a save file that can be used to reproduce the issue?

**Comment by ReisenII** [comment]
Sure thing. I used to test the latest Revamp version (1.4.1) and my vanilla CoC character (since the bug comes from the vanilla, it shouldn't matter). She has pregnancy speed 5.

I tested again and made 4 separate saves for each step. i don't know how to add files here, so i used my Dropbox.
https://www.dropbox.com/s/leimgb67ivrv45u/Goopreg%20issue.zip?dl=0
The first save is my character with no pregnancy and Valeria equipped
The second save is right after the Valeria + Goo threesome. CoCEd show she has 495 hours left on her pregnancy and 204 of Goostuffed status.
After waiting about 495/5 hours, I saved again. The pregnancy show 0h left while goostuffed status show 98.
The last save is after having vaginal sex with Izma right after the third save. Butt pregnancy still has 0 hours goo, while the PC is vaginal pregnant with Izma's children. Also on the Appearance it shows both pregnancy at once.

Due to the random value of the goostuffed status, it's not 100% replicable everytime. In the past I edited my vanilla game version by making the goo pregnancy last 2500 hours, to make sure the goostuffed status never outlast the "normal" pregnancy even with maximum pregnancy speed, and that seemed to fix the issue. I can comment that without it, it happened quite a lot of times to have double pregnancy with 5 speed, hence why I reported the issue to begin with.

**Comment by brrritssocold** [comment]
Thanks, i will take a look.
Btw. [you can attach files to issues](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Note however, once uploaded the file cannot be deleted (although you can remove the link to it from the comment / issue).
This will keep the files available in the future, in case they are needed again.

**Comment by ReisenII** [comment]
I tried to attach the zip file, but it gave me an error.

**Comment by Stadler76** [comment]
@ReisenII commented 5 hours ago
> I tried to attach the zip file, but it gave me an error.

GitHub doesn't accept .zip-Files in comments, although is says so. However, you can attach .gz or .tar.gz-Files. You can create these archive-types with [7-Zip](http://www.7-zip.org/). If its a single file, you can directly `gzip` it (Right-click the file, choose 7-Zip → Add to archive, choose `gzip` from the compression method dropdown). If you want to compress multiple files or a folder, its a two step compression:
1. Select the files or the folder, then 7-Zip → Add to archive and then `tar` from the compression method dropdown.
2. Now, that you have a single `.tar`-file, just compress it by choosing `gzip` from the compression method dropdown.

**Comment by ReisenII** [comment]
So it wasn't seeing things when it's clearly written "zip" there.
I'll add those files here so I can remove the file from Dropbox, in case they are again needed.

[Preg issue.tar.gz](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/956631/Preg.issue.tar.gz)

**Comment by brrritssocold** [comment]
That is odd. Seems to work for me....
I'm using chrome, in case that matters.
[like-this.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/956693/like-this.zip)

**Comment by Stadler76** [comment]
nope, doesn't work in Chrome either. I can't even reupload your example zip
