### ISSUE TITLE
 no pics for some enemies

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#462]
imp warlord, Priscilla, goblin shaman (pic appeares after i won: http://i.imgur.com/eNy4sia.jpg )
CoC_1.0.2_mod_1.4.swf - it's 3MB smaller than pre2
[Giacomo_worms.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/910409/Giacomo_worms.zip)

It looks like this happens during the exploring, in forest encounters i just have seen imp overlord and Priscilla.

**Comment by Foxwells** [comment]
Priscilla seems fine in the mountains, broke elsewhere. Special imps are broken all together, whether you beat them or not and regardless of location. Regular imp is fine. Goblin Assassin seems to be broken while exploring/forest, still researching. Pics appears once defeated, per usual.

On an off-hand note, why is my level 1 champion encountering special goblins/imps in the wasteland? x: Is their appearance based on stats over level now?

**Comment by Stadler76** [comment]
This bug was introduced, when merging the PR for the encounters API.
I've already posted a reply to https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/452#issuecomment-292722138 but so far no reaction from @aimozg
