### ISSUE TITLE
Cannot find "MinoMutual" scene from the source code

### ISSUE THREAD

**Issue by KWJG** [Kitteh6660/Corruption-of-Champions-Mod#463]
I found a scene after defeating a minotaur, button named "MinoMutual", but cannot find it from the source code. The source code zip file is not in the final state?

I failed to identify the condition of the scene.

The scene starts with the following paragraph:

Every muscle in the minotaur’s body bulges as he pumps his swollen horse cock with reckless abandon. Despite the evident vigor with which he strokes the tower of meat he calls his penis, there is no hope for release in his eyes. He just sits there, mindlessly stimulating himself, unable to bring himself to climax but also unable to stop himself from trying.

**Comment by DullDanger** [comment]
https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/Areas/Mountain/MinotaurScene.as

**Comment by KWJG** [comment]
Found a real bug.

When I have spider ovipositor, the Lay Eggs button overrides the MinoMutual button, blocking the scene.

**Comment by Foxwells** [comment]
I don't think it's a bug. If you look at the code, it has an order to replace buttons, and is intentionally set up that way.

**Comment by KWJG** [comment]
Now we have three lines for the buttons, so this makeshift code should be fitted so. I see no reason for those scenes being mutually exclusive.

**Comment by Foxwells** [comment]
Fair enough-- though, it still isn't a bug. It's intentionally designed, and just hasn't been adjusted to the increased capabilities of the Mod. I do support a suggestion to move the buttons, though ^^

**Comment by DullDanger** [comment]
> Your knee-length, draconic dick {strain / strains} for a tight hole to fill while your loose cooter wants something big and drooling stuffed into its drooling opening. Even now you feel the wetness of your drooling loins salivating and you can’t help but wonder if there is another minotaur around here somewhere to make a !Unknown subject in “playername”! sandwich.

**Comment by Stadler76** [comment]
**\*sigh\*** https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/430#issuecomment-288881757

Looks, like I have to work on a fixes batch soonish ...
