### ISSUE TITLE
Erlking Doesn't Give Gems

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#464]
Run from the Erlking, intentionally get caught, receive no gems despite it saying I should. Also seems to happen when I just naturally get caught (37 speed in that test).

Zip of my file: 
[no erlking gems.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/911743/no.erlking.gems.zip)

![rip erlking](https://cloud.githubusercontent.com/assets/15647033/24887257/0ec995e8-1e20-11e7-8e85-c6340d09f3b4.gif)

**Comment by Stadler76** [comment]
Not tested, but the following diff should fix this:
```diff
diff --git a/classes/classes/Scenes/Areas/Forest/ErlKingScene.as b/classes/classes/Scenes/Areas/Forest/ErlKingScene.as
index 3e94c159..577f1e07 100644
--- a/classes/classes/Scenes/Areas/Forest/ErlKingScene.as
+++ b/classes/classes/Scenes/Areas/Forest/ErlKingScene.as
@@ -467,6 +467,7 @@ package classes.Scenes.Areas.Forest
 			var gemFind:int = 10 + rand(15);
 
 			outputText("<b>You found " + gemFind + " gems.</b>\n\n");
+			player.gems += gemFind;
 
 			var selector:int = rand(4);
 
```
