### ISSUE TITLE
Lustzerker Gained Typo

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#466]
> After drinking to the last drop another hip flask of firewater you starts to feel weird maybe slight unpleasant feeling inside your body. Like many tiny flames cursing inside your veins making you ponder what just happening with your body. Remembering about salamanders natural talent to enter berserk-like state you **quessing** it’s could be that.

Should be _guessing_.

**Comment by Stadler76** [comment]
The whole grammar needs fxing. My current suggestion:
> After drinking <del>to</del> the last drop of another hip flask of firewater you start to feel <ins>a</ins> weird<ins>,</ins> maybe slight<ins>ly</ins> unpleasant feeling inside your body.  Like many tiny flames cursing inside your veins making you ponder what<ins>s</ins> just happening with your body.  Remembering about salamanders natural talent to enter <ins>a</ins> berserk-like state, you <del>quessing</del> <ins>guess</ins> <del>it</del><ins>that</ins> <del>could</del><ins>should</ins> be <del>that</del><ins>it</ins>.

**Comment by Foxwells** [comment]
tbh I didn't really read it, I wouldn't have even noticed the typo had it not been a stroke of luck.

As a loser who does nothing but write, I'm gonna push forth this as a suggestion for a re-write:

> After finishing another hip flask of firewater, you start to feel a weird, slightly unpleasant feeling inside your body-- like many tiny flames are coursing through your veins. You ponder just what's happening to you when you remember that salamanders have natural talent for entering a berserk-like state. You guess that this feeling is what it is.
