### ISSUE TITLE
New Idea for coc revamped 

### ISSUE THREAD

**Issue by CapriciousClowns** [Kitteh6660/Corruption-of-Champions-Mod#469]
i played some other text based games and fun games ;) 
but there was this status where if you get cum soaked a lot it sticks to your character and you could use it as an outside force to make enemies more vulnerable to lust from the stench of smell of all the cum so I wonder if that be a cool stat effect or perk for combat and ya know I still wonder to myself we all know sensitivity is a bad think and it kinda makes you more susceptible to lust increase but why not make it a good thing? like good and bads like high sensitivity would mean your more aware of the things around you like heightened senses and the downside to it would be more lust vulnerability while having low lust means you can be less vulnerable it would make ya ice cold or tempered to handle those things cool idea am I right? ;D

**Comment by Xel101stars** [comment]
i like this idea since there isn't a lot surrounding the sensitivity stat

**Comment by Kitteh6660** [comment]
Actually, I want to think about removing Sensitivity stat entirely.
