### ISSUE TITLE
How long will the Glacial minotaur be updated?

### ISSUE THREAD

**Issue by xuhosen** [Kitteh6660/Corruption-of-Champions-Mod#473]
Look forward to Glacial minotaur

**Comment by Foxwells** [comment]
[](https://trello.com/b/jhFIdMvt/corruption-of-champions-revamp-mod)

Tl;dr: It's not going to happen according to the Trello.

**Comment by Kitteh6660** [comment]
If someone writes that. The Glacial Rift could do with a more encounter.

Also please don't post asking when content will come out. This isn't the right place.
