### ISSUE TITLE
Change silk armor collection text

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#476]
![screenshot_132](https://cloud.githubusercontent.com/assets/15647033/25066079/a2697f92-21e1-11e7-9c49-d970ff573f6e.png)

I _really_ don't think "ejaculates" is what is meant to be here. Maybe "exclaims" or "announces"?

**Comment by Kitteh6660** [comment]
That was like that in the vanilla.
