### ISSUE TITLE
Lethicite Ring has no effect

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#478]
![screenshot_133](https://cloud.githubusercontent.com/assets/15647033/25066618/e9b6ca08-21f0-11e7-9bf1-b15c71f89afb.png)

It's worth mentioning I have 0 min lust without the ring. But why does this ring add minimum lust anyway? Shouldn't it boost corruption or something? We already have the Crimstone Ring.

**Comment by Foxwells** [comment]
Update: Issue seems to be that its effect is listed as "1" (aka the minimum lust raiser) instead or "9" or "CORRUPTION"

[https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Items/JewelryLib.as#L74](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Items/JewelryLib.as#L74)

**Comment by Stadler76** [comment]
Well, you could possibly change the `effectID` to `CORRUPTION` but the magnitude is still at 0%.

**Comment by Foxwells** [comment]
If my theory is correct, the "0" is representative of how many hours it takes before corruption raises by 1. You would put the value at "10". But I have no idea how to modify compiled files, so I can't test that >>;;

**Comment by Stadler76** [comment]
As of now its corruption gain / 10 per hour:
https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/633fac0a9897309ec008cedfc99676844aad10c5/classes/classes/PlayerEvents.as#L66

**Comment by Foxwells** [comment]
Heck, that's where that code is. Ty!

Then we'd need the sum of 0.1, right? Since it's meant to give 1 point of corruption per 10 hours. Just set the magnitude as 1. 1/10=0.1
