### ISSUE TITLE
Dog-Morph and Fox-Morph max stats are wrong

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#48]
In description +int -tou:

    Dog-Morph and Fox-Morph
    Speed: +10
    Intelligence: +10
    Toughness: -10

In code -int no tou:

            if (dogScore() >= 4 || foxScore() >= 4) {
                maxSpe += 10;
                maxInt -= 10;
            }

**Comment by Kitteh6660** [comment]
The guide was outdated. I've updated it.

The new code is intended.
