### ISSUE TITLE
Lethicite Armor corruption gains possibly miswritten?

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#482]
The gains themselves aren't bugged ~~to my knowledge~~ but I found this curious bit of code:

```
if (player.cor < 50) dynStats("cor", 0.05);
if (player.cor < 80) dynStats("cor", 0.05);
```

It seems rather... silly to have cor<50 specified considering the gains are the same thing, unless I'm missing something.

**Comment by Stadler76** [comment]
They stack.
If your corruption is below 50 both conditionals are true, so `dynStats("cor", 0.05)` is called twice.

**Comment by Foxwells** [comment]
Ah, I see. So it becomes 0.1... Ty!

~~off to edit the wiki page for that, then~~
