### ISSUE TITLE
statbars do not fit in their place

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#484]
![goo-girl_stats](https://cloud.githubusercontent.com/assets/25287445/25099031/346f4eba-23c4-11e7-9dab-e751cdd3f72f.png)

After consuming  4 wet clothes.

CoC_1.0.2_mod_1.4.1.swf
[goo-girl_stats.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/926313/goo-girl_stats.zip)

**Comment by FelipeASimoes** [comment]
Did it stick forever? From my experience it tends to fix itself in the next scene transition, when the UI is redrawn.

**Comment by Foxwells** [comment]
It means your stats haven't updated to their lowered maximum. Fight something, they'll fix.

**Comment by brrritssocold** [comment]
@DullDanger Can you confirm that this is still the case with 1.4.2?

1. loaded `goo-girl_before.sol`
2. consumed 5 wet cloth from inventory

Could not reproduce the issue.
Please also see #540 as to what information can be helpful for bug reports.

**Comment by Stadler76** [comment]
Diff that workarounds that issue:
```diff
diff --git a/classes/classes/Scenes/Camp.as b/classes/classes/Scenes/Camp.as
index 6088e38f..3a86bec1 100644
--- a/classes/classes/Scenes/Camp.as
+++ b/classes/classes/Scenes/Camp.as
@@ -780,7 +780,7 @@ private function doCamp():void { //Only called by playerMenu
 	}
 	
 	//Menu
-	
+	dynStats();
 	menu();
 	addButton(0, "Explore", exploreEvent, null, null, null, "Explore to find new regions and visit any discovered regions.");
 	addButton(1, "Places", placesEvent, null, null, null, "Visit any places you have discovered so far.");
```

The dynStats()-call would be a no-op but it fixes the stat boundaries.

**Comment by DullDanger** [comment]
CoC_1.0.2_mod_1.4.3.swf
Аfter consuming 4 Wet Clothes and returning to main screen results are same as on first screenshot. Next WC fixes it:
![20170503010](https://cloud.githubusercontent.com/assets/25287445/25638956/982f2bb0-2fa3-11e7-90c1-4b0cb400ecfc.png)
