### ISSUE TITLE
Purity Ring is not working

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#49]
Looks like it is supposed to have handler in PlayerEvents.timeChange(), like lethicite ring, but it have not.

**Comment by openaz** [comment]
According to implementation, Purity ring decreases lust gain in similar way as e.g. Berzerking skill.

**Comment by Netys** [comment]
It description says:
reduces minimum libido
makes it harder for you to get turned on
Slowly purifies the wearer over time

Lust gain reduction is only one of 3 declared effects.

**Comment by Kitteh6660** [comment]
This will be fixed in 1.2.11.
