### ISSUE TITLE
Can there be a way to stop/reverse Jojo's transformation?

### ISSUE THREAD

**Issue by Gekuu9** [Kitteh6660/Corruption-of-Champions-Mod#501]
I had no idea that that option would caused Jojo to drink the potion and turn into Joy, and my last autosave was too late to go back and change it. I really don't want Jojo to change, but I can't seem to find any way to stop it at this point. Could you add some way to stop Jojo from drinking the potion, or a way to reverse the transformation after he turns into Joy?

**Comment by Foxwells** [comment]
You could use CoCED to stop it-- though I do support a way to de-bimbo Jojo, because I have been in your spot an annoying amount of times.

**Comment by Foxwells** [comment]
You may want to close this now that there's an option to change your mind on bimbo'ing Jojo
