### ISSUE TITLE
[Refactor] Convert appearanceDefs into class

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#507]
Convert `appearanceDefs.as` into a class so i can be used as such.
This will be cleaner than importing the same file all over the place.

- [ ] convert `appearanceDefs.as` to class
- [ ] update references to use the `appearanceDefs` class

**Comment by Stadler76** [comment]
Well, that would be a shitload of refactoring, replacing every single
```as3
if (player.lowerBody == LOWER_BODY_TYPE_WHATEVER)
```
with
```as3
if (player.lowerBody == AppearanceDefs.LOWER_BODY_TYPE_WHATEVER)
```

Actually I can live with having that include in all those files, that use them.

**Comment by brrritssocold** [comment]
You are right.
How about a compromise?
```
package classes
{
	/**
	 * Class for appearance constants.
	 * Instead of inserting the same ~500 lines in every file that references it.
	 */
	public class AppearanceDefs
	{
		include "../../includes/appearanceDefs.as";
	}
}
```

Use the class for new content and replacing `LOWER_BODY_TYPE_WHATEVER` with `AppearanceDefs.LOWER_BODY_TYPE_WHATEVER` whenever code is touched that uses the 'old' style?
Eventually all code will be replaced and the imports can be removed (i can hope, can't i?).

On that note, what about moving some consts out of `appearanceDefs.as`?

e.g.:
`VAGINA_LOOSENESS_*` into `VaginaClass`

**Comment by brrritssocold** [comment]
Superseded by #995
