### ISSUE TITLE
Cant bimbo jojo

### ISSUE THREAD

**Issue by gamer20002** [Kitteh6660/Corruption-of-Champions-Mod#511]
I cant find the option to bimbo jojo after I tell him to guard the chest, is it only posible to do it the other way?

**Comment by Stadler76** [comment]
Yes. You have to tell him to catch the thief.

**Comment by gamer20002** [comment]
they should change the wiki then, it says thay you can bimbo him afterwards

**Comment by Foxwells** [comment]
@Kitteh6660 Close this, it isn't an issue (except for one on the Wikia)
