### ISSUE TITLE
[Very minor] Roxanne cock size issue

### ISSUE THREAD

**Issue by ReisenII** [Kitteh6660/Corruption-of-Champions-Mod#516]
Roxanne has her demon magic cock that increase in size for each 4 hours she has no sex, and if the PC lose her drinking contest she use said cock to ream his/her butt with a different scene depending on her size or PC's butt size.

The inconsistency that I found is that Roxanne's cock size gets resetted before the actual sex scene occur.
The only actual consequence of this is simply that the game use the wrong cock area to check for stretch chances; always 30 instead of the intended 30+(flags[kFLAGS.ROXANNE_TIME_WITHOUT_SEX]/4) because said flag is always set to 1 by the time the sex scene play.
Considering her size can go up to theoretically infinite (most likely resetting when over 105, still minotaur-tier size), I found a little weird my PC couldn't consistently gets stretched out when she was about at looseness 3, hence I looked up in the code and found this.

This is a really minor inconsistency I found while (literally) fucking around with my PC's butt, it's otherwise almost invisible to players that are not anal gaped fixated as ~~my PC~~ me. I still thought it was worth reporting. I fixed it in the past by moving flags[kFLAGS.ROXANNE_TIME_WITHOUT_SEX] = 1; from the end of the drinking contest to the end of the actual 3 sex scenes.

**Comment by brrritssocold** [comment]
Will take a stab at this.

**Comment by Foxwells** [comment]
@Kitteh6660 Not an issue/already fixed, close this

**Comment by ReisenII** [comment]
Like I said it's really minor, I meant that the flag ROXANNE_TIME_WITHOUT_SEX gets set to 1 during function roxanneDrinkingContest() instead at the end of the sex scene, this means when any of the three (losing) sex scenes occur, the chance of the player ass to get stretched will always be calculated with a cock size of 30 because in
`player.buttChange(Math.floor(30+(flags[kFLAGS.ROXANNE_TIME_WITHOUT_SEX]/4)),true,true,false);`
the flag is 1. I thought that wasn't intentional from the guy who wrote this to begin with so I reported

It's minor, nothing gamechanging, so I understand why it's not treated as an issue. I'll close this as I know how to fix it myself.

**Comment by brrritssocold** [comment]
**Please re-open**

After stepping through the code i can see there is a race condition due to that asynchronous handling of events / user interaction:

1. Loss occurs and scene is selected
2. Selected scene function is attached to a 'Next' button
3. Flag is reset with `flags[kFLAGS.ROXANNE_TIME_WITHOUT_SEX] = 1;`
4. Later, the player presses 'Next' button, at which point the flag has already been reset.
