### ISSUE TITLE
Compiling gives me almost 600 warnings ...

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#527]
Compiling the latest build give me 593 warnings. I know, that CoC Source is spaghetti code, but does that mean, that it has to be slammed into my face with almost 600 warnings?

I'll file a partial fix in a min, that removed those from appearanceDefs.as.
Those deprecated appearance constants will probably left there, so they'll never be reused and its valid usage of them to update old saves, that still have them set.

**Comment by Stadler76** [comment]
I'll look into the 3 deprecated `kFLAGS` later, probably with a `modSaveVersion` bump

**Comment by brrritssocold** [comment]
You can use the compiler flag `-show-deprecation-warnings=false` to suppress the warnings.
In flashdevelop: *Project*->*Properties..*.->*Compiler Options* tab, *Additional Compiler Options* field.

The deprecated metadata tags were added in #519, with the hope that people will not use deprecated code. As noted in the PR, flashdevelop will highlight deprecation warnings.
