### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by Foxwells** [Kitteh6660/Corruption-of-Champions-Mod#536]
Hey if I wanted to make sprites for those who don't have any, how would I add them to a pull request? I love making CoC-style sprites but IDK where they're stored. Only how to extract them z_z

**Comment by Stadler76** [comment]
Theres a card on the CoC Revamp Trello board.

btw: care to join the CoC Mods discord server? Lots of staff from CoC Revamp and Xianxia are there:
**Discord Server:** https://discord.gg/R25MZEx

**Comment by Foxwells** [comment]
I can't do anything on the Trello even with an account, so I've been kinda ignoring it ^^;;

Uh, sure, no idea who Xianxia is there but I want to contribute more and could always use advice on what I'm doing~ o:
