### ISSUE TITLE
Jojo meditation after night outside of camp

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#55]
Night spent outside of camp (forest kitsune mansion for example) doesn't propertly resets Jojo daily meditation benefits.

**Comment by openaz** [comment]
Time shift needs to be implemented. E.g. like this http://pastebin.com/UrbRWZiu (note: untested)

**Comment by openaz** [comment]
Pastebin updated again. Starting new game after timeshift implementation didn't started on day -3 or 0.
