### ISSUE TITLE
Wolf Peppers

### ISSUE THREAD

**Issue by CrypticCadam** [Kitteh6660/Corruption-of-Champions-Mod#557]
While exploring the Glacial Rift, I have encountered Amarok several times and defeated them several times, but Amarok still has not dropped a wolf pepper. I am playing on the newest release for the modded version.

**Comment by ReisenII** [comment]
Just taking a wild guess, but the drop for Amarok miss the weight number.
`this.drop = new WeightedDrop(consumables.WOLF_PP);`
Any other WeightedDrop instances have a number in the function value, like for Minerva
`this.drop = new WeightedDrop(consumables.PURPEAC, 1);`

I may be very wrong of course, but I too tried to farm the Wolf peppers with no luck, so I looked up in the code to check the drop rate and I couldn't find it.

**Comment by Foxwells** [comment]
Ah shit, my bad. The Amarok was the first NPC I ever made, so I was bound to overlook something :joy: [This](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/560) should patch that up.
