### ISSUE TITLE
Goblin rape scene repeated

### ISSUE THREAD

**Issue by Suikoi** [Kitteh6660/Corruption-of-Champions-Mod#570]
CoC 1.0.2 mod 1.4.3
When I try raping a goblin with the "CorruptDick" option it just shows the regular "DickTooBig" scene

**Comment by ReisenII** [comment]
Indeed those tho buttons leads to the same sex scene
`//Corrupt too big scene`
`if (player.cockArea(player.biggestCockIndex()) > monster.vaginalCapacity() && (player.cor > 80 - player.corruptionTolerance() || player.findPerk(PerkLib.Sadist) >= 0 || flags[kFLAGS.MEANINGLESS_CORRUPTION] >= 1))`
`addButton(2, "CorruptDick", manRapesGoblinTooBig);`
`//Regular too big scene`
`if (player.cockArea(player.biggestCockIndex()) > monster.vaginalCapacity())`
`addButton(1, "DickTooBig", manRapesGoblinTooBig);`

In all Goblin encounters there is a function named rapeAGoblinCorruptTooBig() supposedly intended for the "Corrupted too big dick" but it's never called
