### ISSUE TITLE
Recent Travis builds always fail

### ISSUE THREAD

**Issue by Stadler76** [Kitteh6660/Corruption-of-Champions-Mod#586]
All recent Travis builds fail with the same error. Seems, like a configuration issue:
![2017-05-04 20_09_07-job 281 1 - kitteh6660_corruption-of-champions-mod - travis ci](https://cloud.githubusercontent.com/assets/13157984/25718378/18f1e0f4-3106-11e7-9c1f-15377e090f2b.png)

At the time of writing for example my PR #585 just compiles fine without any warnings. I've even cleaned the project before creating a debug build, but Travis still fails on it.

**Comment by brrritssocold** [comment]
working on it.

**Comment by Stadler76** [comment]
Closing, because its fixed by merging PR #588
