### ISSUE TITLE
Somewhat game-breaking bug (rarely encountered)

### ISSUE THREAD

**Issue by wyvvern** [Kitteh6660/Corruption-of-Champions-Mod#6]
Glad to hear you have a new hard drive!

This one has to do with maximum lust and the way you refactored the camp menus. [camp.as]

If the player has:

1) No followers they can have sex with to reduce lust
2) Either are numb because they drank minotaur blood or cannot masturbate because they're a centaur (and they don't have the centaur items from the farm to allow them to)

They're permanently stuck in camp. Game over.

When you switched from the old method (function pointers/string variables) to control what buttons are on the menu you left the flavor text with all the conditions but didn't re-add those checks to your button removal code.

```
	if (player.lust >= 100) {
		removeButton(0);
		removeButton(1);
	}
```
Presumably you're fiddling with this code already since you mentioned increasing maximum lust on the forums. I just did this to quick fix it in my own mirror:

```
	var canFap:Boolean = player.findStatusAffect(StatusAffects.Dysfunction) < 0  && (flags[kFLAGS.UNABLE_TO_MASTURBATE_BECAUSE_CENTAUR] == 0 && !player.isTaur());

	if (player.lust >= 100 && canFap) {
		removeButton(0);
		removeButton(1);
	}
```

**Comment by Kitteh6660** [comment]
The maximum lust of 100 was actually a magic number. I've completely refactored to call for maxLust() which will return 100, or 120 if you have bro/bimbo/futa brains perks.

Thank you, I've added canFap. This will come in next snapshot.
