### ISSUE TITLE
Explore regions not being logged

### ISSUE THREAD

**Issue by bqbum** [Kitteh6660/Corruption-of-Champions-Mod#604]
### Overview
	Exploration of locations not being logged. It could be an issue with CocED since that is the only way I know of to see how many times you have visited a location, however I do not have this problem with mod v1.4.2 so something is happening with this specific version(1.4.3).

	
### Game version
	CoC_1.0.2_mod_1.4.3
	
### Expected behaviour
	If you go to a region like desert it counts and keeps track of how many times you do it.
	
### Actual behaviour
	It lists explorations as stuck at 1. I can change the number with the editor, but it has no effect (encounters that are supposed to happen at a certain number of explorations don't)

### Steps to reproduce the issue
1. Use cocED to check the number of explorations at a certain location (there may be better ways to do this)
2. Travel to that location several times.
3. Check the editor again and it should be the same number (usually 1 unless you tried editing it)

If possible, attach a save file that reproduces the issue.
[bug save.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/984125/bug.save.zip)

**Comment by brrritssocold** [comment]
Tried exploring the forest and desert, checked the save with [minerva](https://mariani.life/projects/minerva-air/), `TIMES_EXPLORED_*` flags are incremented.

Exploring the forest and desert with provided save, flags are incremented as expected.
Creating a new game with 1.4.2 and editing exploration with CoCEd has no effect.

Looking at the CoCEd source, it tries to read the explore counters from e.g. `exploredDesert` property,
but those are no longer used in CoC-Mod, as the counters were moved to flags e.g. (`TIMES_EXPLORED_DESERT = 2299`).

Please file an issue with CoCEd.

**Comment by bqbum** [comment]
> Please file an issue with CoCEd.
I passed the word along: https://github.com/tmedwards/CoCEd/issues/19
Though he doesn't know when he'll get around to it. Until then everything should work except the main locations tab in the editor.

**Comment by Foxwells** [comment]
CoCED hasn't been updated in a long time. I wouldn't expect much.

**Comment by brrritssocold** [comment]
Since this isn't a issue with CoC-Mod itself, can we close this issue?
