### ISSUE TITLE
[Development] Request 'Adminster Issues' permission for Sonar

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#607]
@Kitteh6660 Would it be possible to get the permission `Administer Issues` for the [Corruption-of-Champions-Mod sonar project](https://sonarqube.com/dashboard?id=org.github.Kitteh6660%3ACorruption-of-Champions-Mod)?

This would allow me to mark issues as 'false positive' and 'won't fix'.

1. Visit the sonar project page
2. Select 'Administration' -> 'Permissions'
3. Search for the user (brrr) in the search field (to the right of 'All', 'Users', 'Groups')
4. Select 'Administer Issues' and 'Browse' (Required according to the tooltip) for the user

**Comment by Kitteh6660** [comment]
Done.

**Comment by brrritssocold** [comment]
Thank you, much appreciated.

**Comment by brrritssocold** [comment]
Have the permissions been changed?
I no longer seem to have the 'Administer Issues' permission, so I am unable to set issues as false-positive.

**Comment by Kitteh6660** [comment]
Should be done again now. Let me know.

**Comment by brrritssocold** [comment]
It works, thank you.

**Comment by Stadler76** [comment]
Nice. IMHO Sonar is way too nitpicky as of now.
