### ISSUE TITLE
I'm not sure, but...

### ISSUE THREAD

**Issue by assassin0223** [Kitteh6660/Corruption-of-Champions-Mod#61]
I don't know if this is a bug, but you should check if currently wearing the red bodysuit w/ the proper appearance does anything.
Cause I haven't noticed Raphael visiting me.
I have the proper appearance and the red bodysuit worn, but also had the scene of him hiding in the barrel.
So I'm not sure if there's a bug. But since this is a bug fixing thread, I'll just leave a link to another bug report that I accidently posted in the vanilla coc issues page.
https://github.com/herp-a-derp/Corruption-of-Champions/issues/752

**Comment by Netys** [comment]
After barrel scene he wouldn't visit you anymore regardless off your choise. There are no way to finish training after it.

**Comment by PowerOfVoid** [comment]
``` flags[kFLAGS.RAPHEAL_COUNTDOWN_TIMER] = -2; ```
I believe that this leads to the orphanage content in Tel'Adre.

Of course... I just raped the douchebag and turned him over.  Because, in Corruption of Champions, that's what you do to people you are mildly annoyed at.

**Comment by openaz** [comment]
After barell, you have possibility to visit Raphael in Tel'Adre in orphanage (homes->orphanage in Tel'Adre). But only if you covered him and if you still fit Raphael's requirements. If you didn't covered him, you can't access him anymore. If you don't fit his requirements, you'll get note about it when you'll try to access orphanage. Anyway, barell scene is the last visit from him and now, it's your turn to pay him visits.

**Comment by assassin0223** [comment]
I see, not a bug, but unfinished content. Thank you for the information. In the end, I edited the flags to make me meet Raphael again and this time he visited me. Weird how I wasn't visited the first time.
