### ISSUE TITLE
Wolf Pepper nonfunctional

### ISSUE THREAD

**Issue by Lucariofan843** [Kitteh6660/Corruption-of-Champions-Mod#612]
### Overview
	Nothing happens when Hero uses wolf pepper.
	
### Game version
	CoC_1.0.2_mod_1.4.4
	
### Expected behaviour
	The wolf pepper transforms the hero into a wolf-morph with each use.
	
### Actual behaviour
	A blank page is shown with the option to continue and no effects have been applied.

### Steps to reproduce the issue

Consuming the item, either obtained from the enemy or by COCedit.

**Comment by Foxwells** [comment]
This is long addressed, buddy: [https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/609](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/pull/609)

**Comment by Lucariofan843** [comment]
Ooops, thanks for letting me know XD

**Comment by Locksoli** [comment]
I'm still having a problem with it too... How do I fix it?

**Comment by Foxwells** [comment]
![screenshot_144](https://cloud.githubusercontent.com/assets/15647033/26012152/363c8e98-3719-11e7-8433-ad4781d1d958.png)

![screenshot_145](https://cloud.githubusercontent.com/assets/15647033/26012158/40e35e80-3719-11e7-8dbe-ddfed018e0f8.png)

The secret is being patient for the next update.

**Comment by brrritssocold** [comment]
1. As mentioned, wait for the next release
2. Get the code and build it yourself
3. I proposed #499, but there was no interest
