### ISSUE TITLE
Lumi can't enhance Fox Jewels

### ISSUE THREAD

**Issue by DaniDipp** [Kitteh6660/Corruption-of-Champions-Mod#617]
### Overview
When the player has a Fox Jewel in their inventory, the "Fox Jewel" button is not displayed in Lumi's "Enhance" menu.
	
### Game version
1.0.2_mod_1.4.4
	
### Expected behavior
Display of disabled buttons for every enhance-able Item with enabled buttons for every available ingredient in the player's inventory.
	
### Actual behavior
If one or multiple Fox Jewels are present in the player's inventory, the button get's overridden by the button for Golden Seed.

### Steps to reproduce the issue
1. Acquire a Fox Jewel
2. Find Lumi's Laboratory
3. Open the "Enhance" menu

### Where to find the bug
The bug is located in this section of Lumi.as:
```as
if (player.hasItem(consumables.FOXJEWL)) {
	addButton(1, consumables.FOXJEWL.shortName, lumiEnhanceGo, consumables.FOXJEWL, undefined, undefined);```
} else {
	addDisabledButton(btn++, consumables.FOXJEWL.shortName);
}
```

The `addButton` function of line 138 should be called with `btn++` instead of `1` for the first argument so the next button is in the correct position:
```as
addButton(btn++, consumables.FOXJEWL.shortName, lumiEnhanceGo, consumables.FOXJEWL, undefined, undefined);
```

[LumiBug - Issue#617.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/998256/LumiBug.-.Issue.617.zip)

**Comment by DaniDipp** [comment]
I should add that I don't know if my solution solves the problem because I can't figure out what I do wrong when building the project, but I don't see why it wouldn't work. (Famous last words of a programmer)

**Comment by Foxwells** [comment]
Pushed a fix as part of mutationsupdate.

**Comment by DaniDipp** [comment]
Thanks!
