### ISSUE TITLE
Missing back button in Rathazul's armor menu

### ISSUE THREAD

**Issue by openaz** [Kitteh6660/Corruption-of-Champions-Mod#62]
This is more likely Feature request as this issue occurs also in original CoC.

When asked Rathazul to make an armor, new menu is shown with selection of possible crafts. As there's no back button, player can't change mind.

```diff
Index: Rathazul.as
===================================================================
--- Rathazul.as	(revision 2169)
+++ Rathazul.as	(working copy)
@@ -550,6 +550,7 @@
 	if (player.hasKeyItem("Divine Bark Plates") >= 0) {
 		addButton(6, "D.Bark Armor", craftMaraeArmor, true);
 	}
+	addButton(14,"Back",rathazulWorkOffer);
 }
 
 private function craftSilkArmor():void {

**Comment by PowerOfVoid** [comment]
Likely relates to #40

**Comment by openaz** [comment]
Oh, didn't saw it. Sorry. Same as #40.

**Comment by openaz** [comment]
I have checked #40 and also the commit. It's almost same, not exactly. According to commit, it's possible to return from screen, where you're selecting what to craft (Followers -> Rathazul -> Armor -> Dragonscale) and that works fine. This issue is about returning from screen, where you're selecting from what to craft (Followers -> Rathazul -> Armor). So it's very similar, yet not exactly same.
