### ISSUE TITLE
Infinite Distance between Player and Encounter

### ISSUE THREAD

**Issue by Altamis** [Kitteh6660/Corruption-of-Champions-Mod#623]
### Overview
	After fighting a Sand Trap in the Desert and using the Climb context button to increase distance I proceeded to shoot it three times with my bow to win the fight. After the battle further encounters have my character starting out with the caption "You’ll need to close some distance before you can use any physical attacks!" and the fight button replaced with Approach. Pressing the Approach button does nothing, and does not seem to close the distance leading to an infinite loop and effectively making physical combat impossible.
	
### Game version
	1.0.2_mod_1.4.4

### Expected behaviour
	Ability to close distance and engage in combat.

**Comment by brrritssocold** [comment]
Could not reproduce, need more information.

**Comment by Altamis** [comment]
For some reason every time I attempt to post a zip file of the save it says the file type is not supported, have tried to zip it up with both winrar and 7zip with no luck, so I have uploaded the save to a file hosting site and will provide the link.

http://www.filehosting.org/file/details/665329/rrnXzPkCYhNDDEpZ/coc_1.0.2_mod_save_1.4.4

Have only seen this happen once, and the exact steps taken led to the issue involved the Sand Trap I believe, or at least that was the last normal encounter I had before the infinite distance issue popped up.

**Comment by Altamis** [comment]
After some experimentation I have discovered the file created during "save to file" does not load. It just goes to a blank screen, and every time I have tried, it will not allow me to post zip files in the comments. I keep getting the error message file type not supported even after zipping it up as a .zip archive using both winRAR and 7zip.

So will attempt again to post the save files taken directly from my SharedObjects folder for Flash Player and will link them from a file hosting site.

http://www.filehosting.org/file/details/665333/K0fdy0xMXWKUfwKZ/CoC%20save.zip

**Comment by Altamis** [comment]
![coc capture](https://cloud.githubusercontent.com/assets/28678466/26036619/7554f7da-38a6-11e7-837b-efbfc6ac107d.PNG)

Here is a screen capture of what is occurring, the fight button is replaced with Approach, and no amount of clicking it will close the distance to allow for melee combat. Even after multiple encounters.

**Comment by BelshazzarII** [comment]
this issue is probably caused by a bugged Mimic encounter. Did you encounter a mimic, click the "fight" button a few times and it didn't do anything?

If you did, you stacked a bunch of "knocked back" status effects on your character. Can you go to the debug menu(type D E B U G) and take a screenshot of the screen you get when you click "dump effects"?

You should get a bunch of instances of KnockedBack. You can probably fix it just by Approaching a bunch of times, but I'll whip up an on-save-load fix.

**Comment by OfficerHonk** [comment]
I also encountered this issue, but I found that if you encounter a sandtrap and run away from it, it fixes it.
