### ISSUE TITLE
I always encounter the same events, no matter how often I explore.

### ISSUE THREAD

**Issue by just-a-pervert** [Kitteh6660/Corruption-of-Champions-Mod#624]
### Overview
	When I explore at the lake, I have in over a hundred tries not once encountered a fight. 
	
### Game version
       1.0.2_mod_1.4.4
	
### Expected behaviour
	I should run into fights with lake inhabitants or cultists or at least the shark girl!
	
### Actual behaviour
	I've encountered The Boat, The Sword and the Ruined Village each once, The Farm 3 times and since then it is ALWAYS either Walk on the Beach, Equinum, Whisker fruit, or Rathazul, often several times in a row!

### Steps to reproduce the issue
    Select "Explore", then "Lake".

[coc.save.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/998951/coc.save.zip)

**Comment by Foxwells** [comment]
Just a quick question: What is your level/what do your stats look like?

~~I'm in the middle of things or I'd open your save~~

**Comment by just-a-pervert** [comment]
![screenshot - 14 05 2017 - 00 07 54](https://cloud.githubusercontent.com/assets/28678569/26029608/6d1e0150-3839-11e7-8cc5-463195904a17.png)

**Comment by Foxwells** [comment]
You can't encounter Goo-girls, Green Slime, or the Fetish Cultists (I think you need to clear the Factory for those) until you are higher level/have higher stats :-)

**Comment by just-a-pervert** [comment]
Is there really NOTHING else at the Lake? I seem to remember gaining at least one level there before venturing into the forest :|
