### ISSUE TITLE
Pure Jojo Sex menu dissappeared

### ISSUE THREAD

**Issue by KWJG** [Kitteh6660/Corruption-of-Champions-Mod#626]
I had a savefile with pure Jojo sex menu opened.

The sex menu appeared until version 1.4.2, but after version 1.4.3, the menu is gone like it didn't happened. Now I have to re-initiate the confrontation.

I read through the code (the zip attachment). The only checker for pure Jojo sex menu is the flag number 2311.

**Comment by DullDanger** [comment]
Same thing: #564

**Comment by Kitteh6660** [comment]
Unfortunately it seems that there were some refactors some time ago that changed the monk variable to Jojo status flag.

I don't know if that can be fixed, sorry. Your best bet is to go through the confrontation and you can easily re-unlock.

**Comment by Kitteh6660** [comment]
BTW this is going to be removed in 1.4.19 due to subpar writing. Sorry.
