### ISSUE TITLE
Is the Wolf Pepper functional + Thank you for previously!

### ISSUE THREAD

**Issue by Lanterngirl** [Kitteh6660/Corruption-of-Champions-Mod#629]
Hello there!! :>

I just picked up some Wolf Peppers from Hellhounds in 1.4.4-- but when I use them, it just leads to a blank page. When I click them again, it'll say that I can't use 'nothing'. Is this an issue on my end? I'd love to play around with some Wolf Peppers, but if they're not fully implemented, I understand! They don't appear in the debug menu, so I'm just wondering.

Also, I brought up an issue before about dickgirl status and was delighted to see a change came about from it! I'd like to say thank you very much for listening and thinking about it! If there's anything I can do in return, or any ways I could contribute to the game somehow, I'd love to know.

Much love!!

**Comment by Foxwells** [comment]
A fix has been pushed and merged. You just have to wait for the next release.

**Comment by Lanterngirl** [comment]
Ah, thank you very much! In that case, I'm sorry to have bothered you then!

Thank you for your patience!! :> <3
