### ISSUE TITLE
Weapon Merchant's inventory incomplete/unavailable?

### ISSUE THREAD

**Issue by emeraldzeta** [Kitteh6660/Corruption-of-Champions-Mod#630]
I have been browsing around for awhile trying to locate a explanation or solution to this issue, currently running v. 1.4.3. of the mod. 

Issue at hand: It appears to me that the Weapon Merchant in Tel'Adre doesn't sell all the weapons that's he is supposed to, like he does in the original game? Weapons missing would be ( going by the mod wiki ): 

Large Claymore, Huge Warhammer, Katana, Spear, Coiled Whip, Wizard's Staff, Spiked Gauntlets & Wingstick.

Weapons that ARE available:

Flail, Scimitar and Mace

Are these weapons missing on purpose or is this actually a bug? 

All and any answers are welcome.

**Comment by Foxwells** [comment]
a) Try not to rely on the wiki too much ATM. It's in serious editing and has a lot of scattered info.
b) Can you attach your save file and a screenshot of the bug?
c) Can you verify that this issue does *not* happen in 1.4.4?

**Comment by emeraldzeta** [comment]
a) noted
b) http://i.imgur.com/H6ih7bL.jpg <- screenshot 1.4.3
c) issue is resolved as of 1.4.4 all the weapons I listed and "Dagger" added to the merchant.
http://i.imgur.com/UJtD57g.jpg <- screenshot 1.4.4

**Comment by Foxwells** [comment]
Hmm... Well, if it's been resolved already, no need to worry too much about it. Close this, please ^^

**Comment by Stadler76** [comment]
PR #602 fixed that

~closing~
