### ISSUE TITLE
Error with charcter 'Etis'?

### ISSUE THREAD

**Issue by Wisper200** [Kitteh6660/Corruption-of-Champions-Mod#634]
### Overview
Character 'Etis' gives 1 dragonic cock instead of 3 tentacles

### Game version
	1.0.2_mod_1.4.4
	
### Expected behavior
	Playing as 'Etis' gives the PC 3 tentacle cocks
	
### Actual behavior
	PC has 1 dragonic cock

**Comment by Netys** [comment]
Fixed in #635
