### ISSUE TITLE
X-mas Elf bug

### ISSUE THREAD

**Issue by bdsmlodz** [Kitteh6660/Corruption-of-Champions-Mod#637]
### Overview
	Can't Unwrap Elf as a female.
	
### Game version
	e1.0.2_mod_1.4.4 + 1.0.2_mod_1.4.5
	
### Expected behaviour
	Proceed as a female and have Perk.
	
### Actual behaviour
	Req penis.

### Steps to reproduce the issue

1. Set date on 25 dec 
2. Start new game in Ingram
3. Go sleep
4. Choos "Unwrap Elf"

**Comment by Netys** [comment]
Fixed in #641

**Comment by bdsmlodz** [comment]
Yeah, there is Back button but is that means I can't have Perk until i grow penis?

**Comment by Netys** [comment]
Or wait for the update.

**Comment by bdsmlodz** [comment]
Ok, thx. You'r great!
