### ISSUE TITLE
impLordEncounter takes 2 hours

### ISSUE THREAD

**Issue by Netys** [Kitteh6660/Corruption-of-Champions-Mod#64]
Button "Next" after "A large corrupted imp crosses your path" text advances time 1 hour. And after combat end it advances again. This happens with all larger imps, bot not with level 1 basic imps.

This can cause auto-defeat if something unusual happens on time change.

Not entirely sure (spaghetti code...), but looks like it is caused by 

      doNext(camp.returnToCampUseOneHour);

in impLordEncounter / impWarlordEncounter / impOverlordEncounter, since basic imp encounter does not have this call.

**Comment by openaz** [comment]
This should do the trick.
```diff
Index: ImpScene.as
===================================================================
--- ImpScene.as	(revision 2169)
+++ ImpScene.as	(working copy)
@@ -1559,7 +1559,7 @@
 				flags[kFLAGS.CODEX_ENTRY_IMPS] = 1;
 				outputText("\n\n<b>New codex entry unlocked: Imps!</b>")
 			}
-			doNext(camp.returnToCampUseOneHour);
+			doNext(playerMenu);
 		}
 		
 		//IMP WARLORD

```
