### ISSUE TITLE
Katherine's training scene soft locks the game.

### ISSUE THREAD

**Issue by FinnChap** [Kitteh6660/Corruption-of-Champions-Mod#642]
### Overview
	When I got to the point in Kath's guard-training where you go to a lake, all the options are greyed out... I can't choose 'bath' or any of the sex scenes because her knot is still too large, and her training's not over.
	
### Game version
	1.0.2_mod_1.4.4
	
### Expected behaviour
	I think there should be a way to get out of the scene without sex or bathing.
	
### Actual behaviour
	No options are available, thus locking me in the scene.

### Steps to reproduce the issue

        1. Katherine has to have a big enough knot to be unable to pull out.
        2. Her training must not be complete to lock the bathing option.
        3. Scene where Kath and PC go to the lake must play.
[kathsoftlock.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1012647/kathsoftlock.zip)
(Just go to Kath's alley and it should play the lake scene)

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

**Comment by Netys** [comment]
Fixed in #641
