### ISSUE TITLE
Wolf Peppers in 1.4.5

### ISSUE THREAD

**Issue by CrypticCadam** [Kitteh6660/Corruption-of-Champions-Mod#666]
Hello, I have reported an issue a while ago regarding Wolf Peppers and their inability to drop from the giant wolf in the glacial plains, but as they do now drop, they are unable to be consumed.
When I eat a Wolf Pepper, the screen goes blank and it appears that the Wolf Pepper number doesn't go down. After I eat it again however, I am given the text "You cannot eat NOTHING" and the Wolf Peppers disappear from my inventory.
[New Compressed (zipped) Folder.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1016630/New.Compressed.zipped.Folder.zip)

I added a copy of my save

**Comment by Foxwells** [comment]
This has already been fixed... and had multiple bug reports already sent in... They're working o3o Here's a screenshot of proof for you:

![screenshot_150](https://cloud.githubusercontent.com/assets/15647033/26281446/2d71b4ec-3dbc-11e7-8acc-6729bab25f0c.png)

**Comment by CrypticCadam** [comment]
Okay, thanks!
