### ISSUE TITLE
izmael stuff

### ISSUE THREAD

**Issue by OCTOB3R** [Kitteh6660/Corruption-of-Champions-Mod#679]
### Overview
	After becoming a bro words not meant to be seen happens
	
### Game version
	CoC_1.0.2_mod_1.4.6b or whenever you could bro her
	
	In a joshing tone, you ask if that means he’s never been tempted to eat you !Unknown multi-word tag ""!.

“You?” Complete horror creases Izmael’s face. !Unknown multi-word tag ""!!Unknown multi-word tag ""!

**Comment by Foxwells** [comment]
May I ask for all references of this you can find? I'm going to work on fixing this, so some pointers of all the locations would be good ^^
