### ISSUE TITLE
Hunger Never Drops

### ISSUE THREAD

**Issue by qatar31** [Kitteh6660/Corruption-of-Champions-Mod#688]
### Overview
	Hunger never drops in realistic mode.
	
### Game version
	1.0.2_mod_1.4 using flashplayer 25
	
### Expected behaviour
	hunger drops after every action

### Actual behaviour
	Hunger never drops, always resets too 100 every round no matter what

### Steps to reproduce the issue
Going to write what caused the issue here, using the Valeria Sex option with a goo girl caused hunger to never drop. When reset to 0 using a save editor, it immediately spikes to 100 again and never drops

**Comment by Foxwells** [comment]
As discussed on Discord: You're goo-stuffed. This isn't a bug, you're just literally full. Please close this.
