### ISSUE TITLE
Showing Lust damage

### ISSUE THREAD

**Issue by Peterinox** [Kitteh6660/Corruption-of-Champions-Mod#697]
Is there a reason why the lust damage inflicted on the PC isn´t shown exept for some characters like Helia?
Else I would suggest to spread it to the other monsters. Here is the (rather complicated but working) part of the code:

var lust:Number = 20 + rand(10) + player.sens/10 + rand(game.helScene.heliaSparIntensity() / 10) + rand(player.lib/20) * (1 + (player.newGamePlusMod() * 0.2));
				game.dynStats("lus", lust);
				lust *= player.lustPercent() / 100;
				lust = Math.round(lust * 10)/10;
				outputText(" <b>(<font color=\"#ff00ff\">+" + lust + " lust</font>)</b>\n");

If someone comes up with another fancy solution I would happily adabt to that but else spread this piece ...
Maybe the exact value should be hidden in hardcore mode 
Thanks for any comments

**Comment by BelshazzarII** [comment]
main reason is people forget to output those values, really. There isn't a simple "takeLustDamage" function like there is takeDamage, and implementing it right now would be a bit of a pain in the ass since you'd have to check every monster for refactoring.

**Comment by Kitteh6660** [comment]
It's entirely possible but it will take some time. This could slowly be rolled out over the course of several updates.

**Comment by Peterinox** [comment]
Haha I found a way better solution:

var lust:int = player.lust;
      ... game.dynStats("lus", ... 
lust = player.lust - lust;
outputText(" <b>(<font color=\"#ff00ff\">" + lust + " </font>)</b>\n\n");

It actually works to just substract the stat value before and after the damage XD
Still complicated in comparison to normal damage but any factoring is included.

**Comment by Peterinox** [comment]
Oh boy, thanks to a push from kitteh in the right direction and additional thinking time I come up with another solution. Literally the same principle as damage:
_var lustDmg:int = ...
player.takelustDamage(lustDmg, true);_
instead of:
_game.dynStats("lus", ... );_
So still every source has to be changed but like this it is way more fancy 👍
