### ISSUE TITLE
Kanga fruit and Mighty veggie don't work

### ISSUE THREAD

**Issue by EGKangaroo** [Kitteh6660/Corruption-of-Champions-Mod#700]
### Overview
	Game gives no text for kanga fruit and mighty veggie consumption, no transformation happens, number in inventory don't update when consuming multiple in a row
	
### Game version
	1.0.2_mod_1.4.6b (The Chill Smith))
	
### Expected behaviour
	Kanga fruit and mighty veggie consumption should trigger some descriptive text about consumption as well as any transformative effects.
	
### Actual behaviour
	I get a blank text, no transformation happens. Intelligence decreases occasionally. Number of fruits shown in inventory does not update until I've consumed more than what I have in my inventory. Consuming one more than in my inventory causes an error message to say "You cannot use NOTHING!!" and then the mighty veggies all disappear from my inventory.

Note: entering debug mode causes descriptive text to appear! It includes texts about lowering intelligence as well as texts describing hips widening. However, no body parts ever turn into those of a kangaroo!

### Steps to reproduce the issue

1. Use the CoC editor to add any number of kanga fruits or mighty veggies into your inventory
2. Consume them, note that there is no text description.
3. Upon consuming ONE more kanga fruit or mighty veggie than you added into your inventory, you receive the text: "You cannot use NOTHING!!" and the inventory updates, causing all the mighty veggies/kanga fruits to disappear out of your inventory at once.

(when in debug mode)
1. Enter debug mode
2. Continuously consume mighty veggies or kanga fruit
3. Text does appear here
4. Note how no body part transformations occur, only intelligence drops and hips widening.

**Comment by brrritssocold** [comment]
With 'CoC editor' do you mean [CoCEd](https://github.com/tmedwards/CoCEd)?

Cannot reproduce this in 1.4.7, seems more likely an issue with the editor used to add the items.

1. Create new character
2. Spawn Kanga Fruit and Mighty veggie via cheat menu
3. Consume Items
4. As expected, text appears, transformations happen and items get consumed

**Comment by Kitteh6660** [comment]
Does this still persist in 1.4.8?

If not, this issue may be closed.

**Comment by Khyno** [comment]
This should not be closed, it still persist even in 1.4.9! I tested it with a new character as you suggested but not spawning the items (in-game found/enhanced).

**Comment by EGKangaroo** [comment]
My apologies. I'll reopen the issue, but I haven't been able to do any testing recently so I can't provide feedback on the issue myself. Wasn't entirely sure what the normal protocol in that situation would be.

**Comment by Stadler76** [comment]
An exception causes that.
Heres the diff, that should fix that:
```diff
diff --git a/classes/classes/Items/Mutations.as b/classes/classes/Items/Mutations.as
index 8b517a70..0360cd65 100644
--- a/classes/classes/Items/Mutations.as
+++ b/classes/classes/Items/Mutations.as
@@ -3128,7 +3128,7 @@ package classes.Items
 				changes++;
 			}
 			//-Shorten clits to reasonable size
-			if (player.getClitLength() >= 4 && changes < changeLimit && rand(5) == 0) {
+			if (player.hasVagina() && player.getClitLength() >= 4 && changes < changeLimit && rand(5) == 0) {
 				outputText("\n\nPainful pricks work through your " + player.clitDescript() + ", all the way into its swollen clitoral sheath.  Gods, it feels afire with pain!  Agony runs up and down its length, and by the time the pain finally fades, the feminine organ has lost half its size.");
 				player.setClitLength(player.getClitLength() / 2);
 				changes++;
```

**Comment by Stadler76** [comment]
Btw: There's an unclosed `<b>`-Tag in that TF. Fix would be:
```diff
diff --git a/classes/classes/Items/Mutations.as b/classes/classes/Items/Mutations.as
index 8b517a70..f3590657 100644
--- a/classes/classes/Items/Mutations.as
+++ b/classes/classes/Items/Mutations.as
@@ -3240,7 +3240,7 @@ package classes.Items
 			if (player.findPerk(PerkLib.Diapause) < 0 && player.kangaScore() > 4 && rand(4) == 0 && changes < changeLimit && player.hasVagina()) {
 				//Perk name and description:
 				player.createPerk(PerkLib.Diapause, 0, 0, 0, 0);
-				outputText("\n\nYour womb rumbles as something inside it changes.\n<b>(You have gained the Diapause perk.  Pregnancies will not progress when fluid intake is scarce, and will progress much faster when it isn't.)");
+				outputText("\n\nYour womb rumbles as something inside it changes.\n<b>(You have gained the Diapause perk.  Pregnancies will not progress when fluid intake is scarce, and will progress much faster when it isn't.)</b>");
 				changes++;
 				//trigger effect: Your body reacts to the influx of nutrition, accelerating your pregnancy. Your belly bulges outward slightly.
 			}
```
