### ISSUE TITLE
Scales n stuff

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#725]
Recently tf'd a pc into a dragonmorph, dragon scales and all, but on trying to use one of rathazul's lotions to make scales "smooth" scales continued to be referred to as "tough". In the .sol, the adjective for skin descrip which is usually changed by Rath's items remained the same as well, as though permanently stuck on "tough". Lotions do work on dragon underbelly scales though. Is this intentional?

**Comment by Stadler76** [comment]
Body Lotions can't be applied to the main dragon scales, but to the underbody (belly, lower jaw, ...) scales.

Well, that button could have been disabled, if your skin it goo or dragon scales.
