### ISSUE TITLE
Dungeon maps are not working

### ISSUE THREAD

**Issue by BlazinHothead** [Kitteh6660/Corruption-of-Champions-Mod#728]
### Overview
	The map screen in dungeons doesn't give the map. Only errors.
	
### Game version
	1.0.2_mod_1.4.7
	
### Expected behaviour
	The map screen to show that dungeon map.
	
### Actual behaviour
	The part where the actual map should show instead contains various errors

### Steps to reproduce the issue

1. Go to any dungeon.
2. Click on the map button.

This issue only popped up in version 1.4.7. The map screen in the previous version, 1.4.6b, works fine.
 Here's a screenshot from the Factory dungeon:

![coc map error](https://user-images.githubusercontent.com/29499331/27251524-419cd918-5362-11e7-8822-d359e07ec8bf.PNG)

**Comment by Stadler76** [comment]
That has been fixed and will be in the next release.
