### ISSUE TITLE
Isabella Tentacle Sex Bugged? Or Not Implemented Yet?

### ISSUE THREAD

**Issue by TheScopedOne** [Kitteh6660/Corruption-of-Champions-Mod#732]
The button for "TentacleSex" is faded out, even though you have tentacles yourself.

So when I first saw this option, I immediately got some incubidraft's, purified them then got myself 8 more dicks since it didn't tell me how many you needed to have to do it. I actually wanted 7 dicks but when I got to 6 extra, the next duped one to three. And a pink egg would remove my balls which I couldn't do so I'm an abomination now (All are horsedicks).

Then I went to Mareth, got into a fight then lost (Nightmare instead of game over) and got tentacle dicks as planned. (If this is a Bug, please don't remove this feature)

But even though I got this many, the option is still faded out. Is it not implemented yet? Because I can't seem to get it to trigger. Does it require you to have a smaller dick than 20 length, 1.8 Width?
  
My character is a Herm (started as it) with all stats full except Libido and sensitivity.

I'm running CoC 1.0.2 Mod 1.4.7 Windows 7 Internet Explorer

Reproducing is just trying to get tons of tentacle dicks and see its not working.

Bug or not implemented, that is the question.

**Comment by brrritssocold** [comment]
Checked the code, requirements are: min. 3 tentacle cocks with a length of 24 inches or more .
