### ISSUE TITLE
Kitsune Tails Won't Change Color

### ISSUE THREAD

**Issue by ClassicalPsycho** [Kitteh6660/Corruption-of-Champions-Mod#734]
While trying to get "metallic golden" hair on my kitsune character, I noticed that going into the appearance tab and scrolling to the text that describes your tails after your hair changes color, still says that they are white.

Running: CoC_1.0.2_mod_1.4.7

The items I've tested to dye my hair include: fox jewels, fox berries, and pink, green, blue, rainbow, gray, and black dyes.

Unless I'm missing some specific way to dye my tail hair, I'd guess that the new individual dye usage for hair, fur, and under fur is interfering with the original dyeing process, which dyed

**Comment by ClassicalPsycho** [comment]
Accidentally clicked submit, meant to end with: "which dyed both hair and tails"

**Comment by Stadler76** [comment]
I'll look into this. I already have some idea how to solve this.

**Comment by ClassicalPsycho** [comment]
Ok thanks, I think it's messing with the kitsune score too, it stays at 7 despite me changing hair color to a "non-kitsune" color, such as pink or green

**Comment by Stadler76** [comment]
Ok, I should have handled the latter, too. If you care to test it: You can download a test build here: https://drive.google.com/file/d/0B6ayFYXDcvsASEtmUWNrajZPaHc/view?usp=sharing

Just make sure to backup your saves first. They shouldn't break, but better be safe, than sorry.

**Comment by ClassicalPsycho** [comment]
Thanks for the fix, the tails description changed when I loaded the saves. Maybe next update there can be a dye tails option, I kind of liked the idea of having two separate colors.

BTW: I noticed that when I go to the dye options, there is an option to dye your characters wings, did you add that, or was my game bugged?

**Comment by Stadler76** [comment]
Nope, thats from cockatrices implementation. Written by MissBlackthorne and implemented by me. In the next version you can dye feathered wings.
