### ISSUE TITLE
mistress elly quest teleportation

### ISSUE THREAD

**Issue by archmancer8** [Kitteh6660/Corruption-of-Champions-Mod#75]
PC keeps getting teleported back into the prison while out on the quest (5 monsters in 4 days). Also, Elly gives the quest but doesn't bother to remove any restraints. Do you think this was intended by the original programmer/writer?

**Comment by openaz** [comment]
I thought about this few weeks ago too. When I'm on quest to be fucked, I have to win against male or loose against females. And if I loose, I can be taken back to prison. Which doesn't make sense. On the other side, there's only one quest and it's almost impossible to fail it. In future, this should lead to discussion, as distinction between lust defeat and hp defeat might be important.

**Comment by Kitteh6660** [comment]
I've made some alterations to the code so you won't get hauled back to prison when the quest is running.

Hopefully it should be addressed in 1.2.12. If it's fixed, go ahead and close.

**Comment by sinfulteddy** [comment]
I'm also having problems with this quest. I don't beat up any opponent. I used tease. Also I've tried submitting to opponents known for the option to submit. I used lovers or slaves to get sex. All different. Over 5 creatures and still no progress. i tried to lose by lust and still nothing. Hp will be hard over 900 hp
