### ISSUE TITLE
Priscilla content rewrite

### ISSUE THREAD

**Issue by TheWrongOtaku** [Kitteh6660/Corruption-of-Champions-Mod#757]
This isn't a bug, but more of an issue with the writing for the Priscilla overhaul. If you read the entire page after asking her for sex then you will notice that after a certain point it skips back to the beginning as if someone wrote a paragraph and then accidentally rewrote it again right under. If you could proofread and edit her content in any spare time then I think it might make it easier to read and understand.

**Comment by Peterinox** [comment]
Not 100 % sure if thats what you meant but I fixed the kissing for herm (Repetition) and found out that text in the foreplay didn´t changed after the first encounter.
Should be better in the next update.
