### ISSUE TITLE
[Question] Mountain exploration and worms encounter

### ISSUE THREAD

**Issue by openaz** [Kitteh6660/Corruption-of-Champions-Mod#76]
When character explores mountain, he can run into sign and choose whether he wants to encounter worms, he doesn't care or he's grossed out. In original CoC, chances are 100% (likes), 50%(who cares) and 0% (grossed). In this mod, encounter rates are 100%, 50% and 10%. Is this intended? This way, there's no possibility to turn worms off.

**Comment by Kitteh6660** [comment]
It's intended. Worms are rare when you choose grossed out. It doesn't make sense for worms to completely vanish from the game. It's like as if they went suddenly extinct.

**Comment by openaz** [comment]
Yes, this makes sense. Thank you for clarifying.
