### ISSUE TITLE
Runed Thong and Rune Loincloth are mixed up

### ISSUE THREAD

**Issue by Cirian** [Kitteh6660/Corruption-of-Champions-Mod#763]
### Overview
	The Runed Thong and Runed Loincloth have swapped names
	
### Game version
	1.0.2_mod_1.4
	
### Expected behaviour
	Crafting a Runed Thong should result in being given an item called 'Runed Thong'
	
### Actual behaviour
	When Crafting a Runed Thong, the item received is called 'Runed Loincloth'
	When Crafting a Runed Loincloth, the item received is called 'Runed Thong'

testing with the save editor shows that the game is identifying and distributing the correct item, but the items themselves have incorrect display names.

### Steps to reproduce the issue

attempt to craft a Runed Thong or Runed Loincloth

savefile with enough blooms included

[daedelus.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1147477/daedelus.zip)

**Comment by brrritssocold** [comment]
Can you test this with the current release (1.4.8)?
Could not reproduce.

**Comment by Kitteh6660** [comment]
Another bug I found is mixed up tooltip for thong and jockstrap, that will be corrected in 1.4.9.
