### ISSUE TITLE
Text Missing in Mountain

### ISSUE THREAD

**Issue by botukon** [Kitteh6660/Corruption-of-Champions-Mod#773]
### Overview
	Sometimes I get a screen with no text when visiting the mountains. I was recently attacked by Ceraph and she put a ring on my character. I am trying to get her to show up again.

	
### Game version
	1.0.2_mod_1.4.8
	
### Expected behaviour
	There should be text when visiting the mountains.
	
### Actual behaviour
	I am met with a window lacking text. The 'next' is still functional

### Steps to reproduce the issue

Simply revisiting the mountains several times and it will eventually happen.

I don't know how to attach the save file. I keep getting a message indicating that the file is not supported.

**Comment by Kitteh6660** [comment]
Does this issue still persist in the latest version?

It might have been fixed, I don't know.
