### ISSUE TITLE
Start Up Problem?

### ISSUE THREAD

**Issue by ForgottenFate** [Kitteh6660/Corruption-of-Champions-Mod#778]
### Overview
	e.g.: When opening the game on Google Chrome with the .swf there seems to be a 60% for my game to gain a glitching back screen and be unable to do anything other than reload
	
### Game version
	e.g.: 1.0.2_mod_1.4.8
	
### Expected behaviour
	e.g.: To be able to play the game
	
### Actual behaviour
	e.g.: Unable to do anything and must reload or close the tab

### Steps to reproduce the issue

1. e.g.: Open the game using the .sfw download

**Comment by BelshazzarII** [comment]
Most browsers have dropped support for Flash. For a non buggy experience I recommend you grab a standalone flash player from the Adobe website.
