### ISSUE TITLE
Kath: stuck after being unable to sex her

### ISSUE THREAD

**Issue by Enzoyyy** [Kitteh6660/Corruption-of-Champions-Mod#801]
I didn't notice that you could report issues here till like a month later so I dont remember exact details.

Basically, I took her to i think either the desert or lake and had the option to have sex with her. But due to i think my cock being to big (or something) and me not using reducto on her knot, none of the sex options were available. Couldn't progress or backtrack and had to reload the save.

**Comment by Netys** [comment]
It's probably #642

**Comment by Stadler76** [comment]
Can you still repeat this bug in a recent version of CoC Revamp (Currently 1.4.9)?
