### ISSUE TITLE
Had trouble gaining Slime Core perk

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#829]
### Overview
	I was fully an Ooze; eg had slime cravings and everything, but I could not for the life of me get a Slime Core from defeating a Goo-Girl
	
### Game version
	1.0.2_mod_1.4.6b
	
### Steps to reproduce the issue

1. Switch to debug mode
2. Spam a Wet Cloth
3. Defeat a hundred Goo-Girls

I tried to figure out WHY and couldn't see anything wrong in the coreDropChance() function but I did see that the function is only called at the end of the sex scenes, I tried again for another 20+ goo-girls and it still never proc'd so I just gave it to myself through the editor.

Not sure if I was just unlucky, but imo the function ought to be called regardless of sex or not eg on combat cleanup and the spyOnGooAndOozeSex() ought to give you one automatically since you see that goo's core go flying out of her body.

**Comment by Kitteh6660** [comment]
So far, I see this excerpt, there's 25% chance with the right condition. You'll need slime craving.

`rand(4) == 0 && player.hasStatusEffect(StatusEffects.SlimeCraving) && player.findPerk(PerkLib.SlimeCore) < 0 && player.isGoo() && player.gooScore() >= 4`
