### ISSUE TITLE
Full Bunny Morph gives a Naga Score of 7 with no sign of a Bunny Score

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#830]
### Overview
	Title
	
### Game version
	1.0.2_mod_1.4.6b

**Comment by TheWrongOtaku** [comment]
Have you tried using the newest version to see if it's fixed on there, the newest one is v1.4.8

**Comment by Drake713** [comment]
Just tested in 1.4.8 with a fresh character and it is the same; use editor to put a Neon Pink Egg in your inventory, turn on debug mode, spam the egg and the result is:
Human Score: 4
Mutant Score: 3
Naga Score: 7

**Comment by Stadler76** [comment]
Thats an error in the text, it should actually read Bunny Score:
```as3
if (player.bunnyScore() > 0) {
	raceScores += "<b>Naga Score:</b> " + player.bunnyScore() + "\n";
}
```
