### ISSUE TITLE
Harpy Womb stays after loosing all Harpy score

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#851]
### Overview
	Found while testing to see which racial perks, if any, I could keep without being that race
	
### Game version
	1.4.8
	
### Expected behaviour
	Increases all laid eggs to large size so long **as you have harpy legs and a harpy tail.**
	
Other Racial Perks you can keep without being that race:
Diapause - intended behavior?
Dragonfire - intended behavior?
Harpy Womb - unintended behavior or else the description should be changed
Hellfire - intended behavior?
Incorporeality
Oviposition - due to interaction with Basilisk Womb

PS. Testing included resting for several days after loosing the racial score

**Comment by Stadler76** [comment]
Thats intended. Once you get it, you'll keep it till next ascension. It'll just be inactive if you don't meet the requirements to be active.

**Comment by Drake713** [comment]
Maybe add a "disabled" tag to it like the JoJo perks then?

**Comment by Stadler76** [comment]
Bout the other perks:
- Diapause ... uuh, dunno. How can you obtain it and can you get it again?
- Dragonfire was intended, although IMHO it should be removable at least with Hummanus (It does in my Dragon Mod)
- Hellfire can only be obtained once till you ascend again. Hance why this is intended
- Incorporeality can be removed by consuming Hummanus at a 1/10 chance
- The Bassy Womb perk grants you the Oviposition Perk if you have none and protects the Oviposition Perk from being lost

**Comment by Drake713** [comment]
Diapause is the kangaroo womb perk, so you can def get it again by eating more fruit, don't think it can be removed other than by entirely losing the vag/womb

**Comment by Stadler76** [comment]
Diapause gets removed in a player event (triggered when an hour or more passes ingame):
```ts
if (!player.hasVagina() && player.findPerk(PerkLib.Diapause) >= 0) { //Lose diapause
	outputText("\n<b>With the loss of your womb, you lose your kangaroo-like diapause ability.</b>\n");
	player.removePerk(PerkLib.Diapause);
	needNext = true;
}
```
Since its not on the list of permeable perks I could add some code to hummanus, so this has a chance to remove it too and to superhummus, that always removes it.

Just need some loss text for hummus, thats less dull than the text above.
