### ISSUE TITLE
Blank Screen when fighting Basilisks and suffering a Speed loss

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#854]
### Overview
	When I fight basilisks the screen blanks out when it does w/e attack causes a speed loss
	
### Game version
	1.0.2_mod_1.4.8

This bug has persisted through closing and reloading the browser, and I also remember getting it a few times when I was using a transformative that would have given me fur, several transformatives had this bug, but only when it would give me fur, not any other change.

Also to be clear, this is not the whole browser. just the text output portion of the screen; aka you can see your speed took a hit, but there is no text to describe what happened.  And when you take another action the new text is displayed assuming it is not another gaze attack.

**Comment by Stadler76** [comment]
Can't repeat so far. Could you provide a savegame, where that happens?

**Comment by Drake713** [comment]
Created a new character and ran it until the high mountain opened up then edited stats to 100 so could survive long enough to be hit by it:
https://www.dropbox.com/s/vsj3f2te3iwup5k/CoC_2.sol?dl=0
![example](https://user-images.githubusercontent.com/30520080/29480676-5d0c908e-8437-11e7-8d02-91b6fb4004ee.png)

**Comment by Stadler76** [comment]
Ok, found it. The Scene text is missing in Combat.as: https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/Combat/Combat.as#L758-L773

If anyone figures out a scene text for this (It would be a stare counter attack from the bassy), I'll fix this bug then.

**Comment by Kitteh6660** [comment]
Turns out that the line was accidentally removed.

This will be re-added from vanilla.
