### ISSUE TITLE
Transformative Items missing a flags[kFLAGS.TIMES_TRANSFORMED] update

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#858]
### Overview
	Looking through the files some transformational items are missing a line that updates the global counter
	
### Game version
	1.0.2_mod_1.4.8

Items lacking the line:
game.flags[kFLAGS.TIMES_TRANSFORMED] += changes;

Canine Peppers
Clovis
Equinum
Goblin Ale
Imp Food
LaBova
Minotaur Blood
Phouka Whiskey - perhaps intended for this one
Rizza Root
Snake Oil
Taurium
Wet Cloth
Wolf Pepper

**Comment by Drake713** [comment]
Updated to include all the transformative items, but I did not go through common consumables code if you want to check/include those as well eg Gro+ and the like

**Comment by Stadler76** [comment]
@Drake713: All the transformatives you've mentions should update TIMES_TRANSFORMED properly now. Phouka Whiskey had no changes++ at all, so updating TIMES_TRANSFORMED there wouldn't do anything.

If you find more TFs, just tell.
