### ISSUE TITLE
[Wellspring of Lust] is not triggering [Battlemage]

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#860]
### Overview
	title
	
### Game version
	1.0.2_mod_1.4.8
	
### Expected behaviour
	One would expect to always benefit from Battlemage's Might spell with the Wellspring of Lust perk
	
### Actual behaviour
	The player's current lust level appears to be checked FIRST to see if Battlemage should activate or not, and THEN your lust is raised by Wellspring of Lust

### Steps to reproduce the issue

1. Have both perks
2. Have less than 50 current lust
3. Enter into battle, and check to see if you are under the effects of Might or not (you won't be)

**Comment by Kitteh6660** [comment]
This will be corrected in 1.4.9.

The perk will take priority over Battlemage in the patch.
