### ISSUE TITLE
Rhino Steak transformative error

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#861]
### Overview
	coding error: player.tailType = HORNS_RHINO;
	
### Game version
	1.0.2_mod_1.4.8

player.*tailType* = HORNS_RHINO;

Additionally, I'm not sure why Upheaval checks horn length since I can't see any Rhino horn increases beyond player.horns = 2;

**Comment by Stadler76** [comment]
It could have been `player.horns == 2` in that case. Using `>=` is merely a failsafe.

Anyways: Thanks for pointing that out. Should be fixed in the upcoming fixes batch

**Comment by Drake713** [comment]
This is from the Upheaval code:
```
if (player.horns >= 6 && player.horns < 12) {temp = 60;}
if (player.horns >= 12 && player.horns < 20) {temp = 75;}
if (player.horns >= 20) {temp = 80;}
```
But take a look at that Rhino Steak transformative again, I can't see how a Rhino horn would be greater than 2...

Additionally, (also from Upheaval)
```
var horns:Number = player.horns;
if (player.horns > 40) player.horns = 40;
```
This is done... and then never used in the damage calculation

**Comment by Stadler76** [comment]
Ok, I'll look into this later on
