### ISSUE TITLE
Successful Android APK

### ISSUE THREAD

**Issue by DragonessLover** [Kitteh6660/Corruption-of-Champions-Mod#865]
### Overview
	I have a working android apk of the CoC Mod, but do not know how I can get it to you.  I can also make an apk of any future releases for this mod.
	
### Game version
	coc_1.0.2_mod_1.4.8
	
### Actual behaviour
	Works just as well as the .swf does on a computer, though it does up to 30 seconds to load.

**Comment by Kitteh6660** [comment]
Here's the repository by Hexxah where Android builds of CoC mod are hosted.

https://github.com/Hexxah/CoC-MOD-Android-Build
