### ISSUE TITLE
Some lust attacks are ignoring resistance.

### ISSUE THREAD

**Issue by NineRed** [Kitteh6660/Corruption-of-Champions-Mod#866]
### Overview
Many lust attacks in the game are ignoring lust resistance, making fights extremely difficult. Especially noticeable in the Phoenix Tower.
	
### Game version
	1.0.2_mod_1.4.8
	
### Expected behaviour
Lust damage should be mitigated by lust resistance
	
### Actual behaviour
Some Lust attacks deal the full damage regardless of resistance.

### Steps to reproduce the issue
1. Fight any encounter in the Phoenix Tower with any amount of Lust resistance.
2. Brigid's lust move always hits for 30.  Phoenixes lust move always hits for 40. If you have a dick, Harpies' lust move always hits for 30.

**Comment by BelshazzarII** [comment]
Should be fixed now that takeLustDamage applies resistances by default.

**Comment by Kitteh6660** [comment]
Once I release version 1.4.9, if the issue still persists, let me know.
