### ISSUE TITLE
using fuctions to determine chance in encounter API seems to be broken

### ISSUE THREAD

**Issue by BelshazzarII** [Kitteh6660/Corruption-of-Champions-Mod#874]
I started thinking something was wrong when finding the harpy chick in the High Mountains became unbearably hard.

I decided to trace two things: the value of itemcount on ovi elixirs and the chance for the harpy chick encounter. They should be the same.

For some reason, even with 5 or more ovi elixirs, the chance was always 1 or 0, even though itemcount was tracing correctly.  Changing the value to be a hard number worked just fine, but using a function seems to be broken. I looked at the API but I have no idea what could be causing this. From what I can tell, the "when" conditions work just fine with functions, and itemcount returns the correct value when you do, say, itemcount() >= 2.

For now, it may actually be better to set the chance to encounter her to 2(a bit more likely since High Mountain is pretty crowded) only as long as you have at least two elixirs. Right now, finding her is pretty damn frustrating.

**Comment by aimozg** [comment]
My mistake.
```js
{ //...
chance: player.itemCount(consumables.OVIELIX),```
should be
```js
{ //...
chance: function():Number { return player.itemCount(consumables.OVIELIX); },```

**Comment by Stadler76** [comment]
Ok, added to the fixes batch. Thanks, @aimozg
