### ISSUE TITLE
Tail Slap can be spamed past fatigue cap

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#877]
### Game version
	1.0.2_mod_1.4.8
	
`player.changeFatigue(40,2);`
But there is never any check to see if you are too fatigued to use it.
Bug or intended?

**Comment by Stadler76** [comment]
mmh, Tail Whip doesn't cost any fatigue. And the intro text of tail swap says:
"With a simple thought you set your tail ablaze."
So I assume, that it shouldn't cost any fatigue to begin with.

**Comment by Drake713** [comment]
Well current implementation will increase fatigue by 40 with each use and then still allow use past 100 fatigue.  Seems like either that line updating fatigue should be removed or the standard fatigue checks should be added, unless this current behavior is intended

**Comment by Ormael7** [comment]
It's situation when I forgot to put check if PC got enough fatigue to use it. So it should have added this part to fix issue as it does cost fatigue to use.

**Comment by Drake713** [comment]
I was working up a spreadsheet comparing some abilities to each other and Tail Slap was coming in vastly under-powered and over priced under current implementation.  The only benefit it seems to have is that it keep raging inferno going.  I'd probably only use it if its cost was 5 fatigue or the damage was buffed.  Page two here shows my preliminary analysis:
https://www.dropbox.com/s/qgv72zt41eeq5fm/Attacks.ods?dl=0

**Comment by Stadler76** [comment]
I have to figure out an updated formula to make it more powerful, then I'll fix the fatigue mechanic (plan is to change the cost to 25 base cost modified by spellcost reduction for setting the tail ablaze)
