### ISSUE TITLE
Most Physical Specials do not display their fatigue cost

### ISSUE THREAD

**Issue by Drake713** [Kitteh6660/Corruption-of-Champions-Mod#894]
### Game version
	e.g.: 1.0.2_mod_1.4.9
	
Out of 7 buttons under that menu (that I have unlocked) only Horn Stun shows its fatigue cost; AnemoneSting, Bite, Bow, Tail Slap, Tail Whip, and Shield Bash do not.

**Comment by Kitteh6660** [comment]
This will be rectified in 1.4.10.
