### ISSUE TITLE
Code Commenting and Cleanup

### ISSUE THREAD

**Issue by Mattibun** [Kitteh6660/Corruption-of-Champions-Mod#9]
Since this seems to be the main fork now, would you like assistance in commenting the code so others can understand what is happening?

**Comment by Kitteh6660** [comment]
Go ahead.

I have commented several commonly used functions such as outputText to explain.

**Comment by Mattibun** [comment]
Thanks! I'll see what I can find.

**Comment by Kitteh6660** [comment]
So far, I've cleaned several codes, including combat. I've also documented some of the functions. More may eventually be added, such as code commonly called.
