### ISSUE TITLE
[Typo] Boobgartuan + Shouldra scene incomplete

### ISSUE THREAD

**Issue by kiop9099** [Kitteh6660/Corruption-of-Champions-Mod#901]
### Overview
	Shouldra + female player w/Boobgartuan spirit sex scene cuts out.
	
### Game version
	mod_1.4.9 (persisted in previous versions, probably just unnoticed)
	
### Expected behaviour
	//Vagina with Boobgartuan Scene
	
### Actual behaviour
	Boobgartuan scene cuts out after:
                "Who the fuck is THIS?

### Steps to reproduce the issue
       Player Gender: Female (At least one vagina)
       Breast Size: 16+, or Big F-Cup+
       Exgartuan Status: Possessed breasts and "sleeping" from boobgasm
       Battle Conditions: Defeat Shouldra with lust, or ghostbust her incorporeal tush up until she offers sex instead, knowing the outcome.
       Shouldra Sex: At least once prior to trigger the scene?
       Time: 0600 ~ 2000
       Location: Town Ruins (random encounter)
       
### Screenshot of game
![screenshot 34](https://user-images.githubusercontent.com/31273251/29607287-c3053df2-87be-11e7-84a8-95dbc1f0bbba.jpg)

### Probable issue
       Line 1228 of ShouldraScene.as
![screenshot 35](https://user-images.githubusercontent.com/31273251/29608225-942eff88-87c1-11e7-9bcc-d0b55a051e76.png)

       </i?\ should be </i>\

### Additional Coments
       Sorry, don't know how to program, let alone contribute to the code.

**Comment by BelshazzarII** [comment]
it's fixed
