### ISSUE TITLE
Corrupt Jojo in camp before ever meeting him

### ISSUE THREAD

**Issue by TiffSmith** [Kitteh6660/Corruption-of-Champions-Mod#931]
### Overview
         Sometimes when loading a save game, corrupted Jojo is in the camp, even if he's not yet been encountered. 
	
### Game version
	1.0.2_mod_1.4.9

I'm not sure what triggers it, but it seems to happen randomly when loading a save. The attached file is a character I created, skipped the prologue, immediately quicksaved having done nothing else, then loaded, and Jojo was in camp. I created another character to test it, and it did not happen. I'm unsure if you can still encounter Jojo in the Forest when this happens. Possibly something local to me? I have no idea what's causing.

[CoC_1.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1268876/CoC_1.zip)

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [ ] Reproduce issue
- [ ] Working on patch for issue
- [ ] Submit pull request

**Comment by brrritssocold** [comment]
Could not reproduce this.

Can you confirm this happens with `1.0.2_mod_1.4.9`, the save is created with this version?
The reason i'm asking is because the provided save has the `monk` property, which is a old save format.

**Comment by Stadler76** [comment]
Probably caused by the following section in `Saves.as`:
```as3
		// Fix possible old save for Plot & Exploration
		flags[kFLAGS.TIMES_EXPLORED_LAKE]     = (flags[kFLAGS.TIMES_EXPLORED_LAKE] || saveFile.data.exploredLake || 0);
		flags[kFLAGS.TIMES_EXPLORED_MOUNTAIN] = (flags[kFLAGS.TIMES_EXPLORED_MOUNTAIN] || saveFile.data.exploredMountain || 0);
		flags[kFLAGS.TIMES_EXPLORED_FOREST]   = (flags[kFLAGS.TIMES_EXPLORED_FOREST] || saveFile.data.exploredForest || 0);
		flags[kFLAGS.TIMES_EXPLORED_DESERT]   = (flags[kFLAGS.TIMES_EXPLORED_DESERT] || saveFile.data.exploredDesert || 0);
		flags[kFLAGS.TIMES_EXPLORED]          = (flags[kFLAGS.TIMES_EXPLORED] || saveFile.data.explored || 0);
 
		flags[kFLAGS.JOJO_STATUS]        = (flags[kFLAGS.JOJO_STATUS] || saveFile.data.monk || 0);
		flags[kFLAGS.SANDWITCH_SERVICED] = (flags[kFLAGS.SANDWITCH_SERVICED] || saveFile.data.sand || 0);
		flags[kFLAGS.GIACOMO_MET]        = (flags[kFLAGS.GIACOMO_MET] || saveFile.data.giacomo || 0);
```
A fix could be to `delete` all those outdated props before saving the `saveFile` again, so they'll be gone for good?

**Comment by shakey2** [comment]
I am having this issue as well, I overwrote a savefile and now not only is jojo suddenly a slave in camp, my character went from being male to herm on the save even though it was a Male character when I saved.
