### ISSUE TITLE
[bug] Cause of disappearing double penetration option for Katherine.

### ISSUE THREAD

**Issue by metalax** [Kitteh6660/Corruption-of-Champions-Mod#938]
v1.4.9
Tracked down a bug in Katherine's sex menu, where the option to double penetrate her disappears.

In katPenetrate() in scenes/places/teladre/Katherine.as, if Katherines knot size is at least 6", the SucknFuck button appears in it's disabled state. If her knot size is 4" or less, the SucknFuck button appears in it's active state but due to a typo is replacing the location that the double penetration button occupies.

the line 
	addButton(2, "SucknFuck", suckNFuck);
should be
	addButton(3, "SucknFuck", suckNFuck);

**Comment by Stadler76** [comment]
Thanks for pointing that out. Should be fixed, when the PR is merged.
