### ISSUE TITLE
Rathazul items disappearing 

### ISSUE THREAD

**Issue by Turkroach** [Kitteh6660/Corruption-of-Champions-Mod#949]
If you purchase an item from Rathazul while your inventory is full and select the "Nevermind" option, your gems are still used and the item is lost permanently.

**Comment by brrritssocold** [comment]
**Please use the issue template when submitting bugs, it's there for a reason. Thank you.**

- What version of the game are you using?
- Could not reproduce this on the latest release 1.0.2 - Mod v1.4.9 (a7b19c2)
- 'Nevermind' returns the money, abandon does not - working as expected

**Comment by brrritssocold** [comment]
What is the status of this issue? If it is resolved, please close it.
The issue can be re-opened at a later date if the issue re-occurs.

If there is no response I will request the issue be closed.

**Comment by Stadler76** [comment]
> If there is no response I will request the issue be closed.

Same here: I'll wait till the 22. Sep for feedback and then I'll close it.

Side note: Just added 'Need feedback' to the labels.

**Comment by Stadler76** [comment]
Ok, closing it due to the lack of feedback.
If you can provide us some feedback feel free to reopen it.
