### ISSUE TITLE
New Content Ideas

### ISSUE THREAD

**Issue by ClassicalPsycho** [Kitteh6660/Corruption-of-Champions-Mod#960]
I'm not sure if there is a proper place to post this, but after seeing the post made by Abi696 "Few Suggestions," I was wondering if anybody might have some interesting ideas they would like to see in the game. Here are a few brainstormed ideas I've had whilst playing the game:

**A beach/ocean/river area-** it came to my attention that aquatic monsters are very scarce in this game, and the same goes for the areas where they would be found in. Adding a few new areas with watery themes could introduce monsters such as, crocodiles/alligators, a whole ecosystem of oceanic monsters, mermaids, fish-men/girls, a ghost ship dungeon, palm tree dryads, pirates, another storage chest, etc.

**A jungle area-** monkey-morphs, tiger-morphs, ape-morphs, big lamias, frog-morphs, etc., could be added. This would also allow for a new dungeon (probably in the form of a temple).

**Dryads and plants need some love-** I'm not too familiar with the different types of monsters that could be related to the forest, but there is a noticeable lack of dryads. So far, there are only 3 different people with plant physiology (and one newbie-shredding tentacle beast), so adding some variety to the forest enemies would make it more worthwhile to go into the forest, and I believe it would make the early game either more difficult or easier depending on the levels of the new enemies.

**The bee hive should be featured as a dungeon-** the bee hive would make a great early-game dungeon to explore, and would give players an easier way of obtaining the different types of honey.

**Kiha needs her interactions fixed-** I can understand taking a stroll through her previous territory in the swamp, but a lot of her "hang out" scenarios still take place in the swamp and her old home, which is strange to read when she lives in your camp. Also, I feel like she should not fly off every time the player hugs her, seeing as she will happily have sex whenever you want.

**Is the Kitsune Village going to be a thing?-** this is really just me asking (begging) because I had heard rumors about it.

**As of right now I'm out of ideas, so here are some new enemies that could be added-** scorpion-morph (desert), golems (mountain/high mountain), fox-morph thieves/highwaymen (plains/deep forest), dog-morph bandits (pretty much anywhere), forest lamias (forest/deep forest), bear-morphs (mountains/deep forest), dragon-morphs (fake like Kiha) (volcanic crag), jackalope-morph (mountains/high mountains), snow owl harpies (glacial rift), Cherufe (mythical creatures you may want to look up on Wikipedia) (volcanic crag), renegade phoenix harpies (volcanic crag)

If this post does not belong here please notify me, and I will copy+paste what was written here to an appropriate place, but if it's okay to leave it, please comment what ideas you have to further expand this ambitious list of suggestions. Thank you all in advance for contributing, and be sure to thank the generous people who continue to work on this game for all of their effort.

**Comment by tistdaniel** [comment]
Personally, I think these are some good ideas.

But I think the chances they'll be included go way up if you write the scenes.

**Comment by ClassicalPsycho** [comment]
@tistdaniel 
I would totally help write the scenes, but I have no experience in doing so. That is why I thought it would be a good idea to maybe have a small thread to help create content. Throwing ideas around, (no matter how silly or stupid you think they may be), is much better than letting them float around in your head. Anyhow, maybe I will try writing a few drafts and see how well they turn out, because I would love to see 
at least some of this stuff added to the game at some point.

**Comment by ClassicalPsycho** [comment]
@tistdaniel 
I wrote a bit for the ocean biome's discovery encounter, but I'm not sure it is up to par with the actual writers' work. Feel free to criticize, or add to what I have written though.
**As you trek your way through the blisteringly hot desert, you come across what may be the biggest dunes you've seen so far. Seeing how you will be forced to traverse the dunes to continue any further, you decide to head back to camp. Turning to head back though, you notice something peculiar about the dunes, they seem to stretch on for miles on both sides without showing any sign of stopping. Now interested by the odd wall of sand, you begin climbing to the top in hopes of seeing something on the other side. After much stumbling on the loose terrain you finally manage to reach the summit, only to sigh in disappointment. On the other side there only appears to be a shimmering mirage of what looks like a vast ocean. Sighing once more, you decide to continue forwards seeing as you've already climbed the dunes, but notice something out of place. The mirage has not changed at all despite your change in elevation, and when concentrating you could almost swear that the air smelled somewhat... salty? You begin racing toward what you once believed was a mirage, now certain that salty smell is for real, as it only becomes stronger the closer you get. Soon, you reach the edge of what you can now confirm is a large body of water, in fact, now that the sun isn't shining directly down on the shimmering water, you notice waves in the distance, which can only mean that this is the ocean! You memorize the location and head back to camp, everyone will want to know what you've found. 
Beach Discovered**

**Comment by melch-i** [comment]
There should be a dryad in the next release

**Comment by Stadler76** [comment]
Bout the Beach/Ocean area:
This is currently in CoC Xianxia only. GDoc: [CoC: New Locations - Beach and Ocean](https://docs.google.com/document/d/1Fq9zjXPIBbMA1a_1Le4OCRWF2kLiQ4JTxV3mQpV6kGo/edit#heading=h.yxv77smu7c30). Maybe you want to direct your suggestion the CoC Xianxia and/or the GDoc?

**Comment by Kitteh6660** [comment]
Unfortunately, I want to start cutting down on accepting new content, with focus on finishing up the mod.
