### ISSUE TITLE
accidentally posted these on the original game rather than the mod: 6 small bugs

### ISSUE THREAD

**Issue by tistdaniel** [Kitteh6660/Corruption-of-Champions-Mod#968]
I believe these should all be easy to fix. In every instance, the code is correct elsewhere in the game, so it should just be a copy-and-paste fix, aside from #6, which might require some writing.

1. When playing using only the keyboard, it's very easy to accidentally name the Gargoyle "1". This doesn't seem to happen with other nameable characters. Something's wrong with the code here.
2. When the Fetish Cultists first arrive at the lake, the description includes a line about exploring that should have been cleared from the screen.
3. When encountering a goblin in SFW mode, the rape screen still comes up, but the only options on it are Next and Leave. Next increases lust, but returns you to the same screen. You can keep doing this to max out lust on the same screen.
4. Sometimes when viewing the Appearance screen, the "virgin" tag on the anus gets dropped. Refreshing the screen fixes that, but it makes it seem like a rape scene was missed--I've restarted a few games because of this. (I often play as a virgin for the challenge.)
5. When fighting the mimics, an hour passes before battle, and an hour passes after battle, meaning every mimic battle is two hours. I believe the hour before battle is a mistake.
6. When genderless, if you lose to an imp (might be only certain variants of imp) you get the error message: "Error: multiCockDescriptLight() called with no penises present."

**Comment by tistdaniel** [comment]
Another small bug: Joy seems to have a broken italics tag (talk:yourself) that turns all text italic for the rest of the game.

**Comment by Stadler76** [comment]
@tistdaniel wrote:
> Another small bug: Joy seems to have a broken italics tag (talk:yourself) that turns all text italic for the rest of the game.
That should be fixed in PR #971
