### ISSUE TITLE
Dragonscale Armorcraft scum makes gold worthless; should be nerfed.

### ISSUE THREAD

**Issue by TrickQuestion** [Kitteh6660/Corruption-of-Champions-Mod#975]
### Overview
The dragonscale armorcraft scum makes gold worthless.
	
### Game version
1.0.2_mod_1.4.9 (and many versions before it)
	
### Expected behaviour
One of the following four things: either dragon scales not sold in Tel'Adre, or dragon scales cost significantly more gold, or dragonscale items cost gems to craft, or dragonscale items take time to craft.
	
### Actual behaviour
See steps to reproduce issue, below.

### Steps to reproduce the issue
You can make in excess of 3,000 gold per hour by purchasing dragon scales from Pawn, returning to camp, crafting limitless Dragonscale Thongs for 0 gold each and 0 hours time, and resell to Pawn on the next trip. No supplies necessary except meeting Rat enough times and finding Tel'Adre.

Savefile not needed, the scum is trivial to reproduce.

**Comment by Stadler76** [comment]
Ok, I'll work on it.
Current plan:
- DragonScale base price raised to 45
- DragonScale Undergarments base prices lowered to 360
- DragonScale Armors base prices raised to 900

So, by buying Dragonscales from Femoit and then selling the crafted DragonScale gear you can still make little profit, but I doubt, that would be worth the effort.
Calcs for Femoit:
- DragonScale Armors:
  `(900 / 2) - (5 * round(45 * 1.66)) = 450 - (5 * 74) = 450 - 370 = 80` Profit per piece
- DragonScale Undergarments:
  `(360 / 2) - (5 * round(45 * 1.66)) = 180 - (2 * 74) = 180 - 148 = 32` Profit per piece
