### ISSUE TITLE
Marble's bad ending

### ISSUE THREAD

**Issue by mad0alyss** [Kitteh6660/Corruption-of-Champions-Mod#979]
### Overview
	e.g.: When using a large number of y item the game crashes.
	I'm trying to get the bad ending with Marble but despite keeping her affection below 48% it didn't trigger and I just got the one where you lose an hour to drink her milk. Another player tried to help and get the same issue. 
### Game version
	e.g.: 1.0.2_mod_1.4
	
### Expected behaviour
	e.g.: Can use as many y item as i want.
	
### Actual behaviour
	e.g.: The game crashes after using around z number of item y.

### Steps to reproduce the issue
try 

1. e.g.: Switch to debug mode
2. e.g.: Try to eat n number of item y
3.

If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

**Comment by Kitteh6660** [comment]
Please make sure you're using the latest version, see if this still happens.
