### ISSUE TITLE
Owcas tavern makes everything italic

### ISSUE THREAD

**Issue by Whimsalot** [Kitteh6660/Corruption-of-Champions-Mod#981]
Every time I visit the tavern in Owcas, everything goes italic. Couldnt find the problem in the source code, so maybe somebody more experienced can have a look.

**Comment by brrritssocold** [comment]
*This comment is to avoid duplicate effort.*

I'm working on this issue:

- [X] Reproduce issue
- [X] Working on patch for issue
- [ ] Submit pull request

**Comment by brrritssocold** [comment]
Seems the issue is how ActionScript handles tags.

**Comment by Stadler76** [comment]
@brrritssocold commented:
> Opening a tag in one outputText() and closing it in another does not seem to work.

Actually the issue is with the `menu();`-call in line 621, since `menu()` also flushed the output:
```as3
/**
 * Hides all bottom buttons.
 */
public function menu():void { //The newer, simpler menu - blanks all buttons so addButton can be used
	for (var i:int = 0; i <= MAX_BUTTON_INDEX; i++) {
		mainView.hideBottomButton(i);
	}
	output.flush();
}
```

**Comment by brrritssocold** [comment]
Thanks, you are right.
So why does flushing break formatting tags?

**Comment by Stadler76** [comment]
>  So why does flushing break formatting tags?

mmh, probably because of the usual AS3 HTML-Formatter borked-ness ...

You could probably fix/workaround this issue by resetting the formatting, when clearing the output. But on the other hand, that would make it harder to find and fix the causes.

**Comment by brrritssocold** [comment]
Will add notes to the appropriate functions, to let others know that calling the function can unintended side effects.

**Comment by Whimsalot** [comment]
Thats good to know because I found 2 other cases of broken formating that might be related to that. 

Sadly, they are a lot harder to reproduce:
1. Rathazuls text went italic while buing a lot of Reducto
2. Lethices turned everything bold during her first fight.

I will see if I can nail them down to a spefic scene/text and open a new Issue if I find anything usefull.

**Comment by brrritssocold** [comment]
Encountered another one with Katherine.
IIRC: `Sex -> Penetrate -> Vaginal`, will try to reproduce and fix.
