### ISSUE TITLE
times to reappear npc events are random

### ISSUE THREAD

**Issue by capitanjal** [Kitteh6660/Corruption-of-Champions-Mod#982]
Overview
	+The times to reappear npc events are random.
	++rare items aren't that rare
Game version
	1.0.2_mod_1.4.10
	
Expected behaviour
	 +there is events like Izma and phylla that should appear every 8th time and the like.
         ++bro brew and bimbo liquor are rare drop
	
Actual behaviour
	I go to the lake like 20th times and Izma still don't appear is the same with phylla; if you want these events be more random at least put a upper limit to the timing

**Comment by Kitteh6660** [comment]
Unfortunately, that's due to how RNG currently works.
