### ISSUE TITLE
load save from file ! Unhandled Exception

### ISSUE THREAD

**Issue by capitanjal** [Kitteh6660/Corruption-of-Champions-Mod#983]
### Overview
	When you try to load a file from a backup the game trows ! Unhandled Exception, if you pick the save and put it in the fl save folder you can bypass this error.
	
### Game version
	e.g.: 1.0.2_mod_1.4
	
### Expected behaviour
	you should load the save game in the location of the flv, the save is not corrupt but the button don't work

**Comment by brrritssocold** [comment]
Are you trying to load a file like `CoC_10_backup.sol` with `Data -> Load File`?
In that case it will not work, as save games created with `Save` and `Save to File` have different formats.
