### ISSUE TITLE
Metric measurements question

### ISSUE THREAD

**Issue by openaz** [Kitteh6660/Corruption-of-Champions-Mod#99]
It seems that even there's switch between imperial and metric system, most of the texts are in imperial only. My question is, if it's worth of time to fully implemented metric system. It would mean to update most of the texts and char creation as well.

Imperial system is hardcoded in probably all scenes, in char creation and maybe much more. I have tested that it's possible to alter char creation to use metric<->imperial conversion and allow player to set e.g. height in centimeters. But converting is not exactly precise as it has to contain rounding etc. So better way might be to change implementation. Instead of storing inches, we would store number which will be in inches for imperial or centimeters for metric system.

**Comment by Netys** [comment]
I'm living in country where only metric system is used, and imperial system is... Exotic. It isn't really a big problem, conversions are simple enough, but it requires some effort to conceive.

Rounding isn't really bad. We always assume there would be some measuring error, so rounding inchs to cm and tenth parts of inch to mm wouldn't be a problem. But it would be nice to make inch-based changes to change in cm, since otherwise it would be impossible to have values which aren't divisible by round inch value.

**Comment by openaz** [comment]
So I'm not only one from non-imperial-system country. My original idea was the rework, but I realized, that it would cause issues with CoC save editor, char viewer etc. So we definitely don't want to save values in metric system. And due to this, it doesn't make sense to work with metric system even in calculations as it won't be precise at all so it will loose the difference. So only question left is, if we want to convert imperial to metric for display purposes (e.g. scenes, appearance description etc).

**Comment by Kitteh6660** [comment]
The game still stores values in inches. To display centimeters, the game takes the original value and multiply it by 2.54. So it wouldn't seriously affect sizes.

**Comment by openaz** [comment]
I'll change question little bit :) Should I spend time to rewrite texts to reflect selected measurement system option? It would affect only displayed informations, nothing else.

**Comment by Netys** [comment]
No need to touch save values and internal representation, looks like Number which supports float point values is used everywhere, so some simple wrapper would work just fine. What I wanted to say — if integer inch values are used we can have like 10, 13, 15, 18, 20 cm but no values between.

But, TBH, this isn't a work which I'd consider high priority.

**Comment by alexolog** [comment]
Even though I am more comfortable with metric, I feel that a partial/inconsistent conversion is worse than no conversion at all.
